### ISSUE TITLE
Row resize handles are not visible when first column is hidden

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#3005] opened 2017-04-04 10:31 UTC
Can be reproduced here:
http://dojo.telerik.com/AWaGA/3

Version: 2017.1.223

**Comment by Dimitar-Goshev** [comment] 2017-08-25 08:33
Duplicate of: https://github.com/telerik/kendo-ui-core/issues/1815

**Closed by Dimitar-Goshev** 2017-08-25 08:33 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: Low
