### ISSUE TITLE
Editor closes <source> tags incorrectly

### ISSUE THREAD

**Issue by HansHappyHorizon** [telerik/kendo-ui-core#7521] opened 2023-09-15 08:41 UTC
### Bug report

The `<source>` tag in the Editor gets closed incorrectly. It's a void element, so it should either close itself or not have a closing tag at all. To quote MDN:
> The <source> element is a [void element](https://developer.mozilla.org/en-US/docs/Glossary/Void_element), which means that it not only has no content but also has no closing tag. That is, you never use "&lt;/source&gt;" in your HTML.
> 
> --- [&lt;source&gt;: The Media or Image Source element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source)

### Reproduction of the problem
Follow these steps:
- Create an editor with "`viewHtml`" enabled in the toolbar, e.g.:
```js
$("#editor").kendoEditor({ tools: ["viewHtml"] });
```
- Click the `</>` button to open the "view HTML" modal;
- Update the HTML with this snippet:
```html
<picture>
    <source media="(min-width: 0px)" srcset="https://picsum.photos/id/0/300/200.webp" type="image/webp" />
    <source media="(min-width: 0px)" srcset="https://picsum.photos/id/0/300/200.png" type="image/png" />
    <source media="(min-width: 0px)" srcset="https://picsum.photos/id/0/300/200.jpg" type="image/jpg" />
    <img src="https://picsum.photos/id/0/300/200.jpg" width="300" height="200" />
</picture>
```
- Click the "Update" button in the HTML modal;
- Now click the `</>` button again to view the HTML, and you'll notice that all `<source>` tags now have a `</source>` closing tag added.

### Current behavior
All the `<source>` get closing tags (`</source>`), which makes the HTML invalid as it's a void element. Above snippet would get turned into this (indented for readability):
```html
<picture>
    <source media="(min-width: 0px)" srcset="https://picsum.photos/id/0/300/200.webp" type="image/webp"></source>
    <source media="(min-width: 0px)" srcset="https://picsum.photos/id/0/300/200.png" type="image/png"></source>
    <source media="(min-width: 0px)" srcset="https://picsum.photos/id/0/300/200.jpg" type="image/jpg"></source>
    <img src="https://picsum.photos/id/0/300/200.jpg" width="300" height="200" />
</picture>
```

### Expected/desired behavior
The `<source>` should not get a closing tag, but should either close themselves, or not be closed at all.

### Environment

* **Kendo UI version:** 2023.2.829
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2023-12-12 09:00
@HansHappyHorizon Thank you for this detailed issue report. This issue is duplicate of https://github.com/telerik/kendo-ui-core/issues/4909
I have transferred the details from this issue to the previous one and I am closing the current one as duplicate. You may track the previous issue for any updates.

**Closed by Dimitar-Goshev** 2023-12-12 09:00 UTC
Labels: Bug, SEV: Low, C: Editor, FP: Unplanned
