### ISSUE TITLE
Unable to print PDFViewer's PDF on Safari

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#7243] opened 2023-03-02 15:04 UTC
### Bug report
Unable to print PDFViewer's PDF on Safari
Regression since 2022.2.802 , most probably related to the following fix in that release - https://github.com/telerik/kendo-ui-core/issues/6923

### Reproduction of the problem
1. Run this Fullscreen Dojo in Safari - https://runner.telerik.io/fullscreen/uhIVIDoW
2. Expand the overflow menu and tap on the Print tool

### Current behavior
The Print Options window is loaded, but PDF pages are not shown in the Print preview. PDF pages content is not present in the saved PDF, if we save the printed content to file.

### Expected/desired behavior
PDF pages are shown in the print preview window of Safari and can be saved to PDF
Working version 2022.2.621 - https://runner.telerik.io/fullscreen/abePoXEy 

### Environment
* **Kendo UI version:** 2023.1.117
* **Browser:** iPadOS 16.3 Safari

**Comment by sspasova** [comment] 2024-10-31 08:19
The issue is fixed with https://github.com/telerik/kendo/issues/20260

**Closed by sspasova** 2024-10-31 08:19 UTC
Labels: Bug, SEV: High, jQuery, Touch Devices, FP: Completed, C: PDFViewer
