### ISSUE TITLE
Bootstrap 4 does not work in responsive mode using the Telerik .NET Core "copying Kendo UI resources through NPM and Webpack" tutorial.

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#4796] opened 2019-01-25 12:17 UTC
Based on customer report:

> When following the "copying Kendo UI resources through NPM and Webpack" tutorial, and including Bootstrap 4 into the layout, the Bootstrap 4 responsive navbar behaves unexpectedly.  If I explicitly include a standard copy of jQuery into the layout, the Bootstrap components begin to work, but the Telerik components fail (likely because there are now two different instances of jQuery on the page).
>
> I'm assuming it has something to do with the way that the Kendo UI tutorial bundles and references the jQuery library into the main.js file using Webpack.
> 
> To reproduce:
>
> 1) Build and run the project maximized.  You will see that the navbar and dropdown within work normally.
> 2) Resize the window so that the navbar becomes responsive with the hamburger menu.
> 3) Click the dropdown.  Nothing will happen.  (It should drop down.)
> 4) Click the navbar.  Nothing will happen.  (It should collapse.)
> 5) Maximize the window.  The navbar will be too large.  (It should shrink back to its normal size.)

Reported in ticket 1382171

Note: the issue appears to be related to webpack bundling, because if I create an ad hoc bundle, be it minified or not, everything works as expected.

**Comment by jivanova** [comment] 2019-01-28 16:02
Also reported in 1384648

**Comment by Juveniel** [comment] 2019-02-18 07:00
The problem is related to point 4. of [the Copying Kendo UI Client Resources through NPM and Webpack](https://docs.telerik.com/aspnet-core/getting-started/getting-started-copy-client-resources#copying-kendo-ui-client-resources-through-npm-and-webpack) article. With the provided setup, jQuery is being bundled twice, thus leading to the observed behavior.

In order to correctly bundle Kendo UI and its jQuery dependency, the following definition should be used:
```js
import $ from 'jquery';
window.jQuery = $; window.$ = $;

import "@progress/kendo-ui";
import "@progress/kendo-ui/js/kendo.aspnetmvc";
import "@progress/kendo-theme-default/dist/all.css";
```

I will update the related article to reflect the above. Closing the issue.

**Closed by Juveniel** 2019-02-18 07:00 UTC
Labels: Bug, Kendo1, Kendo2, Priority 2, SEV: Low, Triaged
