### ISSUE TITLE
Root Menu item is not opened, if hovered before close animation completes

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5354] opened 2019-10-24 13:36 UTC
### Bug report
The menu open animation of root menu item does not occur if it is hovered before the close animation of the same item or another item completes.
Reported in ticket #1435709.

### Reproduction of the problem
1. Go to [Menu Animation demo](https://demos.telerik.com/kendo-ui/menu/animation)
1. Hover Furniture and wait for its open animation to end.
1. Quickly move the mouse over Storage, passing above the Menu.

### Current behavior
If Storage is hovered before the close animation of Furniture completes, Storage is not opened.

### Expected/desired behavior
Storage is opened.

NOTE: The issue is reproducible also if on step 3 the already opened root item is hovered again - Quickly move the mouse to the left of the item to trigger its close animation and immediately return the mouse over Furniture.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by ma3xdev** [comment] 2019-10-30 15:22
I think that the issue is not related to the fact that you jump from a submenu to a root element.
Just try this:

1. hover on "Decor" -> the sub-menu opens
2. don't hover on sub-menu items, but jump on "Lights" before the sub-menu disappear completely
Bem! The Lights sub-menu doesn't open

while if you
1. hover on "Decor" -> the sub-menu opens
2. don't hover on sub-menu items and leave the mouse from "Decor"
3. let the sub-menu completely close
4. hover on "Lights"
this time the Lights sub-menu opens

But I don't think this is related to jump to another menu before the previous sub-menu is closed, because if you slide horizontally through the whole menu bar, each sub-menu opens correctly.
Maybe could be some issue on the mouse over-mouse leave and mouse over again on another menu element when a sub-menu is not still completely closed.

These are my 2 cents.

**Comment by Dimitar-Goshev** [comment] 2019-11-14 08:47
@ma3xdev Thank you for sharing your observations. I updated the description of the issue.

**Comment by martintabakov** [comment] 2020-01-10 10:53
Also mentioned in thread #1448642.

**Comment by ma3xdev** [comment] 2020-01-29 16:07
Now the issue seems to have been resolved. No more problems on the root menu, but it seems to be still presente in the submenus.
Imagine to have a menu with 2 submenus in its dropdown elements: if you try to open one submenu and then (without selecting any items in the submenu) move fast over the second submenu root element before the first submenu closes, the second submenu doesn't open.

**Comment by ma3xdev** [comment] 2020-02-14 08:33
While you're working on solving this issue, could you tell us how to speed up the submenu closing effect?
In this way we can reduce the incidence of the issue.
Thank you in advance.

**Comment by aleksandarevangelatov** [comment] 2020-03-19 13:23
Also mentioned in thread #1458085

**Comment by Dimitar-Goshev** [comment] 2020-06-25 08:15
A similar issue with sub items' animation - https://github.com/telerik/kendo-ui-core/issues/5875

**Comment by Iankodj** [comment] 2021-01-14 10:54
Related to: https://github.com/telerik/kendo-ui-core/issues/4506

**Closed** 2021-01-25 09:33 UTC
Labels: Bug, C: Menu, FP: Completed, Kendo2, Next LIB, Priority 2, SEV: Low
