### ISSUE TITLE
DropDownTree popup triggers page scroll and closes automatically 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6074] opened 2020-10-14 13:57 UTC
### Reproduction of the problem
Dojo example: [http://dojo.telerik.com/ePEPAtEl/3](http://dojo.telerik.com/ePEPAtEl/3)
Two scenarios: 
1. The DropDownTree's **height** is set to "auto" and there are enough nodes in the embedded treeview, so that the when the popup shows up a vertical scrollbar appears. In Chrome and IE, when the scrollbar appears the page is scrolled down automatically, which causes the popup to close. 

2. **height** is not set explicitly in the DropDownTree (remove the setting from the dojo example). If the browser window is resized so that there isn't enough space for the whole popup to be displayed, on the popup showing up, the same behavior as in 1. is observed. 

### Current behavior
The popup closes automatically.

### Expected/desired behavior
The popup remains open.

### Environment

* **Kendo UI version:** 2020.3.915
* **jQuery version:** x.y
* **Browser:** [Chrome 85 | IE11 ]

**Comment by zdravkov** [comment] 2020-10-20 14:22
Duplicate of #4776

**Comment by Dimitar-Goshev** [comment] 2020-10-28 09:02
The issue is fixed in Chrome, but still reproducible in IE11.

**Closed** 2020-10-30 13:34 UTC
Labels: Bug, C: DropDownTree, FP: In Development, Kendo2, SEV: Medium
