### ISSUE TITLE
Left Spacing between ComboBox and DropDownList in FireFox is not uniform after 2018.1.x

### ISSUE THREAD

**Issue by tharlinsmith** [telerik/kendo-ui-core#4347] opened 2018-06-28 18:19 UTC
### Bug report

The current selection label used to be positioned the same between these two controls, but in 2018 are now different.  This persists in 2018.2.620.  Appears correctly in current Safari and Chrome.

Related to #4200.

### Current Behavior
![screen shot 2018-06-28 at 11 14 19 am](https://user-images.githubusercontent.com/4153458/42052716-6e0cc88e-7ac4-11e8-8e89-624d354b466b.png)

### Expected/desired behavior
![screen shot 2018-06-28 at 11 14 48 am](https://user-images.githubusercontent.com/4153458/42052743-81c5c506-7ac4-11e8-81e4-bd4ea4f416ae.png)

### Environment

* **Kendo UI version:** 2018.2.620
* **jQuery version:** 1.8.3
* **Browser:** Firefox 60.0.2

**Comment by Dimitar-Goshev** [comment] 2018-07-11 06:47
@tharlinsmith Thank you for reporting this issue. It is a duplicate of the one that you referenced, so I am closing it to avoid duplication.

**Closed by Dimitar-Goshev** 2018-07-11 06:47 UTC
Labels: Appearance, C: ComboBox, C: DropDownList, Kendo2
