### ISSUE TITLE
DateTimePicker time now button does not work

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-ui-core#7371] opened 2023-06-08 16:38 UTC
### Bug report
DateTimePicker time now button does not work

### Reproduction of the problem
1. Run [dojo](https://dojo.telerik.com/@vzsoft/AcaJeBaH)
2. open datetimepicker popup
3. goto tab time
4. click time now button
5. not work!

### Screenshots
![datetime](https://github.com/telerik/kendo-ui-core/assets/5305981/7ca143f1-c30c-4400-8fcf-e39b5557d355)

### Environment
* **Kendo UI version:** 2023.2.606
* **jQuery version:** 3.7
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment] 2023-06-09 06:35
@vzsoft Thank you for your feedback. This issue is duplicate of https://github.com/telerik/kendo-ui-core/issues/7301 , which you may track for progress.

**Closed by Dimitar-Goshev** 2023-06-09 06:35 UTC
Labels: FP: Unplanned
