### ISSUE TITLE
Editor create table tool breaks using latest jQuery with SASS theme

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-ui-core#5797] opened 2020-05-25 02:58 UTC
### Bug report
The editor's create table tool bugs out when using the latest version of jQuery (3.5.1) with any SASS theme.
It works fine in the examples because they all use jQuery 1.12.3 (works up to 2.2.4)
![dojo telerik com_iXaLoSOl](https://user-images.githubusercontent.com/40481873/82773832-9ec08200-9e75-11ea-9a24-af6e9b09dfec.png)

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/editor/index
2. Edit the example
3. Change jQuery version to 3.5.1
4. Click on create table tool

### Environment
* **Kendo UI version:** 2020.2.513
* **jQuery version:** 3.5.1
* **Browser:** all

**Comment by Juveniel** [comment] 2020-10-27 06:10
The issue is fixed as of Kendo 2020 R3 with the following commit https://github.com/telerik/kendo/commit/719dc9a85cd21dce3d878da9d96c32a6312d82e2.

**Comment by Dimitar-Goshev** [comment] 2020-10-27 06:36
The fix is confirmed by the following [Dojo snippet](https://dojo.telerik.com/EvIDaRoJ) with jQuery 3.5.1

**Closed by Dimitar-Goshev** 2020-10-27 06:36 UTC
Labels: Bug, C: Editor, FP: In Development, Kendo2
