### ISSUE TITLE
Wrong number formatting in es-SV culture (possibly others too)

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2421] opened 2016-11-07 08:16 UTC
### Bug report

kendo.toString() outputs wrong number format in es-SV culture.

### Reproduction of the problem

[http://dojo.telerik.com/utEmo/3](http://dojo.telerik.com/utEmo/3)

### Current behavior
kendo.toString(125678.99, "#,#.##") returns ,125,678.99

### Expected/desired behavior
kendo.toString(125678.99, "#,#.##") returns 125,678.99

### Environment

* **Kendo UI version:** 2016.1.226+
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ggkrustev** [comment] 2017-02-09 08:58
The problematic code is in the custom number formatting:

https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L782

**Comment by veselints** [comment] 2017-07-10 08:37
The same issue applies to es-US culture too. The formatter does not interpret correctly the *grouSize* configuration, in which the last member is 0 (for example *groupSize: [3,0],* as it is in the es-US culture).

[Here is a simple Dojo, reproducing the issue with custom culture](http://dojo.telerik.com/ocUZU/3)

**Comment by veselints** [comment] 2017-07-10 08:52
Related to [this item](#2899).

**Comment by Xizario** [comment] 2017-07-11 11:23
@ivanchev, looking at the commit, it looks related to this pull request: https://github.com/telerik/kendo-ui-core/pull/3339
Is the pull request still valid, or we should close it without merge?

**Comment by ivanchev** [comment] 2017-07-11 13:46
I would say the pull request is more related to this issue [2899](https://github.com/telerik/kendo-ui-core/issues/2899), since it covers what culture has what group size. The issue must be resolved before the pull request is evaluated.

The current issue is related to wrong reading of the [3, 0] setting, regardless of the culture , which is a valid setting (see examples [here](https://msdn.microsoft.com/en-us/library/system.globalization.numberformatinfo.percentgroupsizes(v=vs.110).aspx))

**Comment by Dimitar-Goshev** [comment] 2017-07-28 15:06
The issue is fixed and not reproducible in any kendo culture.

**Closed** 2017-07-28 15:05 UTC
Labels: Bug, F: Globalization, Kendo2, SEV: Medium
