### ISSUE TITLE
Spreadsheet Validation dialog appears behind the Window in which the Spreadsheet is placed

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3757] opened 2017-11-13 08:50 UTC
### Bug report
If the Spreadsheet widget is placed within a Kendo Window, when validation error occurs, the validation window appears behind the Window.

![2017-11-13_1050](https://user-images.githubusercontent.com/3431388/32716943-935bbd6e-c860-11e7-824b-50ee9bbcb9e9.png)

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/aYogaW/3);
* Type invalid input in any of the cells with validation;
* **Click in another cell to remove the focus from the edited cell and trigger validation;**

### Current behavior
The validation dialog will appear behind the Kendo Window - move the window to see it.

### Expected/desired behavior
The validation dialog will appear in front of the Kendo Window

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by mishoo** [comment] 2017-12-08 08:41
Is this still an issue?  It appears to be no longer replicable.

**Comment by mishoo** [comment] 2018-07-03 11:38
No longer reproducible.

**Comment by Dimitar-Goshev** [comment] 2018-07-05 08:39
It is still reproducible when "Click in another cell to remove the focus from the edited cell and trigger validation;" is performed.

**Comment by PedroHMLima** [comment] 2018-12-18 12:50
Is there any forecast for this issue? We have opened a support ticket because we have an implementation to do for a client and this bug is annoying because when it is opened behind the window the user thinks the application is just not working.

**Comment by Dimitar-Goshev** [comment] 2018-12-21 09:05
@PedroHMLima Issues fixing order is based on their priority and severity. We will try to fix it for R1 2019 release, but it is possible that the fix may be postponed.

**Comment by mparvanov** [comment] 2019-01-11 14:43
The following issues are reproducible with the latest version (http://kendobuild.telerik.com/dojo-staging/EpOyezOY):
1. (Reproducible also in the original dojo sample) : Type invalid input in any of the cells with validation. Click in another cell and on the Validation dialog click "Retry" . The user is not enabled to reenter a value but the validation dialog pops up again

1. (Regression) Type invalid input in any of the cells with validation. Click in another cell and on the Validation dialog click Cancel. The dialog disappears but the overlay on the window stays modal and the user cannot edit the Speadsheet data neither to close the Window.

**Comment by mparvanov** [comment] 2019-01-14 13:14
The issue is related to Kendo Window widget and will be researched additionally.

**Comment by mparvanov** [comment] 2019-01-21 13:01
The initial issue has been resolved. The issue with user not enabled to reenter a value but the validation dialog pops up again when pressing Retry button in the validation dialog could be resolved by setting autoFocus to false:
https://dojo.telerik.com/iQUmecEb

**Closed** 2019-01-21 13:02 UTC
Labels: Bug, C: Spreadsheet, C: Window, Kendo2, Priority 2, SEV: High, Triaged
