### ISSUE TITLE
Adding reference to a cell in another sheet by navigating to it is impossible

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6447] opened 2021-06-04 16:06 UTC
### Reproduction of the problem
Reproducible in the [demos](https://demos.telerik.com/kendo-ui/spreadsheet/index):
1. Create a second sheet.
2.  Select the new sheet ("Sheet1") and scroll the horizontally to column U. Add a value to the U1 cell.
3. Select the first sheet ("Food Order").
4. Select A17 and enter the following value: =SUM(C5,
5. Select "Sheet1" and try to navigate to U1 either through the keyboard or through scrolling the sheet.

### Current behavior
A popup with an error message appears.

### Expected/desired behavior
The user should be able to navigate to the desired cell, in order to add it as a reference to the formula.

### Environment

* **Kendo UI version:** 2021.2.511
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by sspasova** [comment] 2024-01-25 14:10
I am closing this because the issue is no longer reproducible using Kendo UI 2023.3.1114.

**Closed by sspasova** 2024-01-25 14:10 UTC
Labels: Bug, SEV: Medium, C: Spreadsheet, jQuery, FP: Unplanned, Triaged
