### ISSUE TITLE
The TreeList will not re-evaluate the checkbox template if the dataSource values are changed.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3799] opened 2017-11-27 14:41 UTC
### Bug report

The TreeList will not re-evaluate the checkbox template if the dataSource values are changed.

More details and a runnable example are available in ticket: 1141320 

### Environment

* **Browser:** [all

**Comment by ag-petrov** [comment] 2018-04-20 10:13
The problem reported in the ticket is caused by the fact that some of the nodes have the same exact HTML as the new ones that will be rendered. We have internal caching logic which check whether the HTML content is the same as the new and if it is it uses the cache. When clicking on a checkbox it's HTML is not altered, however it visually appears different. Modifying the logic to re-render the content when it is the same defeats the purpose of using caching and will break the current behavior. Thus I am marking this as won't fix. 

As a possible workaorund I suggest clearing the cached tree by executing the following code.

`$('#treelist').data('kendoTreeList')._contentTree.render([]);`

**Closed by ag-petrov** 2018-04-20 10:13 UTC
Labels: Bug, C: TreeList, Kendo1, Priority 1, SEV: Low
