### ISSUE TITLE
Window's content iFrame height is limited to 150px on Safari

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5817] opened 2020-06-01 14:59 UTC
### Bug report
The issue is reproducible with a maximized Window or Window with height more than 150px.

SASS - When using Kendo Default v2, Bootstrap v4 or Material v2 theme and attempting to display a maximized Kendo Window with iFrame content, the iFrame does not take up the full height of the Kendo Window.
The behavior is observed with Safari browser on MacOS X or iOS. Not reproducible on Windows with Chrome device emulation.

LESS - regression since R1 2021 - 2021.1.119

### Reproduction of the problem
SASS - Run this [dojo with Bootstrap-v4 bug example - 2021.1.330](https://dojo.telerik.com/@Dimitar-Goshev/OMEXiDIz)
Also reproducible with older version [2020.2.513 Dojo](https://dojo.telerik.com/@AleksandarEvangelatov/UrOKeZew)

LESS - Run this [Dojo with Default](https://dojo.telerik.com/@Dimitar-Goshev/UzANokAq)

### Expected/desired behavior
The iFrame should take up the full height of the Kendo Window.

Adding the following style resolves the observed behavior:
```
<style type="text/css">
    .k-window-content.k-window-iframecontent {
        height:100%;
    }
</style>
```

### Environment
* **Kendo UI version:** 2021.1.330
* **Browser:** [Safari | iOS Safari]

**Comment by PekoPPT** [comment] 2020-12-14 08:39
Also reported in ticket: 1498708

**Comment by Dimitar-Goshev** [comment] 2021-04-05 09:53
Reported in ticket 1513871 - increasing priority. Reproducible with 2021.1.330

**Comment by Dimitar-Goshev** [comment] 2021-04-12 15:55
Reported in ticket 1514879 . Regression for LESS themes - works as expected with 2020.3.1118

**Comment by Juveniel** [comment] 2021-12-01 11:59
@Dimitar-Goshev the issue can be reproduced in the Safari browser with iOS < 14. In iOS 14 and 15 the issue is no longer reproducible. Taking this into consideration, the provided workaround in this issue can be utilized for older versions of iOS.

 Closing the issue.

**Closed by Juveniel** 2021-12-01 11:59 UTC
Labels: Bug, C: Window, SEV: Low, jQuery2, Priority 5, FP: Planned
