### ISSUE TITLE
Performance issue when PDF is exported using Drawing API in Chrome 100

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6797] opened 2022-04-15 12:32 UTC
### Bug report

When exporting large content to PDF using the DrawingAPI it takes much more time in Chrome 100 version compared to Chrome 98 or Chrome 99.

### Reproduction of the problem
1. Open the Dojo example - https://dojo.telerik.com/@NeliKondova/upICAkol
2.  Try to export it using Chrome 98, 99 and 100

### Current behavior
The file is exported for about 7-8 seconds with Chrome 98 or 99 and for more than 13 seconds in Chrome 100.

### Expected/desired behavior
There should be no performance issues when exporting large content to PDF in Chrom 100. The issue can be replicated also when using a lot of textareas for example. 

### Environment

* **Kendo UI version:** 2022.1.301
* **Browser:** [Chrome 100]

**Comment by nelito987** [comment] 2022-04-15 12:34
The issue is logged also in kendo-drawing repo: https://github.com/telerik/kendo-drawing/issues/240

**Comment by sspasova** [comment] 2024-02-21 09:14
I am closing this issue because it is no longer reproducible using Chrome 121 and Kendo UI 2024.1.130

**Closed by sspasova** 2024-02-21 09:14 UTC
Labels: Bug, SEV: Low, F: Drawing, F: PDF Export, jQuery, FP: Unplanned, Triaged
