### ISSUE TITLE
Spreadsheet - set cell height to default, after removing multi-line content in a cell

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3527] opened 2017-08-24 07:08 UTC
Spreadsheet - set cell height to default, after removing multi-line content in a cell. Currently, the cell retains the height as per the lines, that were present in the cleared cell. In this scenario MS Excel sets the height back to the default:
![spreadsheetmultilinetextrowheight](https://user-images.githubusercontent.com/3431388/29654016-2e7f9e10-88b4-11e7-9898-2a2f8fc6bdf1.gif)

**Comment by mishoo** [comment] 2018-07-03 11:16
Closing as duplicate of #1874 (also see [this comment](https://github.com/telerik/kendo-ui-core/issues/1874#issuecomment-231668222)).

**Closed by mishoo** 2018-07-03 11:16 UTC
Labels: C: Spreadsheet, Enhancement, Kendo2
