### ISSUE TITLE
Multiple issues in the Switch widget styles

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#2721] opened 2017-02-06 10:05 UTC
### Bug report

There are a few issues in the Switch widget styles in recent versions, probably because of [this commit](https://github.com/telerik/kendo-ui-core/commit/b34ba55997038df682e0a6ceaec08ee2193b2d37).

* Switches show an unneeded border: [Dojo](http://dojo.telerik.com/odOfO/2)
* When using switches in a dark theme like Material, they show a light background:  [Dojo](http://dojo.telerik.com/odOfO).

* Web version of styles shows incorrect styles. This Dojo (opened from a demo) shows switches styles wth Nova styles showing the layout of the Flat theme with only the Nova color scheme: [Dojo](http://dojo.telerik.com/okOdE).

### Environment

* **Kendo UI version:** 2017.1.118 (probably some older versions as well)

**Comment by Dimitar-Goshev** [comment] 2018-07-03 08:16
Duplicate of https://github.com/telerik/kendo-ui-core/issues/3568
I copied the scenarios described above to the other issue for reference.

**Closed by Dimitar-Goshev** 2018-07-03 08:16 UTC
Labels: Appearance, C: Switch, Kendo1, Kendo2
