### ISSUE TITLE
Spreadsheet hyperlink does not work if it is in a Column, that has filter enabled

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2745] opened 2017-02-09 09:25 UTC
### Bug report
Spreadsheet hyperlink does not work if it is in a Column, that has filter enabled

### Reproduction of the problem
- Go to the [Index demo](https://demos.telerik.com/kendo-ui/spreadsheet/index);
- Create a hyperlink in a cell in one of the columns;
- Select the cells in the same column;
- Click on the Filter Toolbar icon to allow filtering;
- Hyperlink is not working anymore;

### Expected/desired behavior
Hyperlink should work, even if part of filterable column;

**Comment by mishoo** [comment] 2017-02-10 08:44
The problem is that there's a `div.k-spreadsheet-filter` overlaid above the content (probably just to highlight the active filter range).  This div prevents clicks from reaching the link (it also can be seen that the mouse cursor does not change when hovering the link, as it should).

I'm not sure how to fix this.  Seems a minor one though, maybe “won't fix” is the answer.  @gyoshev thoughts?

**Comment by gyoshev** [comment] 2017-02-10 11:46
CSS to the rescue!

    .k-spreadsheet .k-filter-wrapper { pointer-events: none; }
    .k-spreadsheet .k-spreadsheet-filter { pointer-events: all; }

We'll keep the styling and the filter icons will still be focusable.

**Closed** 2017-02-10 11:52 UTC
Labels: Bug, C: Spreadsheet, SEV: Low
