### ISSUE TITLE
Right tab scroller disappears when the last tab is selected and the TabStrip width is reduced

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1038] opened 2015-08-14 10:53 UTC
Reproducible here: [http://dojo.telerik.com/eqiGA](http://dojo.telerik.com/eqiGA)

Prerequisites: 
TabStrip with many scrollable tabs

Steps:
1. Maximize the browser window
2. Select the right-most tab
3. Restore the browser window to not maximized state

Result:
The  content for the tab selected is still displayed but the tab is no longer visible and the right side scroll button disappears.

Reported in Ticket ID: [961790]

**Comment by dimodi** [comment] 2015-08-14 11:05
http://docs.telerik.com/kendo-ui/web/tabstrip/overview#scrollable-tabs

If the TabStrip has no fixed width and is placed in a fluid layout, it can re-check if tab scrolling becomes necessary, or is no longer required. To achieve this, execute the widget's resize() method, e.g. in window.resize.

**Comment by dimodi** [comment] 2015-08-14 11:33
The issue is now fixed, however, the described scenario requires the TabStrip's resize() method to be executed when the TabStrip width is changed, e.g. in the browser window's resize event.

http://docs.telerik.com/kendo-ui/web/tabstrip/overview#scrollable-tabs

**Closed** 2015-08-14 11:34 UTC
Labels: Bug, C: TabStrip, SEV: Low
