### ISSUE TITLE
Missing event indication in Scheduler Month view, if an event starts on a previous day and there are at least 3 events before it

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3953] opened 2018-01-31 13:49 UTC
### Bug report
The Scheduler Moth view does not display events which:
* Should be visible on a specific date, as only one or two events are present on that date;
* Start on a previous date;
* Are not visible on that previous date as other events are displayed as first and second events for that date;

Moreover, if the event in question is the third event on the date on which it starts, the `show more` ellipses will be present on the date on which it is the only event. If the event is the fourth or next in the row on its starting day (fifth, sixth etc.), `show more` wont be displayed at all and the day will remain completely empty in the view.

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/ANeno/10);
* On 29 Jan only the ellipses will be present, even if the *The Internship* and the *Now You Dont* events are both scheduled for that date;
* Nothing will be displayed on the 30 Jan, even if the *Now You Dont* event is scheduled for that date;

**Comment by zdravkov** [comment] 2018-02-05 12:54
We have inspected the scenario and updated the issue to the following cases:
1) The lack of the events on the 29th is caused by the fact that the other 2 'long' events are already rendered and the rows that are available are already taken. The same behavior is observed in MS Outlook so if anybody wants this feature improved in some way I will recommend submitting a feature request about it in our [feedback portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) and shareing a possible design that should be added to handle these case.
2) The lack of "more" button in the 30th slot is a the actual bug that is going to be fixed with this issue.

**Comment by Dimitar-Goshev** [comment] 2018-02-12 14:18
After the fix, there is an indication for the presence of an event on 30th, as in Outlook:
![image](https://user-images.githubusercontent.com/6614183/36100866-5836ae2c-1010-11e8-9d6e-e92f89f04441.png)

**Closed by Dimitar-Goshev** 2018-02-12 14:18 UTC
Labels: C: Scheduler, Kendo2, SEV: Medium
