### ISSUE TITLE
Cascading child DropDownList not enabled if parent has filter set (IE)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2238] opened 2016-09-30 10:19 UTC
### Bug report

When the parent DDL has filter set the child is not enabled on parent item selection. Works as expected in Chrome and Firefox.

### Reproduction of the problem
In the following sample [dojo](http://dojo.telerik.com/ELuki) the Categories DDL has filter: "contains" set, which causes the Products DDL not to be enabled after an item is selected in Categories. 

### Current behavior
The child DDL is not enabled thus the cascade does not occur. 

### Expected/desired behavior
The child DDL should be enabled on item selection in the parent. 

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** x.y
* **Browser:** [IE11, 10 ]

**Comment by dimodi** [comment] 2016-10-03 14:30
Duplicate of https://github.com/telerik/kendo-ui-core/issues/1796

**Closed** 2016-10-03 14:31 UTC
Labels: Bug, C: DropDownList, Deleted, SEV: Medium
