### ISSUE TITLE
Selected item in Grid Pager is not visible in LESS Bootstrap theme

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#5677] opened 2020-03-18 14:38 UTC
### Bug report

The selected item in Grid Pager is not visible in LESS Bootstrap theme. The text color is white on white background

### Reproduction of the problem

1.  Go to the following demo: https://demos.telerik.com/kendo-ui/listview/remote-data-binding
1. Select Less Boostrap v3 theme
1. Check the selected page in the pager

### Current behavior
The text color is white on white background

### Expected/desired behavior
The selected page should be visible

### Environment

* **Kendo UI version:** 2019.1.115

**Comment by dmanova** [comment] 2020-03-23 10:18
Closing as duplicate of #5621

**Closed by dmanova** 2020-03-23 10:18 UTC
Labels: Appearance, C: Pager, Priority 1, SEV: Medium
