### ISSUE TITLE
Component is not working at all with jQuery 3.0.0

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1878] opened 2016-07-04 14:29 UTC
Spreadsheet component doesn't work at all with jQuery 3.0.0

http://dojo.telerik.com/@ipeshev/uHuHa

**Comment by tsvetomir** [comment] 2016-08-05 14:50
That might take a while judging by the look of it.

@mishoo feel free to ping @gyoshev regarding JQ3 compatibility problems

**Comment by mishoo** [comment] 2016-08-16 07:24
The bug is in `kendo.list.js`:

![error](https://cloud.githubusercontent.com/assets/334725/17690970/b2a28bde-639a-11e6-97de-1793b3cce26e.png)

`this.options.cascadeFrom` is the empty string, and we end up calling jQuery for a `"#"` selector.  Apparently that worked in earlier versions, but not anymore.  If I add these lines [here](https://github.com/telerik/kendo/blob/master/src/kendo.core.js#L3474):

```js
        if (selector == "#") {
            selector = "#IM_PRETTY_SURE_THIS_DOESNT_EXIST";
        }
```

the problem is fixed, but that's not a nice solution...  Maybe someone more knowledgeable about the List should take a look.  /cc @ggkrustev @tapopov

**Comment by ggkrustev** [comment] 2016-08-16 07:50
I will take a look, but I am sure that the fix will be something similar

**Comment by gyoshev** [comment] 2016-08-16 08:07
I believe [this is fixed in the jquery-3 branch](https://github.com/telerik/kendo/commit/95ace8e1b6ae9326621b7502913ab2f75824cd89#diff-a6be501c990c93aafa7baa3090bb6a02R1191). Maybe cherry-pick this, so the issue is fixed now, instead of waiting for the branch to be merged?

**Closed** 2016-08-16 09:03 UTC
Labels: Bug, C: DropDownList, C: Spreadsheet, SEV: High
