### ISSUE TITLE
Invalid ARIA attribute

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-ui-core#2374] opened 2016-10-28 10:03 UTC
### Reproduction of the problem

The widget have the following issue with WAI-ARIA specification:
- The `ul` element with `listbox` role have no children when no items are selected - the spec says that this role require at least one children with role `option`. Should we hide/remove this element when there are no options?

Ticket: 1071137
### Environment
- **Kendo UI version:** 2016.2 607
- **jQuery version:** 1.9.1
- **Browser:** all

**Comment by Dimitar-Goshev** [comment] 2019-02-14 07:08
Duplicate of https://github.com/telerik/kendo-ui-core/issues/4812
I am closing this issue and relating it to the other one, which suggests reconsidering the role currently used.

**Closed by Dimitar-Goshev** 2019-02-14 07:08 UTC
Labels: Accessibility, Bug, C: MultiSelect, Kendo2, SEV: Low
