### ISSUE TITLE
Kendo DeepExtend removes arraybuffer

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-ui-core#5122] opened 2019-06-19 09:46 UTC
i used pdf viewer in angular, and I passed 'pdfsrc' which is of type ArrayBuffer. when loading pdf, error occurred.

I tried to figure it out and found that after doing the operation 'kendo.deepExtend' (see picture below), 
the 'data' property became '{ }' instead of its original value of type 'Arraybuffer'
![image](https://user-images.githubusercontent.com/34930870/59755220-1c6d2c80-92ba-11e9-9263-5727eb295a75.png)

![image](https://user-images.githubusercontent.com/34930870/59755456-838ae100-92ba-11e9-966f-8e392e957822.png)

![image](https://user-images.githubusercontent.com/34930870/59755483-8c7bb280-92ba-11e9-879d-70ca9024b055.png)

```
public ngOnChanges(changes: SimpleChanges): void {
    if (changes.pdfSrc && !changes.pdfSrc.isFirstChange()) {
      const pdfSrc = this.pdfSrc;
      if (this.pdfViewer) {
        this.isLoaded = false;
        this.pdfViewer.fromFile(pdfSrc);
      } else {
        this.pdfViewer = kendo.jQuery('#pdf-viewer').kendoPDFViewer({
          pdfjsProcessing: {
            file: {
              data: pdfSrc
            }
          },
          width: '100%',
          height: '100%',
          view: {
            type: 'canvas'
          },
          toolbar: {
            items: [
              'pager', 'spacer',
              {
                type: 'button',
                text: 'zoom in',
                id: 'zoomin',
                click: e => {
                  const toolbar = e.sender;
                  this.currentScaleNum = this.currentScaleNum + 1;
                  if (this.currentScaleNum <= this.maxScaleNum) {
                    const pages = kendo.jQuery('.k-page');
                    const scale = 1 + '.' + this.currentScaleNum;
                    Array.from(pages).forEach((s: any) => {
                      s.style.transform = `scale(${scale})`;
                    });
                  } else {
                    this.currentScaleNum = this.maxScaleNum;
                  }

                  if (this.currentScaleNum === this.maxScaleNum) {
                    toolbar.enable('#zoomin', false);
                  } else {
                    toolbar.enable('#zoomin', true);
                  }

                  toolbar.enable('#zoomout', true);
                }
              }, {
                type: 'button',
                text: 'zoom out',
                id: 'zoomout',
                enable: false,
                click: e => {
                  const toolbar = e.sender;
                  this.currentScaleNum = this.currentScaleNum - 1;
                  if (this.currentScaleNum >= 0) {
                    const pages = kendo.jQuery('.k-page');
                    const scale = 1 + '.' + this.currentScaleNum;
                    Array.from(pages).forEach((s: any) => {
                      s.style.transform = `scale(${scale})`;
                    });
                  } else {
                    this.currentScaleNum = 0;
                  }

                  if (this.currentScaleNum === 0) {
                    toolbar.enable('#zoomout', false);
                  } else {
                    toolbar.enable('#zoomout', true);
                  }

                  toolbar.enable('#zoomin', true);
                }
              },
              'download'
            ]
          },
          // messages: {
          //   defaultFileName: 'haha'
          // },
          render: e => {
            if (!this.isLoaded) {
              this.isLoaded = true;

              this.pdfViewer.activatePage(this.pdfPageNumber);
            }
          }
        }).data('kendoPDFViewer');
      }
    }
  }
```

**Comment by jiangyh1024** [comment] 2019-06-21 04:28
I am here to tell u that I've found a workaround. Convert arraybuffer to base64 and pass it to  

 pdfjsProcessing: {
            file: base64String
          },

**Comment by jivanova** [comment] 2019-06-21 06:58
@jiangyh1024 Thanks! The issue is fixed and if it passes our testing procedures, it will be included in the Next Latest Internal Build.

**Comment by Dimitar-Goshev** [comment] 2019-06-24 06:32
@jivanova After the fix, there is a JS error in IE 9 - 'ArrayBuffer' is undefined - kendo.core.js (1853,13)

**Comment by jiangyh1024** [comment] 2019-06-24 09:41
there's a polyfill you can use

https://github.com/inexorabletash/polyfill/blob/master/typedarray.js

**Comment by Dimitar-Goshev** [comment] 2019-06-27 07:23
@jiangyh1024 Thank you for the update. The issue is fixed now and it will be included in our next latest internal build. As a side note, I see that you are creating custom zoom in and zoom out buttons. We are currently implementing this feature as a built-in one and it is expected for our next major release - R3 2019.

**Closed by Dimitar-Goshev** 2019-06-27 07:23 UTC
Labels: Bug, FP: In Development, Kendo2, Next LIB
