### ISSUE TITLE
[Duplicate] Provide validation for the End DatePicker in the Edit popup 

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3392] opened 2017-07-10 11:30 UTC
### Bug report

[demo](http://demos.telerik.com/kendo-ui/scheduler/index)

### Reproduction of the problem

1. Double click on an event to start editing
2. Select some value from the Repeat dropdown
3. Set invalid value for the End date

### Current behavior
Uncaught TypeError: Cannot read property 'getFullYear' of null. Change event is fired and error is thrown.

### Expected/desired behavior
End field is validated

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** all

**Comment by Dimitar-Goshev** [comment] 2017-12-12 09:14
Closed as duplicate of: https://github.com/telerik/kendo-ui-core/issues/2117

**Closed by Dimitar-Goshev** 2017-12-12 09:14 UTC
Labels: Bug, C: Scheduler, Kendo2
