### ISSUE TITLE
Diagram popup toolbar needs class k-diagram-toolbar

### ISSUE THREAD

**Issue by GeorgeGindev** [telerik/kendo-ui-core#6229] opened 2021-01-12 16:42 UTC
### Reproduction of the problem
The Diagram component is missing class for the toolbar inside the popup, and it cannot be targeted to be styled.
https://supportheroes.telerik.com/ticket/1501571

### Expected/desired behavior
The toolbar in the Diagram component should have class k-diagram-toolbar.

**Comment by ag-petrov** [comment] 2024-01-10 07:59
This is not a bug, the rendering is ok. Moreover we have updatde the widgets to use the toolbar widget which is also updated. Closing this one

**Closed by ag-petrov** 2024-01-10 07:59 UTC
Labels: Bug, Enhancement, SEV: Low, C: Diagram, jQuery, Priority 1
