### ISSUE TITLE
Scheduler events are not read by screen readers when navigating between events with Tab/Shift+Tab

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#5247] opened 2019-09-04 14:39 UTC
### Bug report
Scheduler events are not read by screen readers when navigating between events with Tab/Shift+Tab
This is regression since R3 2017 (2017.3.913)
When an event is clicked, `id` and `aria-label` attributes are added to its element and `aria-activedescendant` attribute is added to the Scheduler.
But when an event is selected with keyboard, these attributes are not added to the event and the Scheduler

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/scheduler/selection
1. Click on a Scheduler timeslot on Sunday
1. Press Tab key

### Current behavior
"Meeting with customers" event is focused, but its title and duration are not read by screen readers.

### Expected/desired behavior
"Meeting with customers" event is focused. Its title and duration are read by screen readers using the event's aria-label attribute, containing info about title and duration.
R2 2017 SP1 (2017.2.621) - https://dojo.telerik.com/iWizuMAV

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by veselints** [comment] 2019-09-09 12:56
Related to: https://github.com/telerik/kendo/issues/7400
and: https://github.com/telerik/kendo-ui-core/issues/3303

**Comment by veselints** [comment] 2019-09-10 12:18
The fix has been implemented and reviewed in the following environment:
- Chrome + ChromeVox;
- Edge + Narrator;
- IE + JAWS;
- Firefox + NVDA;

In Firefox, for some reason, after the second navigation, the NVDA reader announces the title of the previously selected and the current event. I have tested the same scenario with version 2017.2.621 of Kendo (https://dojo.telerik.com/iWizuMAV) where the issue is also present.

**Comment by veselints** [comment] 2019-09-10 13:33
PR: https://github.com/telerik/kendo/pull/10051

**Closed** 2019-09-16 09:05 UTC
Labels: Accessibility, Bug, C: Scheduler, FP: In Development, Kendo2, Priority 5, SEV: High, Triaged
