### ISSUE TITLE
When an item is selected in the left panel and setDataSource is used in FileManager, the left panel becomes empty

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7129] opened 2022-11-28 12:14 UTC
### Bug report

When an item is selected in the left panel and setDataSource is used in FileManager, the left panel becomes empty. The behavior does not occur if the _setDataSource_ method is used without previously selecting an item. 

### Reproduction of the problem
1. Open the [Dojo](https://dojo.telerik.com/@NeliKondova/ISIFUPOQ).
2. Select the 'Documents' folder
3. Click on the 'Reset data' button. 

### Current behavior
The left panel in FileManager becomes empty.

### Expected/desired behavior
The newly set folders should be displayed even if an item is selected before setting the new dataSource. 

### Environment

* **Kendo UI version:** 2022.3.1109
* **Browser:** [all ]

**Comment by sspasova** [comment] 2024-01-08 20:37
I am closing this issue because it is no longer reproducible using Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/ukEBOsAV

**Closed by sspasova** 2024-01-08 20:37 UTC
Labels: Bug, SEV: Medium, FP: Unplanned, C: FileManager, Triaged
