### ISSUE TITLE
Window is not centered after refreshing and re-opening it (jQuery 3.1.*)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3383] opened 2017-07-07 10:58 UTC
### Bug report
The Window is centered only when open initially, but is no longer centered after closing, refreshing and reopening it. 

### Reproduction of the problem
Tested with jQuery versions: 1.12.4, 2.2.0, 3.1.0, 3.1.1, 3.2.1. Reproducible only with 3.1.0 and 3.1.1

```html
<div class="container">
    <input type="button" value="open window" onclick="OpenDetailWindow()" />
    @(Html.Kendo().Window()
        .Name("window")
        .Width(1300)
        .Height(700)
        .Visible(false)
        .Modal(true)
    )
</div>

<script>    
    function OpenDetailWindow(defaultTab) {
        $("#window").html("");
        $("#window").data("kendoWindow").refresh({
            type: "GET",
            url: "/Home/MyAction1",
            cache: false
        });

        $("#window").data("kendoWindow").center().open();
    }
</script>
```

### Expected/desired behavior
If the center() method is called prior to opening the window, as in the example above, it should be centered. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 3.1.*
* **Browser:** [all  ]

**Comment by Iankodj** [comment] 2017-07-10 07:22
Duplicate of #2882

**Closed by Iankodj** 2017-07-10 07:22 UTC
Labels: Bug, C: Window, Kendo2, S: Wrappers (ASP.NET MVC), SEV: Low
