### ISSUE TITLE
When selecting item from keyboard in DropDownList with repeated key, It's not selecting the desired item

### ISSUE THREAD

**Issue by Sajan-Kumar-Devarakonda** [telerik/kendo-ui-core#1760] opened 2016-06-03 14:45 UTC

**Comment by KirilNN** [comment] 2016-06-03 15:07
Hi @Sajan-Kumar-Devarakonda,

I am not able to reproduce the issue in neither of our [online demos](http://demos.telerik.com/kendo-ui/dropdownlist/virtualization). Can you please provide steps to reproduce the issue and/or a [Kendo UI Dojo](http://dojo.telerik.com) example?

**Comment by Sajan-Kumar-Devarakonda** [comment] 2016-06-03 19:02
Please find the file, , Steps were given in the file to reproduce the issue.
[Issue Sample.zip](https://github.com/telerik/kendo-ui-core/files/298222/Issue.Sample.zip)

**Comment by Sajan-Kumar-Devarakonda** [comment] 2016-06-04 10:10
Hi @KirilNN .. did you check the file..?

**Comment by underlog** [comment] 2016-06-04 15:45
Took the file and made a Dojo out of it - http://dojo.telerik.com/IxABu . Seems interesting, at least worthy the documentation in case by design. @ggkrustev can say more.

**Comment by ggkrustev** [comment] 2016-07-21 11:34
Hi @Sajan-Kumar-Devarakonda,
We believe that the dropdownlist "search loop" functionality works as expected. It will:
- select "54" item when '5' and '4' are pressed with 500ms or less gap
- Once the "54" item is selected, any additional key press will append the value to "54" (any press is below the default 500ms delay)
- if use keeps pressing '5' key, then the widget will loop the items that starts with "5"
The built-in HTML select element behaves the same way. Here is a screencast of our tests:

http://screencast.com/t/XLtGol5Cpgc

Could you let me know if I am missing something?

**Comment by underlog** [comment] 2016-07-22 09:51
I think that we are ok since we match the native HTML select element. The issue documents the case quite well, IMHO. Closing — @Sajan-Kumar-Devarakonda can chime in with additional feedback.

**Closed by underlog** 2016-07-22 09:51 UTC

**Comment by Sajan-Kumar-Devarakonda** [comment] 2016-07-23 18:23
As @ggkrustev said, If we keep pressing the key 5 it behaving as native html element, but what if press 5 repeatedly below 500ms, it doesn't select the '55' in dropdown , it creates a problem in our automation testing.
