### ISSUE TITLE
Infinite loop when using data-bind "source" and template that contains dropdownlist widget with "value" binding

### ISSUE THREAD

**Issue by codercube** [telerik/kendo-ui-core#778] opened 2015-05-05 12:30 UTC
Found a bug while updating kendo-ui from 2014q3 to 2015q1.
Consider the following code, browser hangs because of an infinite loop while rendering template. Bug appears only when DropDownList widget has data bind set to some value.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Untitled</title>

  <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.1.429/styles/kendo.common.min.css">
  <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.1.429/styles/kendo.rtl.min.css">
  <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.1.429/styles/kendo.default.min.css">
  <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.1.429/styles/kendo.dataviz.default.min.css">
  <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.1.429/styles/kendo.mobile.all.min.css">

  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  <script src="http://cdn.kendostatic.com/2015.1.429/js/kendo.all.min.js"></script></head>
 
<body>
  
  <div id="main"
       data-bind="source: items"
       data-template="item-tpl"></div>
  
  
  <script type="text/x-kendo-template" id="item-tpl">
  	<select 
          data-role="dropdownlist"
          data-text-field="Text"
          data-value-field="Value"
          data-bind="source: values, value: currentValue"></select>
  </script>

  <script>
  	var vm = kendo.observable({
      items: [
        {
          values: [{Text: "ItemA", Value: "AAA"}, {Text: "ItemB", Value: "BBB"}], 
          currentValue: "AAA"
        },
        {
          values: [{Text: "ItemA", Value: "AAA"}, {Text: "ItemB", Value: "BBB"}],
          currentValue: "BBB"
        }
      ]
    });
    
   kendo.bind($("#main"), vm);
  </script>
  
</body>
</html>
```

**Comment by tapopov** [comment] 2015-05-05 12:45
Duplicate of #771

**Closed by tapopov** 2015-05-05 12:45 UTC
