### ISSUE TITLE
The selected tab in the TabStrip now has underline

### ISSUE THREAD

**Issue by moshemal** [telerik/kendo-ui-core#987] opened 2015-07-27 08:46 UTC
### Current version:
![image](https://cloud.githubusercontent.com/assets/2989198/8901835/be27fb0e-3454-11e5-9f3a-f735b5871161.png)

### Few versions before (as it should be):
![image](https://cloud.githubusercontent.com/assets/2989198/8901811/8857bfbe-3454-11e5-8d5e-4eaa97823ae2.png)

**Comment by naskog** [comment] 2015-07-27 08:58
Duplicate of #895

**Closed by naskog** 2015-07-27 08:58 UTC
