### ISSUE TITLE
Ripple util breaks WebPack bundle with Angular 8

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5171] opened 2019-07-15 12:39 UTC
### Bug report

When Kendo UI is integrated within an Angular 8 App, WebPack incorrectly bundles ripple.js util, thus leading to an error when the script is loaded.

https://github.com/telerik/kendo/blob/master/src/util/ripple.js#L9

### Current behavior

A "cannot read property 'kendo' of undefined" error is being thrown after bundling.

### Expected/desired behavior

No error should be thrown when bundling the Kendo script.

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by chubbardsr1** [comment] 2019-07-25 22:31
I see that 2019.2.724 was released 2 days ago.  Do you have an ETA on when the ripple issue will be fixed.  I'm currently having this issue when I updated my Kendo to the latest.  I am on Angular 8.1.2

In order to be able to still work and not get the error, I had to revert to Kendo release from back in the Angular 5.* days.

**Comment by joneff** [comment] 2019-07-26 10:56
The issue is now fixed and under testing from our QA team. The fix will be made available with next week's internal build

**Closed** 2019-07-30 09:09 UTC
Labels: Bug, C: RippleContainer, FP: In Development, Kendo2, Next LIB, SEV: Medium

**Comment by JainamShah1911** [comment] 2019-07-31 13:55
When can I expect an update to solve this issue, stuck after upgrading angular and no workaround available

**Comment by Juveniel** [comment] 2019-07-31 14:50
@JainamShah1911 the issue is fixed. The change will be included in the next Internal Build that is scheduled to be released tomorrow.

As for a temporary workaround, you could open the `node_modules/@progress/kendo-ui/js/util/ripple.js` file and change the following line:
```js
this.kendo.util = this.kendo.util || {};
```

to: 
```js
window.kendo.util = window.kendo.util || {};
```
