### ISSUE TITLE
Preselected items in Multiselect are cleared upon filtering

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1473] opened 2016-03-01 13:18 UTC
There are two preselected items in a Multiselect with minLength: 3, autoBind: false, and serverFiltering: true. When a new search is made, the preselected options disappear.

Steps to reproduce:

1) Open http://dojo.telerik.com/oJOTE/16
2) Type "ani" in the input
3) The preselected items "Chang" and "Uncle Bob's..." disappear

**Comment by Progman2002** [comment] 2016-03-24 23:03
We have encountered the same problem. The problem is that the initial values are not added to the datasource. When the first search result come back the current list of entries will be cleared and readded, based on a calculated index list of the datasource. However, since the old initial values weren't part of the datasource, they get deleted since they aren't in the received search result.

You can use the following workaround until this bug has been fixed:
1. Remove the value initialization.
2. Add the following javascript function to your code:
```javascript
function InitDataSourceOfMultiSelect(multiselectId, initialValues) {
    var multiSelectWidget = $("#" + multiselectId).data("kendoMultiSelect");
    for (var i = 0; i < initialValues.length; i++) {
        multiSelectWidget.dataSource.add(initialValues[i]);
    }
    multiSelectWidget.value(initialValues);
    multiSelectWidget.trigger("change");
}
```
3. Initialize your widged with the following call (in this case using C# in MVC):
```cshtml
InitDataSourceOfMultiSelect("YourIdOfTheMultiSelect", @Html.Raw(Json.Encode(Model.SomeListProperty)));
```

**Comment by ggkrustev** [comment] 2016-06-21 07:54
Seems to be fixed in the latest service pack - 2016 Q2 SP1 (2016.2.607)

**Comment by Dimitar-Goshev** [comment] 2016-06-30 08:05
The issue is still reproducible with the latest version - 2016 Q2 SP1 (2016.2.607)
The initial Dojo sample was defined with autoBind: true, which caused the issue not to reproduce.
The sample is now updated and the steps for reproduction work as expected.

**Comment by ggkrustev** [comment] 2016-07-06 08:42
Fixed in the master. The fix will be included in the 2016.Q3 release

**Closed by ggkrustev** 2016-07-06 08:42 UTC
Labels: Bug, C: MultiSelect, SEV: Medium

**Comment by brunohunziker** [comment] 2016-09-20 05:57
I have the problem still with 2016.Q3 (2016.3.914.440). Workaround helps.

**Comment by ggkrustev** [comment] 2016-09-20 17:39
The repro demo, posted in the description, seems to works with 2016.3.914. Would it be possible to provide a repro demo?
