### ISSUE TITLE
Incorrect multi filter search textbox border in jquery grid

### ISSUE THREAD

**Issue by jvalkeejarvi** [telerik/kendo-ui-core#6310] opened 2021-03-04 13:10 UTC
### Bug report
![image](https://user-images.githubusercontent.com/3441271/109968553-88e0c700-7cfb-11eb-8a5f-95cb6a1fa5ba.png)

### Reproduction of the problem
https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.filterable.search

**Comment by dmanova** [comment] 2021-03-15 10:32
Duplicate of #https://github.com/telerik/kendo-themes/issues/2119

**Closed by dmanova** 2021-03-15 10:32 UTC
