### ISSUE TITLE
DatePicker in Scheduler does not show dates when culture is enabled

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6050] opened 2020-10-01 07:31 UTC
### Bug report

When culture is enabled and a recurring event is edited, the end DatePicker for the recurrence does not show dates with some cultures. 

This is a regression introduced with the R2 2020.2.617 version of Kendo.

### Reproduction of the problem
1. Open the [Scheduler Localization Demo
](https://demos.telerik.com/kendo-ui/scheduler/localization)
2. Select language "bg-BG"
3. Edit the entire series of a recurring event, for example, "Dance Practice"
4. Try to set a different end date of the recurring

### Current behavior
Date Picker does not show any dates with some languages (bg-BG, nl-Nl).  The issue is reproducible in all browsers with Bulgarian language. It is reproducible only in Firefox with "nl-Nl" culture ([Dojo example](https://dojo.telerik.com/OfIVozUY/2))

When the DatePicker is opened and the date in the header is clicked there is an error in the console: Uncaught TypeError: i is undefined 

### Expected/desired behavior
DatePicker should display dates no matter of the configured language. 

### Environment
* **Kendo UI version:** 2020.2.617
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2020-10-08 15:38
The issue is fixed. We will close it once merged for R3 2020 SP1

**Closed** 2020-10-09 06:55 UTC
Labels: Bug, C: Scheduler, FP: Completed, Kendo2, Priority 5, SEV: High
