### ISSUE TITLE
Custom filterable operators defined on grid level will be ignored for group columns

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#5364] opened 2019-10-25 14:20 UTC
### Bug report

Custom filterable operators defined on grid level will be ignored for group columns (nested multiple columns). It happens when the culture on the server-side is other than "en-US". 

### Reproduction of the problem
@(Html.Kendo().Grid<Product>()
          .Name("grid")
          .DataSource(dataSource => dataSource
              .Ajax()
              .Read(read => read.Action("Read", "Home"))
           )
          .ToolBar(t => t.Create())
          .Columns(columns =>
          {
              columns.Bound(product => product.ProductID);
              columns.Group(gr => gr.Title("group column").Columns(cols =>
                  {
                      cols.Bound(col => col.ProductName);
                      cols.Bound(product => product.UnitsInStock);
              }));
              columns.Bound(product => product.Discontinued);
              columns.Command(command => command.Edit());
          })
           .Filterable(ftb => ftb.Mode(GridFilterMode.Row)
                .Extra(true)
                .Operators(operators => operators
                        .ForString(str => str.Clear()
                            .Contains("custom contains")
                            )
                        .ForNumber(num => num.Clear()
                            .IsEqualTo("custom isEqualTo")
                            )

                    )
        )
          .Pageable()
          .Sortable()
          .Filterable()
          .Editable()
)

In the controller the following code should be set: 
public override void OnActionExecuting(ActionExecutingContext context)
        {
            
            CultureInfo.DefaultThreadCurrentCulture = CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("de-DE");
            base.OnActionExecuting(context);
        }

### Current behavior
Filter operator for the ProductID column uses the custom filter for number type. UnitsInStock shows all operators localized for the server-side culture. 

### Expected/desired behavior
Both fields should show only the custom filter operator. 

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment] 2020-11-05 15:45
I was not able to reproduce this, moving it for testing

**Comment by dmanova** [comment] 2020-11-10 17:20
Reproducible both in ASP.NET Core and ASP.NET MVC.

**Closed** 2020-11-13 15:42 UTC
Labels: Bug, C: Grid, Kendo1, Next LIB, Priority 2, S: Wrappers (ASP.NET Core), S: Wrappers (ASP.NET MVC), SEV: Low
