### ISSUE TITLE
Problem with Drag & Drop demo in Firefox

### ISSUE THREAD

**Issue by JoseGoncalves** [telerik/kendo-ui-core#564] opened 2015-02-19 14:06 UTC
In Firefox 35 the Drag & Drop demo available at http://demos.telerik.com/kendo-ui/dragdrop/index does not show the draggable shape when dragging it (in Chrome works fine).

**Comment by KirilNN** [comment] 2015-02-19 15:13
Hi @JoseGoncalves,

The problem is caused by the scoped attribute of the style tag. It will be fixed with the next release, in the mean time removing it seems to be the solution. You can check it out [here](http://dojo.telerik.com/ixudo)

**Closed by KirilNN** 2015-02-19 15:13 UTC
Labels: Bug, C: Draggable
