### ISSUE TITLE
AutoComplete and ComboBox with enabled clearButton do not trigger keyboard on the first tap on mobile devices

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2354] opened 2016-10-21 13:14 UTC
~~### Bug report~~

~~If the "clearButton" option is set to true, the widget does not open Browser's keyboard popup on the first click/tap on mobile devices (observed in Safari and Chrome). Instead it displays the "clearButton" only. On the second click the input box gains focus and Browser's keyboard popup is opened.~~
~~### Reproduction of the problem~~

~~http://dojo.telerik.com/aXifi~~
~~### Current behavior~~

~~Keyboard does not show on initial tap~~
~~### Expected/desired behavior~~

~~Keyboard to be shown when tapping the input for the first time~~
~~### Environment~~
~~- **Kendo UI version:** 2016.3.914~~
~~- **jQuery version:** x.y~~
~~- **Browser:** [Chrome, Safari ]~~

### Bug report

If the [**"clearButton"**](http://docs.telerik.com/kendo-ui/api/javascript/ui/combobox#configuration-clearButton) option is set to **true** (true by default), the widget does not open Browser's keyboard popup on the first click/tap on iOS devices in Safari/Chrome, if there is an item already selected. Instead it displays the "clearButton" only. On the second tap the input box gains focus and Browser's keyboard popup is opened.

### Reproduction of the problem

1. Go to http://dojo.telerik.com/aXifi/5 on iOS Safari
2. Tap on the AutoComplete/ComboBox - the soft keyboard would appear immediately.
3. Type a and select an item.
4. Move the focus away from the widget to hide the keyboard.
5. Tap on the widget again.

### Current behavior
Keyboard does not show on one tap - the clear button becomes visible.

### Expected/desired behavior
Keyboard is shown when tapping on the input for the first time and the clear button is visible.

### Environment
- **Kendo UI version:** 2018.3.911 t
- **Browser:** [iOS - Chrome, Safari ]

**Comment by zdravkov** [comment] 2017-05-12 10:50
Could not replicate it.

**Comment by Dimitar-Goshev** [comment] 2017-05-16 10:37
With R2 2017, the issue is reproducible on iOS Safari and Chrome, when there is an item already selected in the widget. Steps to reproduce are updated in the issue's description.

**Comment by Dimitar-Goshev** [comment] 2017-06-19 11:05
The issue is reproducible only with LESS themes. When tested with SASS based themes Default v2 and Bootstrap v4, the issue is not reproducible.

**Comment by Dimitar-Goshev** [comment] 2019-10-22 08:52
On iOS 13 the issue is reproducible with both SASS and LESS themes.
Kendo UI 2019.3.917

**Comment by sspasova** [comment] 2023-11-09 07:41
Closing this because the issue is not reproducible with Kendo UI 2023.3.1010. Tested on iPhone and iPad using this Dojo - https://dojo.telerik.com/@Dimitar-Goshev/oJuMaduT

**Closed by sspasova** 2023-11-09 07:41 UTC
Labels: Bug, C: AutoComplete, C: ComboBox, SEV: Medium, jQuery, Appearance, Priority 1, Touch Devices, Triaged
