### ISSUE TITLE
In InLine editing mode, TreeList displays Update and Cancel buttons in all command columns

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3279] opened 2017-06-01 11:11 UTC
### Bug report

If there is more than one command column in TreeList and one of them includes an Edit command, when the TreeList is put in edit mode, all command columns display the "Update" and "Cancel" buttons.

Example: [http://dojo.telerik.com/IqePa](http://dojo.telerik.com/IqePa)

### Expected/desired behavior
 "Update" and "Cancel" buttons should be visible only in the command column that declares an "Edit" command. This is how the Grid works.

### Environment

* **Kendo UI version:** 2017.2.504

Reported in ticket #1111872.

**Comment by Xizario** [comment] 2017-06-01 11:29
Duplicate of https://github.com/telerik/kendo-ui-core/issues/2170

**Closed by Xizario** 2017-06-01 11:29 UTC
Labels: Bug, C: TreeList, SEV: Low
