### ISSUE TITLE
editable causes unavoidable error

### ISSUE THREAD

**Issue by zwasser2** [telerik/kendo-ui-core#4691] opened 2018-11-27 20:10 UTC
Clicking on a cell that is editable will throw an error. An example can be shown on the editable documentation at https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/editable

**Comment by zwasser2** [comment] 2018-11-27 22:06
Looks like kendogrid.all.js:58484" if (editContainer && editContainer[0] && $.contains(editContainer[0], e.target) || editContainer[0] === e.target) {" 

doesn't use a check before the || statement. To fix this bug, change this to something like "if (editContainer && editContainer[0] && $.contains(editContainer[0], e.target) || (editContainer && editContainer[0] === e.target)) {"

**Comment by MilenaCh** [comment] 2018-11-29 09:36
Could you provide exact steps for reproduce? I tested the example in the documentation article, which you pointed and it works properly on my side:
https://dojo.telerik.com/@milena/agocExec

**Comment by zwasser2** [comment] 2018-11-29 16:11
I tested it further and it seems it throws an error in Mac but not Windows. I tested in chrome/safari on my mac and safari on my iphone which all got the error. My windows computers (both windows 10, chrome/edge) did not get it.

**Comment by zwasser2** [comment] 2018-11-29 16:15
Explicitly, the instructions are:
1. On a mac open up chrome
2. Navigate to https://dojo.telerik.com/@milena/agocExec
3. Click on a cell
4. Check the console, an error should be thrown "Uncaught TypeError: Cannot read property '0' of undefined"

**Comment by matanasov** [comment] 2018-12-03 08:06
I think this is duplicate of [4670](https://github.com/telerik/kendo-ui-core/issues/4670)
The latest LIB should include the fix and you can verify it on your side.

**Closed by matanasov** 2018-12-03 08:06 UTC
