### ISSUE TITLE
Extra Indentation in OptionLabel

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6939] opened 2022-07-27 13:49 UTC
### Bug report

The Kendo UI DropDownList's OptionLabel has some padding before the OptionLabel which does not match corresponding items in list.  

### Reproduction of the problem
Please visit [this Progress Kendo UI Dojo ](https://dojo.telerik.com/@PMcDonou/ehINewor) and open the Kendo UI DropDownList.

### Current behavior
![image](https://user-images.githubusercontent.com/19593058/181263002-0db6cae1-999c-4ce6-9579-d9bf797472d3.png)

### Expected/desired behavior
The OptionLabel should be matching the items below it or follow any additional design guidelines provided. 

### Environment

* **Kendo UI version:** 2022.1.301
* **jQuery version:** Supported Versions
* **Browser:** all

**Comment by jacobkepford** [comment] 2022-08-06 18:02
Just submitted a pull request to resolve this indendation: https://github.com/telerik/kendo-ui-core/pull/6966

**Comment by sspasova** [comment] 2024-02-07 13:56
I am closing this issue because it is no longer reproducible using Kendo UI 2024.1.130. I am linking a working Dojo example -> https://dojo.telerik.com/@sspasova/AVEqUjoc

**Closed by sspasova** 2024-02-07 13:56 UTC
Labels: Bug, C: DropDownList, SEV: Low, jQuery, Appearance, Triaged
