### ISSUE TITLE
Links keep their initial order, when column in Spreadsheet it sorted

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4261] opened 2018-05-25 10:22 UTC
### Bug report

Links keep their initial order when a column in Spreadsheet it sorted

### Reproduction of the problem

repro dojo:
[http://dojo.telerik.com/exavUZEy](http://dojo.telerik.com/exavUZEy)

Sort the Priority column A-Z

### Current behavior
Links keep their initial order when a column in Spreadsheet is sorted

### Expected/desired behavior
Linked-value, should be correctly sorted along with its text

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by mparvanov** [comment] 2018-06-06 12:27
The issue is still reproducible:

http://take.ms/IWWwR

**Comment by mparvanov** [comment] 2018-06-08 11:52
The issue appears to be fixed with the latest source, closing it as resolved.

**Closed by mparvanov** 2018-06-08 11:52 UTC
Labels: Bug, C: Spreadsheet, Kendo2
