### ISSUE TITLE
Less Themebuilder is throwing "Unrecognised input" error on downloading a theme

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#5774] opened 2020-05-15 13:28 UTC
### Bug report

Currently Less Themebuilder is throwing the following error on trying to download a customized theme:
b.exports {message: "Unrecognised input", stack: undefined, type: "Parse", filename: "input", index: 91030, …}

### Reproduction of the problem
https://demos.telerik.com/kendo-ui/themebuilder/
Customize and download a theme
### Environment

* **Kendo UI version:** 2020.2.513

**Comment by Dimitar-Goshev** [comment] 2020-05-20 14:58
The issue is now fixed and LESS themebuilder works without this error:
https://demos.telerik.com/kendo-ui/themebuilder/

**Closed by Dimitar-Goshev** 2020-05-20 14:58 UTC
Labels: Bug, C: ThemeBuilder LESS, FP: In Development, Kendo1, Kendo2, Priority 5, SEV: Critical
