### ISSUE TITLE
Immutable content is removed when a line is deleted in the Editor

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7070] opened 2022-09-30 09:45 UTC
### Bug report

Immutable content is incorrectly removed when you delete line in the Editor textarea.

### Reproduction of the problem
1. Open this demo - https://demos.telerik.com/kendo-ui/editor/immutable-elements
2. Place your mouse cursor after Dear Your Name,
3. Hit Enter
4. Hit Backspace
### Current behavior

The immutable "Dear" part of the text is removed instead of the empty line

### Expected/desired behavior
The immutable content should not be removed

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by eyupyusein** [comment] 2023-03-28 11:12
Reported in ticket: 1603196

**Comment by GraemeSMiller** [comment] 2023-06-06 22:21
Is there any update on when this might get scheduled? It seems critical functionality for immutable items. Also, your documentation online makes no mention that immutable doesn't work for this scenario which seems very misleading to other developers that aren't aware of this issue.

Demo literally says, "The immutable elements feature of the Kendo UI Editor component enables you to predefine elements in the content area that cannot be edited by the end user." I would say being removable qualifies as being editable.

**Comment by sspasova** [comment] 2023-12-21 09:01
I am closing this issue because the described scenario is working after the applied fix.
 
Note that immutable elements cannot be edited as in having their formatting or text changed, however, they can be deleted.
 
Immutable elements can be removed in the following cases: 
Case 1: Immutable element is (partially or fully) selected and the user is deleting(using backspace or delete key).
Case 2: Immutable element is (partially or fully) selected and the user is typing.
Case 3: Selection starts before the immutable and ends after it and the user is deleting by delete key

We will update our documentation accordingly so there are no more misunderstandings. 
If you would like to request a different behavior for the immutable elements you can always log a feature request in our feedback portal - https://feedback.telerik.com/kendo-jquery-ui

**Closed** 2023-12-21 09:00 UTC
Labels: Bug, SEV: Medium, C: Editor, jQuery, Priority 4, FP: Unplanned, Triaged

**Comment by trailmax** [comment] 2023-12-21 12:58
@sspasova but I can totally edit those elements! they are clearly mutable if I can delete bits of these. What a misleading and useless component!

**Comment by gdenchevprog** [comment] 2023-12-21 14:45
Hey, @GraemeSMiller and @trailmax 

I'm jumping in to provide a bit more clarification about the details shared by my colleague.
The comment itself was a response to [the following statement](https://github.com/telerik/kendo-ui-core/issues/7070#issuecomment-1579533028) which is not "fully" related to this issue in particular. The _current_ intended behavior of an immutable is that such element can be removed.

The original problem that was reported, was that an immutable is incorrectly being removed when a new line is deleted. This in itself is indeed incorrect and it is what the patch aims to fix.

The immutable was first implemented around 7-8 years ago and client requirements at the time were that these should be elements that cannot be changed in terms of appearance or content, however they can be removed.

One of the initial purposes is similar to what is shown in the immutable elements demo. The immutables are sort of like an "email template" and the end user can modify the rest of the content, such as their name without being able to touch the template.

With the above said, I'd like to clarify that the statement in no way means that "there will never be a feature that prevents the deleting of immutables". This item is simply not made to address the default behavior of the feature.

That is why my colleague also suggested that a feature request/enhancement item is logged in our [feedback portal](https://feedback.telerik.com/kendo-jquery-ui). 

What you're saying is a valid scenario and there could be an option that makes the immutables non-deletable as well.

We'll also look into updating our documentation for the moment as I do agree that it isn't very clear what "cannot be edited by the user means". Some will take this information as "the user cannot change the text content or styles", others will take it as "the user can neither change the text, nor delete it".
