### ISSUE TITLE
Element is not moved to next page in Firefox

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1721] opened 2016-05-27 06:37 UTC
The blue rectangle will be wrapped in Chrome, but not in Firefox

http://dojo.telerik.com/@tsvetomir/UZuPO

**Comment by mishoo** [comment] 2016-05-27 07:03
I can't tell from the example what is the expected output, but one thing I know is that multi-column text, or other vertically side-by-side elements, will not be properly split.  For instance if you have two big columns of text, when the first one is split the second one will go to the next page entirely.  The issue is that we take this:

```html
<div class="col1">...big text</div>
<div class="col2">...big text</div>
```

and produce something like this:

```html
<page1>
  <div class="col1">text</div>
</page1>

<page2>
  <div class="col1">continued first col</div>
</page2>

<page3>
  <div class="col1">end of first col</div>
  <div class="col2">...</div>
</page3>
```

So whenever a page break happens, all the elements following it will go to the next page (even if they are floating elements and could start on the current page).  This is noted in the [documentation](http://docs.telerik.com/kendo-ui/framework/drawing/drawing-dom#configuration-Page):

> If the algorithm decides to move a node to the next page, all the DOM nodes which follow it, will be moved as well, even if there might be potentially room for some of them on the current page. This is demonstrated with floating elements in the example below.

though perhaps we should better emphasize it as a known issue.

**Comment by nenchef** [comment] 2020-10-19 08:50
Closing due to Mihai's description and known issue/limitation statement.

**Closed** 2023-11-09 06:39 UTC
Labels: Bug, SEV: Low, F: PDF Export, jQuery, Triaged
