### ISSUE TITLE
Cannot change values of an AngularJS TimePicker with DateInput bound to a variable in the controller

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4051] opened 2018-03-06 12:13 UTC
### Bug report

Cannot change values of an AngularJS TimePicker with DateInput bound to a variable in the controller.

Cannot replicate the same behavior with solo DateInput and DateTimePicker:
https://dojo.telerik.com/uzOjAVOb
https://dojo.telerik.com/IboqIsUP

### Reproduction of the problem

https://dojo.telerik.com/avAHIFIb/8

### Expected/desired behavior

The user can change the values of the TimePicker.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all]

**Comment by ag-petrov** [comment] 2018-03-23 15:01
The reason for the described behavior is that by default the **DateInput** which is used in the picker has a **min** and **max** values set. They reflect 00:00 AM to 12:00 PM of the current day. If however **min** and **max** custom values are used things should work as epxected. Currently there was an issue where the aforementioned and they were not passed correctly to the DateInput but it is already referenced. After the fix is tested and included in the next release one should be able to set value for the picker and the below shown scenario should work.

```
<div id="example" ng-app="KendoDemos">
    <div ng-controller="MyCtrl">
        <input kendo-time-picker
               k-date-input="true"
               k-min="obj1"
               k-max="obj2"
               k-ng-model="obj"/>
    </div>
</div>

<script>
    angular.module("KendoDemos", ["kendo.directives"])
        .controller("MyCtrl", function ($scope) {
            $scope.obj = new Date(2014, 1, 1, 10, 1, 1);
            $scope.obj1 = new Date(2014, 1, 1, 3, 1, 1);
            $scope.obj2 = new Date(2014, 1, 1, 11, 1, 1);
        })
</script>

```

**Comment by matanasov** [comment] 2018-03-26 07:31
@ag-petrov 
The issue is still not resolved for some cases. For example:
1. Run the initial dojo and update it with the code provided in your comment.
2. Focus the input and update the Time part using the keyboard arrows so that the time exceeds the min/max setting (e.g. enter 2 AM)
3. Blur the input - the time gets corrected to min/max value set (e.g. 3 AM) - this is expected
4. Focus the input and update the Time part using the keyboard arrows so that the time is in the range (e.g. 6 AM).
5. Blur the input - the time gets corrected to min/max value set (e.g. 11 AM) - this is NOT correct.

**Comment by ag-petrov** [comment] 2018-03-26 12:05
We have referenced the last reported things. Bear in mind that using dates which are prior or after the current date [min](https://docs.telerik.com/kendo-ui/api/javascript/ui/timepicker/methods/min) and [max](https://docs.telerik.com/kendo-ui/api/javascript/ui/timepicker/methods/max) values should be set.

**Comment by matanasov** [comment] 2018-03-26 13:50
@ag-petrov 
I am closing this, but please ensure our documentation team adds this new requirement in the docs.

**Closed by matanasov** 2018-03-26 13:50 UTC
Labels: Bug, C: DateInput, C: TimePicker, F: AngularJS, Kendo1, Priority 2, SEV: Medium
