### ISSUE TITLE
PivotDataSource options are missing from the MVC wrappers

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#3510] opened 2017-08-17 12:02 UTC
### Bug report

Reported in Ticket ID: 1125563

The `Sort` option of the PivotDataSource is not exposed in the MVC wrappers, so it cannot be configured as in:

http://docs.telerik.com/kendo-ui/controls/data-management/pivotgrid/how-to/sorting/sort-dimension

This applies to other options as well.

For now, it can be configured on the client-side only.

### Environment

* **Kendo UI version:** 2017.2.621

**Comment by dmanova** [comment] 2020-10-14 10:22
Duplicate of #4145

**Closed by dmanova** 2020-10-14 10:22 UTC
Labels: C: PivotGrid, Enhancement, Kendo1, S: Wrappers (ASP.NET Core), S: Wrappers (ASP.NET MVC)
