### ISSUE TITLE
Treeview with CheckChildren enabled and templates does not change properly checkbox indeterminate state in IE 

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4134] opened 2018-04-04 14:53 UTC
### Bug report
Treeview with CheckChildren enabled and templates does not change properly checkbox indeterminate state in IE 11

### Reproduction of the problem
Set a template for the Checkboxes in TreeView.
Have all nodes checked, then uncheck some child node and click on the intermediate checkbox on its parent.

repro video:
[https://monosnap.com/file/kHxY2pflpidqkvmhRxtP4FTguSS1NT](https://monosnap.com/file/kHxY2pflpidqkvmhRxtP4FTguSS1NT)

Attached you can find an example of repro.

### Current behavior
The click on the intermediate checkbox does not change its state to **checked** and does not check all child nodes.

### Expected/desired behavior
The click on the intermediate checkbox should change its state to checked and should have all child nodes checked as well.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [IE 11]

[Index.zip](https://github.com/telerik/kendo-ui-core/files/1876288/Index.zip)

**Comment by jivanova** [comment] 2018-08-16 12:56
Fixed in R2 2018.

**Comment by mparvanov** [comment] 2018-08-20 15:08
The issue is reproducible in Edge with the latest internal scripts:

**Closed** 2018-08-21 06:30 UTC
Labels: Bug, C: TreeView, F: Templates, Kendo2, Priority 2
