### ISSUE TITLE
Kendo Spreadsheet - Cell Formatting incorrect for Value With Decimal

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#4199] opened 2018-05-01 19:37 UTC
### Bug report

Cell formatting is not respected for certain values in cells.

### Reproduction of the problem

1. Go to [this Kendo UI Dojo](http://dojo.telerik.com/orolUGUC)
2.  The cell values are as follows:

>                  
                  {
                    cells: [
                      {
                        value: .034511111111111, format: "##.###"
                      }
                    ]
                  },
                  {
                    cells: [
                      {
                        value: .0914233242323232324324242, format: "##.###"
                      }
                    ]
                  },
                  {
                    cells: [
                      {
                        value: .0914233242323232324324242, format: "00.000"
                      }
                    ]
                  }

> 

### Current behavior

Format for a cell with a value of **.0914233242323232324324242** with a format of **##.###** will display as **.914**.

### Expected/desired behavior
Using the example in Current behavior, it should appear as **.091**.

### Environment

* **Kendo UI version:** From 2017.3.1018 - 2018.1.221
* **jQuery version:** 1.12.X
* **Browser:** all

**Comment by mishoo** [comment] 2018-05-08 07:16
Duplicate of #4005 (fixed).

**Closed by mishoo** 2018-05-08 07:16 UTC
