### ISSUE TITLE
Spreadsheet BUG deletion of multiple not adjusted cells in a DataSource bound

### ISSUE THREAD

**Issue by sqlnew** [telerik/kendo-ui-core#4804] opened 2019-01-30 05:54 UTC
Bug report
Currently, DataSource bound Spreadsheet throws "Unsupported for multiple ranges" error when attempting to delete the content from multiple not adjusted cells.

The error is thrown by the values() method:

values: function (values) {
    if (this._ref instanceof UnionRef) {
        throw new Error('Unsupported for multiple ranges.');
    }
    if (this._ref === kendo.spreadsheet.NULLREF) {
....
Reproduction of the problem
Go to the DataSource Binding demo;
Select a few cells using the Ctrl + click;
Press Delete button on the keyboard;
"Unsupported for multiple ranges" error will be thrown from the values() method;

IIII, Unfortunately, this Bug has not been repaired in the v2019.1.115 version. It's disappointing.
When can we solve this problem? I hope telerik will pay attention to this problem.???

**Comment by Dimitar-Goshev** [comment] 2019-01-30 08:17
@sqlnew This issue is duplicate of https://github.com/telerik/kendo-ui-core/issues/3903 . As @veselints replied there, this enhancement is not currently scheduled for implementation.

**Closed by Dimitar-Goshev** 2019-01-30 08:17 UTC
