### ISSUE TITLE
Spreadsheet to Excel to Spreadsheet not copy/pasting correctly

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#7627] opened 2023-12-05 20:46 UTC
### Bug report

After pasting values from the Kendo UI Spreadsheet to Excel, making a change in Excel, and pasting the value back to a Kendo UI Spreadsheet, it pastes old information.

### Reproduction of the problem
1. [Open the Kendo UI Spreadsheet Overview](https://demos.telerik.com/kendo-ui/spreadsheet/index)
2. Copy Data **C7:D8** from Kendo Spreadsheet
3. Paste data to MS Excel (used: Microsoft 365 MSO version 2309)
4. Edit values in MS Excel. 
5. Copy from MS Excel
6. Paste new values to a Kendo UI Spreadsheet.

### Expected/desired behavior
The new values are not pasted back to the Kendo UI Spreadsheet.  

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** All Supported Versions
* **Browser:** all

**Comment by Dimitar-Goshev** [comment] 2023-12-15 13:32
Closing this issue as duplicate of https://github.com/telerik/kendo-ui-core/issues/7340 . I transferred the described scenario to it.

**Closed by Dimitar-Goshev** 2023-12-15 13:32 UTC
Labels: FP: Unplanned
