### ISSUE TITLE
JavaScript exceptions when using the PDFViewer with the latest PDF.js version

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7468] opened 2023-08-03 12:43 UTC
### Bug report

Using the PDFViewer with the latest version of PDF.js (3.9.179) throws js exceptions. Version 3.4.120 is the last one, with which no js exception is thrown. 

### Reproduction of the problem
Dojo example: https://dojo.telerik.com/IHedIhur/3
1. Open the devtools console and run the example. 

### Current behavior
The file is loaded, however, js exceptions are thrown:

**The `--scale-factor` CSS-variable must be set, to the same value as `viewport.scale`, either on the `container`-element itself or higher up in the DOM. text_layer.js:480:14**

### Expected/desired behavior
No js exceptions when using PDF.js versions newer than v3.4.120.

### Environment

* **Kendo UI version:** 2023.2.718
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by alestoya** [comment] 2023-08-17 14:45
Reported in 1619995

**Comment by nelito987** [comment] 2023-11-07 09:26
Reported in ticket ID: 1630023

**Comment by zstoyanova9** [comment] 2023-12-19 13:46
Reported in: 1634261

**Comment by sspasova** [comment] 2024-01-10 12:22
I am closing this issue because it is no longer reproducible using jszip 3.10.1 and Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/UqIlAtuz

**Comment by IvanDanchev** [comment] 2024-03-14 13:52
Reopening, since the issue is still reproducible with PDF js versions newer than 3.4.120.

**Comment by Dimitar-Goshev** [comment] 2024-03-14 14:29
The issue is not reproducible all the time. On my side I reproduce it with https://dojo.telerik.com/@sspasova/UqIlAtuz on Chrome 122 when running the Dojo. But the issue is not reproducible on my side in Firefox or if I open the Fullscreen version of the same Dojo in Chrome https://runner.telerik.io/fullscreen/@sspasova/UqIlAtuz

**Comment by sspasova** [comment] 2024-10-31 08:34
The issue is fixed with https://github.com/telerik/kendo/issues/20260

**Closed by sspasova** 2024-10-31 08:34 UTC
Labels: Bug, SEV: Medium, jQuery, FP: Unplanned, C: PDFViewer
