### ISSUE TITLE
MultiSelect clear all items button is not visible in Bootstrap 3 theme, when the input is hovered

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4601] opened 2018-10-22 07:59 UTC
## Bug report
MultiSelect clear all items button is not visible in Bootstrap 3 theme, when the input is hovered (while icon on white background).

Related to https://github.com/telerik/kendo/issues/8725
related to https://github.com/telerik/kendo/issues/9051

## Reproduction of the problem
Could be observed on the [MultiSelect Index demo](https://demos.telerik.com/kendo-ui/multiselect/index)

## Environment
Kendo UI version: 2018.3.1017
Browser: [all]

**Comment by veselints** [comment] 2018-10-22 12:28
The following CSS rule will apply color to the icon:

```css
.k-multiselect>.k-multiselect-wrap>.k-i-close {
  color: #357ebd;
}
```

**Comment by Dimitar-Goshev** [comment] 2018-10-22 12:30
Closing this as a duplicate of https://github.com/telerik/kendo-ui-core/issues/4602
Duplicated due to GitHub outage.

**Closed by Dimitar-Goshev** 2018-10-22 12:30 UTC
Labels: Appearance, Bug, C: MultiColumnComboBox, Kendo2, SEV: Low
