### ISSUE TITLE
Mobile Scheduler don't assume editable settings

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5086] opened 2019-05-31 06:27 UTC
### Bug report
Mobile Scheduler don't assume editable settings
https://dojo.telerik.com/@zdravkov/aTETAKEp

### Current behavior
editable is false yet we can still add and delete events

### Expected/desired behavior
Create button is not visible when editable is true

**Comment by Dimitar-Goshev** [comment] 2019-07-08 14:06
Duplicate of https://github.com/telerik/kendo-ui-core/issues/5089
Fixed in R2 2019 SP1 - [2019.2.619 - DOJO](https://dojo.telerik.com/URUBaBAP)

**Closed by Dimitar-Goshev** 2019-07-08 14:06 UTC
Labels: Bug, C: Scheduler, Kendo2, SEV: High
