### ISSUE TITLE
Filemanager's TreeView duplicates subfolders when selected / deselected

### ISSUE THREAD

**Issue by DunhamGitHub** [telerik/kendo-ui-core#7926] opened 2024-08-05 10:17 UTC
### Bug report

Whilst having (top level) `New Folder 1` -> `New Folder 2`, selecting `New Folder 2` and then `New Folder 1` shows a duplicate child folder (each time).

### Reproduction of the problem

1. Open this Dojo https://dojo.telerik.com/AmOGOdut/2
2. Create a New Folder (no need to name it)
3. Create a New Folder inside above
4. Click on New Folder (sub level)
5. Click on New Folder (top level)
6. Notice 2 New Folders in sub level

### Expected/desired behavior
Selecting items in the Treeview should not duplicate them. (Seems contents are also displayed incorrectly)

### Environment

* **Kendo UI version:** 2024.2.514
* **Browser:** all

https://github.com/user-attachments/assets/05ce58da-f745-43ef-af5a-bddf705fe7fa

**Comment by sspasova** [comment] 2024-08-06 06:41
Hello @DunhamGitHub, 

I am closing this issue because it is a duplicate of #7843.

**Closed by sspasova** 2024-08-06 06:41 UTC
Labels: FP: Unplanned, C: FileManager
