### ISSUE TITLE
TreeView MVC checkboxes are not styled when the wrapper is bound to remote data.

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#2380] opened 2016-10-31 09:45 UTC
### Bug report
TreeView MVC checkboxes are not styled when the wrapper is bound to remote data. The issue is not reproducible when a TreeView is bound to local data.

### Desired behavior
Render the same DOM when a TreeView is bound to remote and to local data, which will allow to style check-boxes in the wrapper.

**Comment by Dimitar-Goshev** [comment] 2017-08-09 15:24
Duplicate of #2379

**Closed by Dimitar-Goshev** 2017-08-09 15:24 UTC
Labels: Bug, C: TreeView, Kendo2, S: Wrappers (ASP.NET MVC), SEV: Low
