### ISSUE TITLE
sourceMappingURL for CDN CSS files not found in Edge

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2460] opened 2016-11-21 13:35 UTC
### Bug report

The edge inspector seems to be looking for the map in `source/web/`

<img src="http://i63.tinypic.com/15cdfyc.png"></img>

The styles get loaded and error only occurs when the developer tools are open. If you clear the errors, they will not show up again. 

As a workaround for the moment:

1. Locate the map manually as shown at the Source Maps section  in the MS Edge documentation [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/f12-devtools-guide/debugger/)

    The map files are located at(e.g.)    `~telerik.kendoui.professional.2016.3.1118.commercial\styles\kendo.bootstrap.min.css.map)`

2.  Remove the last line from the CCS files 
`/*# sourceMappingURL=kendo.bootstrap.min.css.map */`

### Reproduction of the problem

Open any demo in Edge and press F12
[e.g. Grid demo](http://demos.telerik.com/kendo-ui/grid/index)

### Expected/desired behavior

Source Map URLs should point to the correct path

### Environment

* **Kendo UI version:** any
* **jQuery version:** any
* **Browser:** [Edge]

**Comment by tsvetomir** [comment] 2016-11-21 15:16
The problem seems to be caused by invalid paths in the source map files. They currently point to their original locations, e.g. `"sources":["web/kendo.black.css"]` rather than to the deployed location `"sources":["kendo.black.css"]`

@gyoshev should I address this during bundling or is there a better way?

**Comment by gyoshev** [comment] 2016-11-21 16:21
I think that the removal of the old suites' directories is cleaner, but will require more effort and is error-prone. Since we may be leaning towards the SASS themes in the future, the bundling step should be fine.

**Comment by vveesseelliinnaa** [comment] 2017-01-20 08:52
Reported in ticket #1084978, raising priority.

**Comment by Alex-Bubblemaster** [comment] 2017-01-27 11:57
Also reported in ticket ID 1086284

**Comment by Alex-Bubblemaster** [comment] 2017-02-17 14:51
Issue is still present in Edge. 
Reported in the [forum thread](http://www.telerik.com/forums/missing-icons-when-i-use-the-kendo-cdn) with ticket ID 1090386
Reopening.

**Comment by tsvetomir** [comment] 2017-02-17 14:56
Bummer. The source maps themselves still contain a reference to an invalid path:
`"file":"web/kendo.common.min.css","sourceRoot":"/source/","sourcesContent":[]`

**Comment by tsvetomir** [comment] 2017-02-21 16:32
The fix will be included in the next internal build. It _will not be_ included in the SP1 release scheduled for tomorrow.

**Closed** 2017-02-24 09:42 UTC
Labels: Bug, SEV: Medium
