### ISSUE TITLE
filter with operator as a function evaluates value as object instead of function

### ISSUE THREAD

**Issue by CuddleBunny** [telerik/kendo-ui-core#126] opened 2014-06-18 15:39 UTC
I created a custom filter like so:

    var colorNameFilter = {
        field: 'colors',
        operator: function (items, filterValue) {
            for (var i = 0; i < items.length; i++) {
                if (items[i].color.indexOf(filterValue) != -1)
                    return true;
            }
            return false;
        },
        value: $('#color-name').val()
    }

I type 'Blue' into the color-name input which adds this filter in a change event and when the filter evaluates I get an error the object Blue is not defined. A hacky remedy for this is the change value to:

    value: "'" + $('#color-name').val() + "'"

By adding a pair of quotes the value now evaluates properly to a string.

**Comment by tapopov** [comment] 2015-04-07 15:52
Duplicate of #548.

**Closed by tapopov** 2015-04-07 15:52 UTC
Labels: Bug, C: DataSource, SEV: Low
