### ISSUE TITLE
Spreadsheet excel download doesn't work with jszip 3.*

### ISSUE THREAD

**Issue by jvalkeejarvi** [telerik/kendo-ui-core#5888] opened 2020-07-02 10:00 UTC
### Bug report

Excel export of kendo spreadsheet does not work when using jszip **3.\***. When using version **2.\*** excel export works.

GitHub repo for issue reproduction: https://github.com/jvalkeejarvi/kendo-spreadsheet-excel-bug/

By looking at files `ooxml/kendo-ooxml.js` and `spreadsheet/workbook.js` it can be clearly seen that `toBlob` method returns a promise when the calling code expects it to be synchronous.

workbook.js:
```javascript
	                    kendo.saveAs({
	                        dataURI: options.forceProxy ? workbook.toDataURL() : workbook.toBlob(),
	                        fileName: data.fileName || options.fileName,
	                        proxyURL: options.proxyURL,
	                        forceProxy: options.forceProxy
	                    });

```

kendo-ooxml.js:
```javascript
	    toBlob: function() {
	        var zip = this.toZIP();
	        if (zip.generateAsync) {
	            return zip.generateAsync(BLOB_OPTIONS);
	        }
	        return new Blob([ zip.generate(ARRAYBUFFER_OPTIONS) ], { type: MIME_TYPE });
	    }

```

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** 3.5
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by dmanova** [comment] 2020-07-06 07:23
Seems related to https://github.com/telerik/kendo-ui-core/issues/2316

**Comment by jvalkeejarvi** [comment] 2020-08-10 08:48
According to this page: https://docs.telerik.com/kendo-ui/framework/excel/introduction JSZip 3 is supported. This should really be fixed. Currently we have to apply an ugly patch in our postinstall step.

**Comment by palhal** [comment] 2021-01-12 06:18
I'm also having this problem when using grid.saveAsExcel().

It seems that JSZip <= 3.2.2 works. When using more recent versions, the export fails like the call was ignored. No errors or warnings.

### Environment
- Kendo UI version: 2020.3.1118
- jQuery version: 3.5.1
- Browser: Chrome 87.0.4280.141

**Comment by veselints** [comment] 2022-05-10 14:54
Closing as duplicate of: #2316

**Closed by veselints** 2022-05-10 14:54 UTC
Labels: C: Spreadsheet, jQuery2
