### ISSUE TITLE
Setting a class through the attributes property in the SplitButton makes the button unclickable

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7251] opened 2023-03-09 13:08 UTC
### Bug report

If you set a class through the items.attributes configuration in the SplitButton, the respective button is unclickable

### Reproduction of the problem
1. Open this example - https://dojo.telerik.com/IvakivUc/5
2. Try to click the Item2 button
### Current behavior
The button is unclickable

### Expected/desired behavior

ТThe button should be clickable

### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment] 2023-06-12 12:16
Closing it as duplicate of https://github.com/telerik/kendo-ui-core/issues/7207 , which is fixed in 2023.1.425 .

**Closed by Dimitar-Goshev** 2023-06-12 12:16 UTC
Labels: Bug, SEV: Low, jQuery, FP: Unplanned, C: SplitButton
