### ISSUE TITLE
Removing an item with the clear button and showing the keyboard are not working as expected on mobile Windows 10.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2366] opened 2016-10-26 11:58 UTC
### Bug report
On Windows 10 touch device with Chrome browser the onscreen keyboard is shown only when the user taps inside the boundaries of the input element inside the MultiSelect. It is not shown, when tapping to the right of the input, i.e. tapping on the div element:
![image](https://user-images.githubusercontent.com/6614183/42454630-a6dd6cf4-8398-11e8-9e41-1b989135b9e1.png)

### Reproduction of the problem
Use Surface or Lenovo tablet with Windows 10.
1. http://demos.telerik.com/kendo-ui/multiselect/index
1. On the second MultiSelect tap to the right of the placeholder.

### Current behavior
The dropdown is expanded, but the keyboard is not auto expanded

### Expected/desired behavior
The dropdown is expanded AND the keyboard is not auto expanded. This works as expected, when tapping on the placeholder text (the placeholder is the input element).

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [Chrome]

**Comment by dannyhanke** [comment] 2017-02-07 11:33
Are there any new information about when this issue is going to be fixed ?

**Comment by ggkrustev** [comment] 2017-02-09 08:59
I am afraid there is no workaround that I could be aware of.

**Comment by Dimitar-Goshev** [comment] 2018-07-09 13:49
The way this issue was initially logged described two different MultiSelect bugs. The one related to clear button functionality is logged separately in the related issue and it is expected to be fixed in R3 2018 release. I am changing the description of this issue to address only the second issue - auto expanding of the software keyboard on tapping inside MutliSelect input.

**Comment by mparvanov** [comment] 2019-09-04 08:48
The issue is not reproducible with version 2019.2.619 in mobile Chrome 76.
Tested on Lenovo touch laptop and MS Surface with Win 10 and the following oprion auto display touch keyboard enabled:
https://www.windowscentral.com/auto-display-touch-keyboard-windows-10-desktop-mode

**Closed** 2019-09-04 08:48 UTC
Labels: Bug, C: MultiSelect, Kendo2, SEV: Low, Touch Devices
