### ISSUE TITLE
Kendo DropDownList bound to Model in Razor Pages scenario does not render data attributes

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5164] opened 2019-07-09 12:11 UTC
### Bug report

The data attributes are not rendered for the DropDownlist when bound to Model in Razor Pages.

### Reproduction of the problem

View:
```
@page
@model TelerikAspNetCoreApp12.Pages.IndexModel

<form>
    @(Html.Kendo().DropDownList()
            .Name("fabric")
            .OptionLabel("Select...")
            .DataTextField("Text")
            .DataValueField("Value")
            .BindTo(Model.Data)
            .Filter("contains")
    )
    <input type="submit" />
</form>
```
Back end:
```
namespace TelerikAspNetCoreApp12.Pages
{
    public class IndexModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        public List<TestModel> Data { get; set; } = new List<TestModel>();

        public void OnGet()
        {
            for (int i = 1; i <= 100; i++)
            {
                Data.Add(new TestModel() { Text = "product" + i, Value = i.ToString() });
            }
        }
    }
}
```

Model:
```
namespace TelerikAspNetCoreApp12.Models
{
    public class TestModel
    {
        [Required(ErrorMessage = "Please select")]

        public string Text { get; set; }

        public string Value { get; set; }
    }
}
```
Inspect the input field for the DropDownList. It does not have **data-val** and **data-val-required** attributes.

### Current behavior

The data attributes are not being rendered.

### Expected/desired behavior

The data attributes should be rendered.

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all] 

[TelerikAspNetCoreApp3.zip](https://github.com/telerik/kendo-ui-core/files/3411613/TelerikAspNetCoreApp3.zip)

**Comment by veselints** [comment] 2019-11-26 15:53
Closing the issue as it was caused by improper configuration of the project. Below you will find a working project with the latest Kendo version:

[InRazorPagesBindTo.zip](https://github.com/telerik/kendo-ui-core/files/3892711/InRazorPagesBindTo.zip)

**Closed by veselints** 2019-11-26 15:53 UTC
Labels: Bug, C: AutoComplete, C: DropDownList, FP: In Development, Kendo2, S: Wrappers (ASP.NET Core), SEV: Medium, Triaged

**Comment by paulito-bandito** [comment] 2021-04-21 13:03
Hi @veselints Could you elaborate on how the configuration was improper? I'm looking at a similar issue.

**Comment by veselints** [comment] 2021-04-23 11:30
@paulito-bandito, in the initial project sample the page model does not contain any field that is marked as `[Required]`. The `[Required]` attribute is used instead on a property of the model that is used to populate the DropDownList source collection:
```
[Required(ErrorMessage = "Please select")]
public string Text { get; set; }
```
Moreover, the DropDownList helper does not point to any property of the model.

If you review the correct sample that I have uploaded in my previous reply:
- The page model contains a `[BindProperty]` with `[Required]` attribute:
```
[Required]
[BindProperty]
public string KendoDropDownValue { get; set; }
```
- The DropDownList helper uses its strongly typed version to define value binding with that model field:
```
@(Html.Kendo().DropDownListFor(m => m.KendoDropDownValue)
```

**Comment by paulito-bandito** [comment] 2021-04-26 14:53
Ahhhh, it's clear now. Thanks a alot for the clarification. That helps a ton!
