### ISSUE TITLE
Spreadsheet Cell selection while entering formula in a cell results in improper cell values assigned to adjusted cells

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3606] opened 2017-09-21 11:56 UTC
### Bug report
Kendo UI Cell selection while entering formula in a cell results in improper cell values assigned to adjusted cells.

[Screenshot here](https://admin.telerik.com/ClientsFiles/219002d9-dda2-4eb4-b24a-2157e348738e_kendo%20ref%20issue.png);

Related to #3607

### Reproduction of the problem
* Create a Spreadsheet and populate with numbers cells A4, B4 and C4
* In cell D4 enter formula =A4+B4+C4
* Press enter to confirm
* On cell D4, press F2 to switch it to editing mode
* Then select a range of other cells say, a5:c5 and press Enter
*  Data starts appearing in cells E4 and F4 also along with D4
* User cannot delete the data in E4 and F4

**Comment by mishoo** [comment] 2017-09-25 09:19
Adding a range there turned it into an [array formula](http://docs.telerik.com/kendo-ui/controls/data-management/spreadsheet/end-user/list-of-formulas#array-formulas).  We have some differences from Excel here and the behavior might seem counter-intuitive (in Excel you must press Ctrl-Shift-Enter to save an array formula, which is like telling it “I know what I'm doing” ☺) — but still, this isn't a bug.

**Comment by vsingb3** [comment] 2017-10-16 10:11
Hi Mishoo,

I'm afraid I disagree to your last statement "....still, this isn't a bug." 

In Excel, when you press Ctrl+Shift+Enter, it does not add additional any additional values as kendo spreadsheet does.
Refer 6th line in "**Reproduction of the problem**" section, currently kendo spreadsheet add values in cell E4 and F4 . And the worst part is that you can't even delete it. 

I believe this is a must fix issue unless there is any technical limitation.

**Comment by mishoo** [comment] 2017-10-17 09:33
Pozzibly the only issue I see here is when one does it accidentally — because undo will not restore the values in the adjacent modified cells.  Reopening and will look for a more Excel-like solution.

**Comment by mishoo** [comment] 2017-10-17 10:51
The “fix” for this is to implement proper support for array formulas.  Since it's a new feature, I opened #3691 to track it.  Closing this one now.

**Closed by mishoo** 2017-10-17 10:51 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: Low
