### ISSUE TITLE
Grid throws error when model object name is a number

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#6827] opened 2022-05-05 11:23 UTC
### Bug report

Kendo grid throws a JavaScript error when the model property name contains only numbers. Ticket ID - 1563890

### Reproduction of the problem
Run the following dojo - https://dojo.telerik.com/elegEmAf/2

### Current behavior
A JavaScript error occurs

### Expected/desired behavior
The data should be visualized correctly.

**Comment by sspasova** [comment] 2024-01-13 20:24
I am closing this issue because it is no longer reproducible. Tested with Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/OpIHIKUp

**Closed by sspasova** 2024-01-13 20:24 UTC
Labels: Bug, SEV: Low, C: Grid, jQuery, Priority 1, FP: Unplanned
