### ISSUE TITLE
MVC DropDownList and ComboBox in IE and Edge do not retain the selected value, when navigating from and back to the view they are placed on

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2982] opened 2017-03-29 13:16 UTC
### Bug report
MVC DropDownList and ComboBox do not retain the selected value, when navigating from and back to the view they are placed on.

### Reproduction of the problem
* Implement the following razor view:
```` Razor
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem { Text = "Black", Value = "1" });
    listItems.Add(new SelectListItem { Text = "Orange", Value = "2" });
    listItems.Add(new SelectListItem { Text = "Grey", Value = "3" });
}

@Html.DropDownListFor(m => m.razor, listItems, "-- Select Status --")

@(Html.Kendo().DropDownListFor(m => m.ddl)
    .DataTextField("Text")
    .DataValueField("Value")
    .BindTo(listItems)
)

@(Html.Kendo().ComboBoxFor(m => m.combo)
    .DataTextField("Text")
    .DataValueField("Value")
    .BindTo(listItems)
)
````

* Pass the Model to the view:
```` C#
public ActionResult Index()
{
    var model = new TestModel()
    {
        razor = "2",
        ddl = "2",
        combo = "2",
        multi = new List<string>() { "2" }
    };

    return View(model);
}
````

* In IE or Edge open the view, where the helpers are placed;
* For each of the drop-downs select an item different than the initial (Orange) item;
* Navigate to another view;
* Navigate back to the initial view by clicking the browser back button;
* The .NET DropDownList will retain the manually selected value, while the Kendo DropDownList and ComboBox will have their values reset to the default (Orange);

### Expected/desired behavior
DropDownList and CombBox should not reset their values.

### Environment
* **Browser:** [ IE | Edge ] 
* **Kendo version:**  2019.2.514

**Comment by mparvanov** [comment] 2019-07-11 15:24
Sample Project for reproduction:
[TelerikAspNetCoreApp2.zip](https://github.com/telerik/kendo-ui-core/files/3382750/TelerikAspNetCoreApp2.zip)

**Comment by gyankov** [comment] 2021-06-03 14:21
I was able to replicate the behavior even in Chrome (91.0.4472.77) and the issue is caused due to several things. Firstly, the widget will always display the value that comes from its options, which overrides the element's value set by the browser's cache. To avoid that we have to modify the `_initValue` and `_setListValue` of the kendo.ui.List. For example:

```
    kendo.ui.List.fn._initValue = function () {
        var that = this,
            value = that.element.val() || that.options.value;
        
        if (value !== null) {
            that.element.val(value);
        } else {
            value = that._accessor();
            that.options.value = value;
        }

        that._old = value;
    }

    kendo.ui.List.fn._setListValue = function (value) {
        value = value || this.element.val() || this.options.value;

        if (value !== undefined) {
            this.listView.value(value)
                .done($.proxy(this._updateSelectionState, this));
        }
    }
```
However, this will give a bigger priority to the element's value than the value in the options, which might not be a good thing in other scenarios. 

Also, the browser restores the cached values right before the `pageshow` event is triggered which is after the document ready event (when we usually initialize the widgets). So at the time we create the widget's instance, the browser hasn't yet restored the values, to overcome that you could defer the initialization to the pageshow's event handler.

The following modified version of Misho's sample will work as expected in Chrome:
```
@model TelerikAspNetCoreApp2.Models.TestModel


@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem { Text = "Black", Value = "1" });
    listItems.Add(new SelectListItem { Text = "Orange", Value = "2" });
    listItems.Add(new SelectListItem { Text = "Grey", Value = "3" });
}

@Html.DropDownListFor(m => m.razor, listItems, "-- Select Status --")

@(Html.Kendo().DropDownListFor(m => m.ddl)
            .DataTextField("Text")
            .DataValueField("Value")
            .BindTo(listItems)
            .Deferred(true)
)

@(Html.Kendo().ComboBoxFor(m => m.combo)
            .DataTextField("Text")
            .DataValueField("Value")
            .BindTo(listItems)
            .Deferred(true)
)

<script>
    kendo.ui.List.fn._initValue = function () {
        var that = this,
            value = that.element.val() || that.options.value;
        
        if (value !== null) {
            that.element.val(value);
        } else {
            value = that._accessor();
            that.options.value = value;
        }

        that._old = value;
    }

    kendo.ui.List.fn._setListValue = function (value) {
        value = value || this.element.val() || this.options.value;

        if (value !== undefined) {
            this.listView.value(value)
                .done($.proxy(this._updateSelectionState, this));
        }
    }

    window.addEventListener("pageshow", function () {        
        @(Html.Kendo().DeferredScripts(false))
      
    });
</script>

```

Finally, even with the above changes, the value will still not restore in IE which I believe is due to a bug in the browser. After some testing I found out that IE is not capable of restoring cached values for elements that have changed their position in the DOM and in both drop down and combobox we wrap the element in a span.

By wrapping the .Net DropDown in a span as shown below you will notice that it stops retaining its value.

```
    $(function () {
        $("#razor").wrap("<span></span>");
    })
```
None of the above is related to the server wrappers, so I am removing the MVC/Core tags.

**Comment by Dimitar-Goshev** [comment] 2023-01-19 13:32
Closing this issue as IE is not supported since R1 2023.
And Microsoft Edge is now based on Chromium engine and its current version is 108.

**Closed by Dimitar-Goshev** 2023-01-19 13:32 UTC
Labels: Bug, C: ComboBox, C: DropDownList, jQuery
