### ISSUE TITLE
Spreadsheet Validation dialog allows Tab navigation on the page, while it is open

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2838] opened 2017-03-01 13:27 UTC
### Bug report
Spreadsheet Validation dialog allows Tab navigation on the page, while it is open

### Reproduction of the problem
- Go to [Validation demo](https://demos.telerik.com/kendo-ui/spreadsheet/validation);
- Type random text in cell C8;
- Press enter to move the focus off that cell - the validation warning will pop-up;
- Press Tab as many times as required to move focus back on one of the Spreadsheet cells;
- Press Retry - the typed value will be applied to the newly focused cell;

### Expected/desired behavior
Tab navigation should be disabled, while Validation dialog is opened

**Comment by mishoo** [comment] 2018-07-10 09:22
This seems to be no longer reproducible, the dialog is properly modal now.

**Comment by Dimitar-Goshev** [comment] 2018-07-10 14:15
The issue was reproducible despite the fact that the dialog was modal. It is reproducible in R1 2017 SP1 - 2017.1.223 - https://runner.telerik.io/fullscreen/aResoXUh - When tabbing, the focus goes out of the dialog up to the browser address bar and then inside Spreadsheet.
It was fixed in R2 2017 - 2017.2.504

**Closed by Dimitar-Goshev** 2018-07-10 14:15 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: Low
