### ISSUE TITLE
PDFViewer scaling is broken for some files

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7389] opened 2023-06-20 13:21 UTC
### Bug report

The scaling and zooming of certain PDF files appear to be broken.

### Reproduction of the problem

1. Open our online demo - https://demos.telerik.com/kendo-ui/pdfviewer/api
2. Click on the "Load" button and wait for the PDF to appear. The file appears at the top left instead of covering the full page.
3. Click on the zoom-in tool.
4. Click on the zoom-out tool - the scaling looks off.

Important note - The demo used different PDF files in v2023.1.425. The above example works as expected with the old files. Client also reported that some of his PDF files are rendered as expected and some are not.

### Current behavior

The PDF file is not scaled properly and the zoom-in/out tools are not working as expected.

### Expected/desired behavior

All PDF files should load in the same manner and the issues with zooming shouldn't be present.

Working sample(2022.2.621) - https://dojo.telerik.com/@gdenchev/OLATEQOg

### Environment

* **Kendo UI version:** 2023.3.1114 (Last working with 2022.2.621, broken since 2022.2.802)
* **jQuery version:** 3.7.0
* **Browser:** [all]

**Comment by sspasova** [comment] 2024-10-31 08:18
The issue is fixed with https://github.com/telerik/kendo/issues/20260.

**Closed by sspasova** 2024-10-31 08:18 UTC
Labels: Bug, SEV: Medium, jQuery, FP: Unplanned, C: PDFViewer, Regression
