### ISSUE TITLE
RTL popups auto-close when the body has scrollbar

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3781] opened 2017-11-20 14:57 UTC
### Bug report

RTL popups auto-close when the body has scrollbar

We cannot replicate the issue with the Version 63.0.3239.59 (Official Build) beta (64-bit) of Chrome.

### Reproduction of the problem

http://dojo.telerik.com/UhecEF/6

### Expected/desired behavior

The popups should stay open.

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 1.12.3
* **Browser:** [Chrome  Version 62.0.3202.94 (Official Build)]

**Comment by zdravkov** [comment] 2018-01-25 08:10
Not reproduced in the latest version of Chrome.

**Comment by Dimitar-Goshev** [comment] 2018-01-25 11:54
Not reproducible with Chrome Version 63.0.3239.132 (Official Build) (64-bit) and latest Chrome Version 64.0.3282.119 (Official Build) (64-bit).

**Comment by Dimitar-Goshev** [comment] 2018-01-25 12:17
I managed to reproduce the issue with Chrome 64 only for the DateTimePicker, when the screen height is less than 929px for the respective Dojo sample.

**Comment by zdravkov** [comment] 2018-02-05 08:07
One possible workaround is to set the 'k-rtl' class to a div instead of the body as for example it is done in this [dojo](http://dojo.telerik.com/UhecEF/17).

**Comment by Romanx** [comment] 2018-02-12 16:01
I seem to be having the same issue without the k-rtl class. Seems to be related to the screen height however isn't entirely consistently reproduce-able. Hoping this is the same, any update on what release this will likely land in?

**Comment by Dimitar-Goshev** [comment] 2018-03-13 12:19
The issue is no more reproducible on my side with **Chrome version 64.0.3282.186** and latest **Chrome version 65.0.3325.146**, even when screen height is less than 929px ([required to reproduce the issue before](https://github.com/telerik/kendo-ui-core/issues/3781#issuecomment-360450485)). I am closing it.

@Romanx The issue was reproducible even without k-rtl class in DropDownList, AutoComplete, ComboBox and MultiSelect, but it was fixed by closing [this item](https://github.com/telerik/kendo-ui-core/issues/3516), which was released in 2017.R3.SP1. The issue is still reproducible for Date/Time Pickers and it is logged [here](https://github.com/telerik/kendo-ui-core/issues/3986).

**Closed by Dimitar-Goshev** 2018-03-13 12:19 UTC
Labels: Bug, C: DropDownList, C: Popup, Kendo1, Kendo2, Priority 1, SEV: Medium
