### ISSUE TITLE
Missing style references in kendo resources under Edge browser

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2221] opened 2016-09-27 09:55 UTC
Missing style references in kendo resources under Edge browser.
Steps to reproduce the issue:
1) Open this dojo sample in Edge browser - http://dojo.telerik.com/avUro
2) Open the console.
Actual - See the missing references here - http://screencast.com/t/Nee7PeBjBe and here - http://screencast.com/t/ImKDesPYO
The issue is reproducible with the offline demos under Edge as well. It is not limited to the CDN.

**Comment by tsvetomir** [comment] 2017-02-23 08:36
Duplicate of #2460

**Closed by tsvetomir** 2017-02-23 08:36 UTC
Labels: Bug, SEV: Medium
