### ISSUE TITLE
Virtualized MultiSelect options.success removes SelectedItems and Doesn't Add Them Back

### ISSUE THREAD

**Issue by harlankoehn** [telerik/kendo-ui-core#1999] opened 2016-07-26 16:23 UTC
I have a Virtualized Multi-Select (Angular 1.x) in a cascading combo scenario where the user selects Equipment models. The issue is that the selected Tags get cleared when they wouldn't need to. For example, you might select Ford, and Chrysler as Makes (parent Multiselect) then select several different Ford and Chrysler models from the virtualized models multiselect. Next you might decide to add Chevrolet to the Makes multiselect and when you do this, it causes all your selections to disappear in the virtualized models mutiselect.

I have a dojo example here:
http://dojo.telerik.com/@villagemedia/Inugi/42

I'm also troubleshooting to find the actual logic bug involved and this one seems pretty complex to me. The bug is basically that _getter fails to actually get. Apparently because the dataSource.inRange > _findRange functions fail to find a range because of a mismatch in the number of elements in the new data list compared to the existing one. [Line 3965 in kendo.data.js](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.data.js#L3965) evaluates to false because count might be for example, 12 items while (end - start) might be 15 items. This results in [_getter exiting at line 1172 (kendo.virtuallist.js)](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L1172) with return null. Which means that ultimately the [item at line 1279 (kendo.virtuallist.js) is null](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L1279).

I'm suspicious this is by design. What normally happens is that multiselect selections get deselected and then reselected. In this case, the reselection fails to occur, apparently because the _values array has been cleared by the [slice action at line 1271 (kendo.virtuallist.js)](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L1271).

So I don't know what the solution is here. Should the _values array be cleared only as items are successfully [handled at lines 1279-1281](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L1279)?

I think the whole purpose of [_range](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L1269) is to try to get the new indexes for existing selections. Correct?

Note that the call stack during this problem is roughly something like this:
[843 select: function(candidate)](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L843)
[863 _triggerChange(removed,added)](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L863)
[836 this.trigger(CHANGE ....](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L836)
[444 value](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L444)
[472 _prefetchByValue(value)](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L472)
[478 _prefetchByValue](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L478)
[491 match = isPrimitive(item) ? value[i] === item : value[i] === valueGetter(item);](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L491)
(not sure what all goes on here)
[1269 _range:](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L1269)
[1279 item = this._itemMapper(this.getter(i, index), i, value);](https://github.com/telerik/kendo-ui-core/blob/b447e4fbb794e7024f2ca18cfbcdfc4392e88128/src/kendo.virtuallist.js#L1279)

**Comment by ggkrustev** [comment] 2016-07-27 08:51
The widget cleared the selected items, because the valueMapper was always returning empty array for the selected indices. This explicitly will tell the widget to clear the selected values. When the option.success is moved into the then callback, the widget will preserve the selected items:

[http://runner.telerik.io/fullscreen/eXAQA](http://runner.telerik.io/fullscreen/eXAQA)

I will close this thread, as the discussed issue not a bug, nor a feature request.

**Closed by ggkrustev** 2016-07-27 08:51 UTC
Labels: Deleted
