### ISSUE TITLE
Percentage value overlaps the name of the uploaded file on a mobile device

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2640] opened 2017-01-18 15:36 UTC
### Bug report

Percentage value overlaps the name of the uploaded file on mobile phone. 

### Reproduction of the problem

Please refer to the attached images (portrait and landscape modes). 

### Expected/desired behavior

The percentage value should not overlap the name of the file. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** [Android 6.0.1 Chrome 55 Web Browser 

![screenshot_20170118-171529](https://cloud.githubusercontent.com/assets/3042944/22070235/f44e7286-dda3-11e6-9080-4d0938e0e236.png)
![screenshot_20170118-171541](https://cloud.githubusercontent.com/assets/3042944/22070236/f4507a36-dda3-11e6-9996-b78fbf3b1353.png)

]

**Comment by Dimitar-Goshev** [comment] 2017-12-22 09:15
The issue is fixed by fixing this related issue: https://github.com/telerik/kendo-ui-core/issues/3021

**Closed by Dimitar-Goshev** 2017-12-22 09:15 UTC
Labels: Appearance, Bug, C: Upload, Kendo2, SEV: Low
