### ISSUE TITLE
Some random slots are not selectable in Chrome on Surface Book

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4758] opened 2019-01-14 05:35 UTC
### Bug report

When tapping on slots in Scheduler some slots can't be selected and some can. This behavior was so far successfully replicated only on Chrome on Surface Book.

ticket: 1381327 

video of the issue - Tuesday and Thursday are not selected though they are tapped - https://www.screencast.com/t/4h4tEkFMmx

A possible workaround is to override this function:
```
kendo.ui.WeekView.fn.selectionByElement= function(cell) {
  var offset = cell.offset();
  return this._slotByPosition(offset.left + 1, offset.top);
}
```
Here is a dojo where it the workaround was applied - https://dojo.telerik.com/@zdravkov/ukokoLuL

ticket: 1474456 

The issue occurs in Chrome and Edge (Chromium) browsers and reports that on mouse click and select some Scheduler slots can be selected and some can't. The issue is reported for both DayView and WeekView. Reportedly the issue is observed on high-resolution monitors(4K monitors) when using Windows display scaling, where disabling the scaling or implementing the above-suggested workaround resolves the issue for the WeekView. 

A possible workaround for the issue, when experienced in the  DayView is to override this function:
```
kendo.ui.DayView.fn.selectionByElement= function(cell) {
  var offset = cell.offset();
  return this._slotByPosition(offset.left + 1, offset.top);
};
```

* **Kendo UI version:** 2020.2.617
* **Browser:** [Chrome 71.0.3578.98, Edge  ]

**Comment by zdravkov** [comment] 2019-01-30 12:35
A possible solution is to get the coordinates of the selected cell from the touched point instead of the touched element offset.

**Comment by aleksandarevangelatov** [comment] 2020-07-09 13:48
The issue is also reported in ticket: 1474456

**Comment by sspasova** [comment] 2023-11-27 09:16
Closing this as no longer reproducible.

**Closed by sspasova** 2023-11-27 09:16 UTC
Labels: Bug, SEV: Medium, C: Scheduler, jQuery, Triaged
