### ISSUE TITLE
Unexpected auto-closing of Grid's page size DropDownList

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3322] opened 2017-06-14 11:12 UTC
### Bug report
[Reproduction video](https://www.screencast.com/t/PbJau83x)

The issue happens when there is scrollbar on the page before and after changing the page size of a Grid to a smaller value. The Grid should be the last element on the page. When the user changes the page size in the footer to a smaller value, and then tries to change the page size again to greater value , the dropdown opens and then auto-closes repeatedly.

### Reproduction of the problem

1. http://dojo.telerik.com/AJoWO
2. Scroll to the bottom of the page
4. Change the page size of the second grid from 10 to 5
5. Try to change the page size of the second grid again.

### Current behavior

The dropdown opens and then auto-closes repeatedly. If the page is scrolled, the dropdown will open as expected.

### Expected/desired behavior

The dropdown opens and remains opened to allow the used to select page size.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [Chrome]

**Comment by PreslavKozovski** [comment] 2017-06-14 11:13
Workaround: [http://dojo.telerik.com/equJO](http://dojo.telerik.com/equJO)

**Comment by Dimitar-Goshev** [comment] 2017-09-04 13:49
Duplicate of: https://github.com/telerik/kendo-ui-core/issues/2768

**Closed** 2017-09-07 08:04 UTC
Labels: Bug, C: DropDownList, Kendo2, Priority 1, SEV: Low

**Comment by mrjijo** [comment] 2020-03-11 06:26
Try this costume height to DD menu , i solved this issue after a long time wasted 
NOTE: make changes on height as per your needs.. in my case 189px height solved my issue 

.k-animation-container{ 
height: 189px !important;  
overflow: hidden !important;
}

**Comment by Sima338** [comment] 2020-09-03 09:40
> Try this costume height to DD menu , i solved this issue after a long time wasted
> NOTE: make changes on height as per your needs.. in my case 189px height solved my issue
> 
> .k-animation-container{
> height: 189px !important;
> overflow: hidden !important;
> }

Seems it works nicely for all cases 
.k-animation-container{
  height: 100% !important;
}
