### ISSUE TITLE
Test a scenario with TreeView bound to a remote datasource with CRUD operations 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6500] opened 2021-07-26 22:05 UTC
### Potential bug report
The Treeview is not tested if all its functionalities work correctly when the component is bound to a remote data source. What is meant here is that there could be potential issues with the Drag& Drop functionality of the component when working with create/update/delete configurations of the Treeview's datasource. 

### Task
Test the Treeview which datasource has definitions for transport create, update and delete with a suitable backend service. Test the following scenarios:
- The Drag&Drop functionality in one Treeview is working correctly
- The Drag&Drop functionality between two Treeviews is working correctly
- Test scenarios of Drag & Drop an item from root to child and vice versa.

### TBD 
- If there are no issues with the Treeview in the described scenario, add an example and a documentation article describing how the component should be configured. 
- If there are issues with the Treeview in the discussed scenario, make the needed changes in the datasource and Treeview implementation. Add an example and documentation article that describes how the Treeview should be configured.

**Comment by veselints** [comment] 2021-07-27 06:18
The HierarchicalDataSource used in the TreeView widget was NOT intended for editing and CRUD operations. By definition, the TreeView itself is a read-only navigation widget that allows selection. If we want to provide stable support for CRUD in any TreeView scenarios, I would consider altering the widget and using the TreeList DS for that. The TreeList DataSource will eliminate any potential editing issues. I would rather think of substituting the HierarchicalDataSource. There is absolutely no need to have two different DS classes implementing the same functionality.

**Comment by ag-petrov** [comment] 2024-02-22 13:29
Closing this one as it is not a bug. If we want specific scenarios we should open a feature request.

**Closed by ag-petrov** 2024-02-22 13:29 UTC
Labels: Bug, SEV: High, C: TreeView, jQuery
