### ISSUE TITLE
Scheduler header misalignment in "Timeline Month" view

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5474] opened 2019-12-12 09:16 UTC
### Bug report

The Scheduler's header container holding the dates and hours in the "Timeline Month" view is misaligning when the "Create new event" popup for the last event in the view appears on the screen.

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/icOCOmaG) and run it
2. Scroll horizontally to the max right position
3. Double click on the last day in the view

### Current behavior
The header and the cells differentiating each day in the view are misaligned
![image](https://user-images.githubusercontent.com/41293735/70698406-1340a380-1cd0-11ea-81aa-66ab2eed03b0.png)

### Expected/desired behavior
There shouldn't be any misalignments when the "Create new event" popup appears on the screen

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by sspasova** [comment] 2023-12-12 08:09
I am closing this issue because it is no longer reproducible using Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/OmunIyiR. Tested using Chrome v.120. 
![image](https://github.com/telerik/kendo-ui-core/assets/43406491/939e2515-5626-4606-b599-aebabf462660)

**Closed by sspasova** 2023-12-12 08:09 UTC
Labels: Bug, SEV: Low, C: Scheduler, jQuery, FP: Unplanned, Triaged
