### ISSUE TITLE
No sorting arrows appear in Grid when datasource is programatically sorted and read method called

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5755] opened 2020-05-11 07:12 UTC
### Bug report
If the datasource of a Grid with "autoBind: false" configuration is sorted using the below code, the data sorting in the component is correct but no sorting arrows appear in the headers of the sorted columns.

>    var grid = $("#grid").data("kendoGrid");
>    var sort = [{field: "Freight", dir: "desc"}, {field: "OrderDate", dir: "asc"}];
>    grid.setOptions({ dataSource: {sort: sort }});
>    grid.dataSource.read();

* This is a regression introduced in version 2020.1.114

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/EniWAFaF) example and run it
2. See the headers of the "Freight" and "Order Date" columns

### Current behavior
The sorting arrows are missing for both the "Freight" and "Order Date" columns
![image](https://user-images.githubusercontent.com/41293735/81531072-baeafc00-936a-11ea-82ab-8386f2830d71.png)

### Expected/desired behavior
The arrows should appear as shown in the image below. The correct behavior can be observed in [this Dojo example](https://dojo.telerik.com/OqeGEmey)
![image](https://user-images.githubusercontent.com/41293735/81531091-c3dbcd80-936a-11ea-819b-477217c1dd76.png)

### Environment

* **Kendo UI version:** 2020.1.406
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Alex-Bubblemaster** [comment] 2020-05-15 08:15
Duplicate of #5623

**Closed by Alex-Bubblemaster** 2020-05-15 08:15 UTC
Labels: Bug, C: Grid, Kendo1, Priority 5, SEV: Medium
