### ISSUE TITLE
Duplicated More Formats dialog in Spreadsheet

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2279] opened 2016-10-10 15:37 UTC
### Bug report
Choosing Custom Format->More Formats... creates two Custom cell format windows

### Reproduction of the problem

On the [Spreadsheet demo](http://demos.telerik.com/kendo-ui/spreadsheet/index) choose custom formats -> More formats as demonstrated in this [Screencast](http://screencast.com/t/3cR1i5a7iGAY)

It is not reproduced when the width of the Spreadsheet puts the Custom formats button in a dropdown menu - [Screencast](http://screencast.com/t/YJIYmObR)

### Environment

* **Kendo UI version:** 2016.3.914
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2016-12-07 13:17
The issue starts to reproduce since R3 2016 (2016.3.914)

**Comment by mishoo** [comment] 2017-01-20 09:21
This happens because [this handler](https://github.com/telerik/kendo/blob/master/src/spreadsheet/toolbar.js#L412) is getting called twice.  The issue appears to come from the DropDownList, here's the output of `new Error().stack` in that handler:

![stacktrace](https://cloud.githubusercontent.com/assets/334725/22143179/cb2f8cfa-df01-11e6-923c-e9f97018adc4.png)

Apparently, once from `_click` and once from `_focusoutHandler`.

I'm not sure how to fix this without breaking something.. the code in DropDownList is full of special cases.  Adding @gyoshev and @ggkrustev 

To fix the issue only for the spreadsheet (not a nice hack though) we could just throttle the handler with a setTimeout and exec only once within a short period (i.e. 10ms).

**Comment by gyoshev** [comment] 2017-01-20 10:16
I believe the second call is due to the [resetting of the title](https://github.com/telerik/kendo/blob/master/src/spreadsheet/toolbar.js#L704).

Not having it in place fixes the issue, but causes others, as it keeps the selected dropdown value.
![image](https://cloud.githubusercontent.com/assets/90405/22145214/0f791988-df09-11e6-909e-e997b183ff9b.png)

@ggkrustev is there a way to reset the selection without triggering a second change event with the same value? Or is this a bug?

**Comment by mishoo** [comment] 2017-01-26 14:29
Fixed in #2327.

**Closed by mishoo** 2017-01-26 14:29 UTC
Labels: Bug, C: Spreadsheet, SEV: High
