### ISSUE TITLE
panel bar nested ng-repeat duplicating array content

### ISSUE THREAD

**Issue by dyanarose** [telerik/kendo-ui-core#1313] opened 2015-12-09 22:42 UTC
As seen in this example: http://dojo.telerik.com/@dyanarose/AbAVE

The idea is to be able to set the panels dynamically while also compiling the panel contents against the scope.

It looks to work, except that the list in the repeater is getting duplicated unexpectedly.

See this tweet that notes previous versions of the library are working as expected: https://twitter.com/TelerikDevRel/status/674680163255189504

**Comment by KirilNN** [comment] 2015-12-10 07:19
The issue is resolved with the latest master, so please try upgrading :)

**Closed by KirilNN** 2015-12-10 07:19 UTC
