### ISSUE TITLE
 Panelbar does not expand when content property is used

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2682] opened 2017-01-30 06:16 UTC
### Bug report

Content property is used in the binding of the control :
$("#panelbar").kendoPanelBar({
      dataSource: [       
          {
              text: "<b>Item 2</b>",
              encoded: false,                                 // Allows use of HTML for item text
              content: "text"                                 // content within an item
          }
      ]
  });

### Reproduction of the problem
http://dojo.telerik.com/orIGi/2

### Current behavior
The node can't be expanded.

### Expected/desired behavior
The node can be expanded correctly.

### Environment

* **Kendo UI version:2017.1.118
* **jQuery version:1.12.3.
* **Browser:** [all]

**Comment by IvanDanchev** [comment] 2017-03-28 14:14
A case not covered by the previous fix is when an item has **content** and **expanded: true** options set [Dojo ](http://dojo.telerik.com/OxIru/5)example. The item does not show its content (left PanelBar, first item). It cannot be collapsed/expanded. Setting expanded: true to an item that has content should be supported, because such an item is expandable through the PanelBar's expand method and the widget's expand method fires when expanding it manually, similarly to expanding an item that contains child items.

**Comment by Dimitar-Goshev** [comment] 2017-08-29 07:23
The issue from the previous comment is logged as a separate one - https://github.com/telerik/kendo-ui-core/issues/3349
I am closing the current issue as fixed. It is not reproducible with versions 2017.1.223+

**Closed by Dimitar-Goshev** 2017-08-29 07:23 UTC
Labels: Bug, C: PanelBar
