### ISSUE TITLE
Incorrect PanelBar selected item appearance in BlueOpal, Bootstrap, Default, Fiori, Metro, Moonlight, Office365, Silver and Uniform themes

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4828] opened 2019-02-06 14:40 UTC
### Bug report
Regression introduced in R1 2019.

- [x] Wrong color for initially selected root item. (They do not have .k-state-default class applied, compared to initially not expanded items. Adding .k-state-default class makes them look as the other items when selected, but this class was not needed in earlier versions)
  - BlueOpal, Default, Fiori, **Metro**, **Office 365**, Silver - text is dark, instead of white
  - Moonltight - text is white, instead of dark

- [ ] Wrong color for selected child item:
  - **Bootstrap**, Default, Metro, Silver - text is dark, instead of white
  - Uniform - background is darker and item text is illegible:
![image](https://user-images.githubusercontent.com/6614183/52475437-26607f80-2ba4-11e9-8c00-5252d14c055a.png)

### Reproduction of the problem
Reproducible in the PanelBar demos, on which there is an initially opened item.
1. Go to https://demos.telerik.com/kendo-ui/panelbar/index
1. Select the corresponding theme through demo's theme chooser.
1. For reproducing root item issues, inspect the first root item "My Teammates", which is initially selected.
1. For reproducing child item issues, expand the third root item "Programs" and then select its child item "Monday"

### Current behavior
E.g. Silver - The selected root item text color is #515967

### Expected/desired behavior
E.g. Silver - The selected root item text color is #fff

[Feedback Portal item](https://feedback.telerik.com/aspnet-core-ui/1386434-selected-color-wrong)
### Environment
* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by joneff** [comment] 2019-02-10 10:29
@TeyaVes @PreslavKozovski this, and the related issue, looks like it's a side effect of changing the button colors

**Comment by TeyaVes** [comment] 2019-02-11 09:38
@joneff , @Dimitar-Goshev , the issue is rather introduced by this fix: https://github.com/telerik/kendo/commit/2a24da8c440afe2ca565e599fa45668fdb58c96f as the selector for the normal state of the link is stronger than the one for the selected. It's different from the related issue, which is why I think we should remove the reference between them.

**Comment by TeyaVes** [comment] 2019-02-11 10:37
Uniform and blue opal selected background color is fixed in:  https://github.com/telerik/kendo/pull/9378

**Closed** 2019-02-18 07:33 UTC
Labels: Appearance, Bug, C: PanelBar, Kendo2, Priority 5, SEV: Medium, Triaged
