### ISSUE TITLE
Fix axisCrossingValues misalignment in StockChart

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2530] opened 2016-12-12 14:14 UTC
Stock chart is misaligned when axisCrossingValues of the categoryAxis is defined.
The issue is reproducible with the Q3 2016 release.
Actual - http://www.screencast.com/t/UX0X9Rl2Q
Dojo sample - http://dojo.telerik.com/UpOKE/2

**Comment by tsvetomir** [comment] 2016-12-12 14:45
Duplicate of #2479

**Closed by tsvetomir** 2016-12-12 14:45 UTC
Labels: Bug, C: StockChart, SEV: Low
