### ISSUE TITLE
Combobox: clear icon shows up initially even if selection field is empty

### ISSUE THREAD

**Issue by AGuyCalledGerald** [telerik/kendo-ui-core#3892] opened 2018-01-04 10:51 UTC
### Reproduction of the problem

look here: https://demos.telerik.com/aspnet-mvc/combobox/template

Although the selection selection field is empty, the clear icon ("x") shows up on the right of the field.
If the field is clicked and blurred, the clear icon vanishes.
The behaviour of the control seems inconsistent.

### Environment

* **Kendo UI version:** probably latest
* **jQuery version:** unknown
* **Browser:** Chrome latest

**Comment by zdravkov** [comment] 2018-01-09 07:40
Duplicate of #3645 
Fortunately it is already fixed and will be available in the upcoming release.

**Closed** 2018-01-09 07:40 UTC
Labels: C: ComboBox, Kendo2
