### ISSUE TITLE
Property 'setOptions' in type 'Stepper' is not assignable to the same property in base type 'Widget'.

### ISSUE THREAD

**Issue by SaphuA** [telerik/kendo-ui-core#5845] opened 2020-06-11 08:21 UTC
### Bug report

I have updated "@progress/kendo-ui" to version "2020.2.513". When I compile my typescript project, I get the following compile error from the index.d.ts file:

> Property 'setOptions' in type 'Stepper' is not assignable to the same property in base type 'Widget'.

The error is on line 8396:
`setOptions(options?: StepperOptions): void;`

This is the same line in class `Widget`:
`setOptions(options: Object): void;`

**Comment by SaphuA** [comment] 2020-06-17 08:19
I see it has been fixed in this commit. When will this be published? As the current version of Kendo does not compile.

https://github.com/telerik/kendo-ui-core/commit/0bbd8a8b4399b40b6b988d9a5955be11c7a097a0#diff-0935ff63aa6826c5a93ab0b6870b2776R8396

**Comment by zdravkov** [comment] 2020-10-06 09:24
The issue is fixed in the latest 2020.3.915 version.

**Closed by zdravkov** 2020-10-06 09:24 UTC
Labels: Kendo2
