### ISSUE TITLE
ToolBar shrinks if all of its tools are under the overflow button

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4107] opened 2018-03-23 13:18 UTC
### Bug report
Since R1 2018 the ToolBar's wrapper element does not have min-height set, which causes it to shrink in height when all of its tools are placed under the overflow button. 

Workaround:
```
.k-toolbar-resizable {
   min-height: 2.4375em;
} 
```

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment] 2018-12-21 15:00
After the fix the ToolBar becomes 4px higher in all LESS themes except Bootstrap v3, Fiori, Material, MaterialBlack and Nova. All themes using kendo.common.css and the Office 365 theme are affected.
As a result buttons are not vertically centered. Reproducible on Basic usage demo:
![image](https://user-images.githubusercontent.com/6614183/50348592-dff68900-0541-11e9-87f3-885af1774c72.png)

The issue may be fixed by adding `box-sizing: border-box;` to the toolbar.

**Comment by Dimitar-Goshev** [comment] 2019-01-04 08:07
- After reviewing the expected height once again, it seems that 44px is the correct expected height for Default theme, and the problem is in fact incorrect padding, which results in not centering the buttons vertically. So the padding should be enough to make the toolbar 44px high in Default and other themes using kendo.common.css
- After the fix, toolbar with all its buttons inside the overflow is less than 44px high. Review the min height applied to the toolbar to achieve the correct height even without buttons.

**Comment by joneff** [comment] 2019-02-10 10:16
As per discussion, this is the correct behaviour.

**Closed by joneff** 2019-02-10 10:16 UTC
Labels: Appearance, Bug, C: ToolBar, Kendo2, Next LIB, Priority 5, SEV: Medium
