### ISSUE TITLE
'Maximum call stack size exceeded' because of the that._initOptions(options); in View = kendo.ui.Widget.extend() makes deepExtend 

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5109] opened 2019-06-12 08:23 UTC
### Bug report
'Maximum call stack size exceeded' because of the that._initOptions(options); in View = kendo.ui.Widget.extend() makes deepExtend:
https://github.com/telerik/kendo/commit/754f7bd5bc596af63cfac29f8911df30288d41ce#diff-30586ad1c9f894dc7aff2e84d548776bR62

This is a regression introduced with the above change.

### Reproduction of the problem
https://dojo.telerik.com/ilITUBIZ

### Current behavior
'Maximum call stack size exceeded' error is thrown.

### Expected/desired behavior
No error should be thrown

### Environment
* **Kendo UI version:** 2019.2.514
* **Browser:** [all]

**Comment by veselints** [comment] 2019-06-12 08:25
A possible workaround for the above would be the following:

```js
kendo.View.fn._initOptions = function(options) {
    this.options = $.extend({}, this.options, options);
}
```

**Comment by Stamo-Gochev** [comment] 2019-06-12 11:51
Looking into the case in more details, a runable sample from [Ticket 1412738](https://admin.telerik.com/?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1412738) will be very helpful. There might be a problem, but the current options of the view do not contain a complex (widget) option that can fail on `deepExtend`.

**Comment by edvinv** [comment] 2019-06-12 13:37
Hi, as I said in the issue ticket the problem has probably something to do with recursion. To demonstrate this you just need simple model where you have some nested property to reference parent object, like in this [example](https://dojo.telerik.com/ilITUBIZ). Run it in see output in console window.

**Comment by Stamo-Gochev** [comment] 2019-06-12 13:43
@edvinv Can you provide some details why such a recursive structure of the model is required in your case?

**Comment by edvinv** [comment] 2019-06-13 07:03
It is not what I try to achieve, it is more the way application is structured. Here is simple example, to get big picture.
```typescript
class ViewModel extends kendo.data.ObservableObject {
	// ... basic functionality for all viewmodels
}

class LoginViewModel extends ViewModel {
	constructor (private sessionsStore: stores.ISessionsStore, private systemStore: stores.ISystemStore){

	}

	// ui properties

	// ui events

	// validating etc...
}
```

As you can see this structure is very similar to angular components. Application has a lot of ViewModel and these ViewModels are bound to Views.  

I think that ViewModels normally don't have back references, but services, that are injected into ViewModel, certainly can. Services can contain data that naturally have graph shape or even references to external library data.

So as you can see it is very difficult, especially in big application, to control the shape of view model. But on the other hand, this should just work. Application should shape viewmodel data in the best way to solve particular problem.

**Comment by Stamo-Gochev** [comment] 2019-06-13 07:19
@edvinv I will push a fix regarding the `deepExtend` logic as it was a side effect that is not currently critical. However, using cyclical structures are not intended to be supported for now. Cyclical references can be handled explicitly by the developer - for example, the graph data containing loops can be transformed beforehand and then the new model (without loops) can be passed to the constructor of the view.

**Comment by Stamo-Gochev** [comment] 2019-06-13 07:47
@edvinv The issue can actually be reproduced without using `kendo.View` - https://dojo.telerik.com/ilITUBIZ/8 . Creating the observable with cyclical references has never worked (the Dojo example uses the oldest available version - 2015.1.318) as loops are not supported. If cyclical references are present in the raw data, then you can transform them beforehand to remove these references and then instantiate the observable.

Can you provide a Dojo example with your real scenario that shows how the app was working with a previous version of Kendo UI and then the upgrade to version 2019.2.514 introduced the bug? It looks like the call stack problem is caused by a problem in the view, which is different from the problem with the observable that the [Dojo example](https://github.com/telerik/kendo-ui-core/issues/5109#issuecomment-501277029) initially showed.

It will be really helpful if you can add this further information in the support ticket, so we can discuss the issue in more detail.

**Comment by Stamo-Gochev** [comment] 2019-06-14 04:40
Closing as the exact real world scenario will be discussed in the ticket. Will be reopened again if necessary.

**Closed by Stamo-Gochev** 2019-06-14 04:40 UTC
Labels: Bug, C: View, Kendo1, Priority 1, SEV: Medium

**Comment by ag-petrov** [comment] 2019-07-11 13:58
We decided to include the previously provided solution in our code base. The issue should not be reproducible with the next version.
