### ISSUE TITLE
Unable to Cut and Paste into NumericTextBox with dollar sign or commas

### ISSUE THREAD

**Issue by geraldbauer** [telerik/kendo-ui-core#4923] opened 2019-03-19 19:22 UTC
This problem has been reported and marked closed (https://github.com/telerik/kendo-ui-core/issues/2962 and https://github.com/telerik/kendo-ui-core/issues/2773). Comments have been posted there asking the question "what version" should we use. Those questions have gone unanswered; thus this new issue. What version of Kendo Angular 2+ (TypeScript) should we be using to resolve these issues?

**Comment by matanasov** [comment] 2019-03-25 08:56
The issue is fixed in 2017 R2 SP1 ([2017.2.621](https://www.telerik.com/support/whats-new/kendo-ui/release-history/kendo-ui-r2-2017-sp1)) version of the Kendo UI for jQuery numeric text box and doesn't affect angular components that use a separate repo:

https://github.com/telerik/kendo-angular

**Closed by matanasov** 2019-03-25 08:56 UTC
