### ISSUE TITLE
Narrator does not announces associated "column header" when narrator focus goes on data cell present under table column.

### ISSUE THREAD

**Issue by ylux587** [telerik/kendo-ui-core#5907] opened 2020-07-08 17:26 UTC
### Bug report

Narrator does not announces associated "column header" when narrator focus goes on data cell present under table column.

### Reproduction of the problem
Render a grid and has come column and data. Use Narrator to read the screen and move to data cell

### Current behavior
Narrator does not announces associated "column header" when narrator focus goes on data cell present under table column.

### Expected/desired behavior
Narrator should announce associated "column header" when narrator focus goes on data cell present under table column..

### Environment

* **Kendo UI version:** Kendo UI version: 2020.2.513
* **jQuery version:** 3.5.1
* **Browser:**Chromium Edge Version: 84.0.488.1 (Official build) dev (64-bit)
* **NVDA Version:**2019.3.1

**Comment by dmanova** [comment] 2020-07-20 17:05
Duplicate of https://github.com/telerik/kendo-ui-core/issues/5576

**Closed by dmanova** 2020-07-20 17:05 UTC

**Comment by ylux587** [comment] 2020-09-18 21:04
We tried approach that was described , but narrator still does not pronounce the column header name event the aria-describedby property is set correctly.

We’ve run the narrator for the sample as well, and it is also not working correctly

**Comment by booninja** [comment] 2021-11-11 10:31
This is still an issue for NVDA screen readers. Both the sample from telerik and our implementation. 

Here is a snippit from the NVDA speech viewer when scanning through the telerik sample:

Category: Seafood, Total Sales: $21,100.00
row 2  column 1
column 2  check box  not checked    Select row
column 3  Ikura   
column 4  $31.00
column 5  not available   
column 6  Seafood
column 7  slider    2   
column 8  graphic    Great Britain

As can be seen, the screen reader is ignoring the column headers.
