### ISSUE TITLE
DropDownTree does not update checked items after setDataSource

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4912] opened 2019-03-14 12:45 UTC
### Bug report

DropDownTree does not update checked items after setDataSource

### Reproduction of the problem
https://dojo.telerik.com/@zdravkov/OCAnuGIR
1) Open the dojo and press the button

### Current behavior
The selected items are not updated

### Expected/desired behavior
The selected items  should be updated

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by FakeCode** [comment] 2019-04-15 16:53
I am also waiting for the fix;
Or need an alternate solution i.e remove/clear dynamically the selected value from dropdowntree.

**Comment by FakeCode** [comment] 2019-04-17 14:13
I got my solution
var dropDownTree=$("#dropdowntree").data("kendoDropDownTree");
            dropDownTree._getSelection()._clearValue(); ////before setting new datasource clear value
            dropDownTree.setDataSource(dataSource);

**Comment by IvanDanchev** [comment] 2019-10-23 13:50
The issue is still reproducible, if the dataSource is set more than 2 times consecutively:
[https://dojo.telerik.com/UcOqEhOh](https://dojo.telerik.com/UcOqEhOh)
1. Click the button 3+ times. 
The checked items are not updated.

**Comment by Dimitar-Goshev** [comment] 2019-11-01 11:38
@zdravkov After the fix, if the datasource has no checked items and it is set to DDTree through setDataSource method, the DDTree will appear as a 2px line.
To reproduce the issue, use the setup from the Dojo in [this comment](https://github.com/telerik/kendo-ui-core/issues/4912#issuecomment-545453708).
1. Run the Dojo with the fix - 3 items are checked.
1. Expand the DDTree and uncheck all items - no items are checked in dataSource1
1. Click Change data 2 times to load dataSource1 again

Result: the DDTree is 2px high

The same scenario may be tested with directly setting dataSource1 as follows:
```
          var dataSource1 = new kendo.data.HierarchicalDataSource({
            data: [
              { text: "Option 1", checked: false },
              { text: "Option 2", checked: false },
              { text: "Option 3", checked: false }
            ]
          });
```
When loading the data initially, the DDTree height is as expected. Then click Change data 2 times to load dataSource1 again
Result: the DDTree is 2px high

**Closed** 2019-11-08 10:32 UTC
Labels: Bug, C: DropDownTree, FP: In Development, Kendo2, Next LIB, Priority 2, SEV: Medium
