### ISSUE TITLE
OptionLabel not shown correctly when value and item templates are used with AngularJS

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#393] opened 2014-11-14 10:29 UTC
Can be reproduced here:

http://dojo.telerik.com/ocOlU

**Comment by hhagely** [comment] 2015-02-04 16:46
Definitely seeing the same issue as rogier21.  Option labels and templates for dropdownlist do not work well with Angular.

**Comment by BrianMcBrayer** [comment] 2015-03-10 14:01
Can we get this issue escalated? I'm looking through the source to try to create a patch for our systems, but I don't have the time right now.

**Comment by ggkrustev** [comment] 2015-03-30 11:45
Seems to be addressed in the latest release of KendoUI. Here is a [demo](http://dojo.telerik.com/IHIla) that proves that.

**Closed by ggkrustev** 2015-03-30 11:45 UTC
Labels: Bug, C: AngularJS, C: DropDownList, SEV: Medium

**Comment by amopitt** [comment] 2015-04-07 12:47
Unless I am going insane, your demo isn't working right.  There are 3 items defined, 4 get rendered in the list.  The first three have a template and the last is incorrect.  This was working in one of the most recent kendo releases we were using.  Now it is broken again.

**Comment by amopitt** [comment] 2015-04-07 12:49
Eh, disregard.  If I update the sources to use 2015.1.318 it works fine.  Not sure what's going on in our code.  Nevermind.

**Comment by ggkrustev** [comment] 2015-04-07 19:44
The issue is related to #665. It is addressed and the fix will be included in the next service pack.

**Comment by amopitt** [comment] 2015-04-07 19:52
Good news, thank you
