### ISSUE TITLE
Sticky menus in Grid

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-ui-core#3889] opened 2018-01-03 07:57 UTC
### Description
The menus in the Grid do not disappear on mouseout, remaining in place. Not reproducible 100% of the time.
### Demonstration
![grid_sticky_menu_1](https://user-images.githubusercontent.com/5155721/34512579-15acf804-f06c-11e7-8a26-8d9bb80f3a32.gif)
### Dojo
Can be reproduced in [this dojo](http://dojo.telerik.com/EhOWa).
### Scope
Reproducible in Chrome, Firefox, IE11

_Reported in ticket 1143069._

**Comment by eyupyusein** [comment] 2022-02-19 10:12
Might be related to: https://github.com/telerik/kendo-ui-core/issues/6680

**Comment by sspasova** [comment] 2023-11-10 16:23
Closing this because the issue is no longer reproducible. I've tested it with Kendo version 2023.3.1010

**Closed by sspasova** 2023-11-10 16:23 UTC
Labels: Bug, SEV: Low, C: Grid, jQuery
