### ISSUE TITLE
Invisible Window Resizes incorrectly after using setOptions() followed by open()

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#4242] opened 2018-05-22 15:53 UTC
### Bug report

Before opening an invisible Kendo Window, if the window is configured using setOptions, the window will be resized incorrectly.  When a user tries to resize the window with the mouse, the appearance of the Window is distorted.

### Reproduction of the problem
[Invisible Window Open After SetOptions 2018.2.516 - Progress Kendo UI Dojo](http://dojo.telerik.com/edAZALeF)
1.  Notice the size of the Window.
2.  Attempt to resize from the bottom of the window.

Here is a [short screencast of the behavior.](https://www.screencast.com/t/6qXDLAGh2jU)

### Expected/desired behavior
Please take a look at [this Progress Kendo UI Dojo with the same approach for version 2018.1.117.](http://dojo.telerik.com/adEGaVuK)

### Environment

* **Kendo UI version:** 2018.2.516
* **jQuery version:** 1.12.x
* **Browser:** All

**Comment by InciteGmbH** [comment] 2018-06-07 06:42
Hi

Could you please set this bug on a higher priority please. It would be great if we can get it on the next internal build.

Thanks a lot.

Marc Huber

**Comment by joneff** [comment] 2018-10-08 08:01
The issue is related to how we measure the title.

This will be fixed for the the upcoming SP.

**Comment by joneff** [comment] 2018-10-14 19:39
The only side effect left is when trying to set the title of a hidden window and will take care of that shortly.

**Comment by Dimitar-Goshev** [comment] 2018-11-12 09:43
Reported title() method issue in ticket ID 1350275 - [Dojo](https://dojo.telerik.com/AziXUXUn). Click on Open with new title button for reproduction.

**Closed** 2018-11-21 12:46 UTC
Labels: Appearance, Bug, C: Window, Kendo2, Next LIB, Priority 5
