### ISSUE TITLE
Documentation Error in tabstrip reload method

### ISSUE THREAD

**Issue by EduVencovsky** [telerik/kendo-ui-core#4928] opened 2019-03-20 11:55 UTC
In the [this article](https://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip/methods/reload) of documentation there is an error.

`Uncaught ReferenceError: tabStrip is not defined at line 11`

![image](https://user-images.githubusercontent.com/37600269/54682276-419ca400-4aed-11e9-8445-62e888e60b57.png)

This is a simple error to fix, but I'm new to github and not sure how pull requests work but here is how to fix it.

The problem is that `tabStrip` isn't defined so just need to add `var tabStrip = `.

Wrong
![image](https://user-images.githubusercontent.com/37600269/54682478-c8ea1780-4aed-11e9-858a-8738a16431f7.png)

Correct 
![image](https://user-images.githubusercontent.com/37600269/54682428-ace67600-4aed-11e9-9efc-2fc3c6d31f85.png)

**Comment by Dimitar-Goshev** [comment] 2019-04-24 05:52
@EduVencovsky Thank you for your feedback. The issue is fixed now.

**Closed** 2019-04-24 05:51 UTC
Labels: C: TabStrip, Documentation, Kendo2
