### ISSUE TITLE
Gantt shrinks its treelist text to fit column's width on PDF export in IE and Edge 

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#1868] opened 2016-07-01 10:24 UTC
### Reproduction of the problem
1. Go to [Gantt PDF Export demo](http://demos.telerik.com/kendo-ui/gantt/pdf-export)
1. Export to PDF

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/47999728-1ef48a80-e10c-11e8-824f-4d99698b06cc.png)

### Expected/desired behavior
Text is cut, as it is not visible in the browser as well:
![image](https://user-images.githubusercontent.com/6614183/47999798-4d726580-e10c-11e8-9201-79dce11624df.png)

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [IE 11, Edge 40]

**Comment by magnus-meridies** [comment] 2019-01-18 11:23
Any news when this bug is fixed?

**Comment by magnus-meridies** [comment] 2019-03-21 07:16
Any feedback on this?

**Comment by Dimitar-Goshev** [comment] 2019-04-02 10:08
@magnus-meridies The issue is fixed and the fix will be included in the next latest internal build as well as in R2 2019.

**Closed by Dimitar-Goshev** 2019-04-02 10:08 UTC
Labels: Bug, C: Gantt, F: PDF Export, Kendo2, Next LIB, Priority 1, SEV: Low, Triaged
