### ISSUE TITLE
Kendo Multiselect dropdown selection loss in filtering

### ISSUE THREAD

**Issue by aryanisml** [telerik/kendo-ui-core#4068] opened 2018-03-09 07:05 UTC
Using Angular JS 1.5 and Kendo UI Jquery
Created the wrapper component on Kendo Multi Select drop down. Provided the checkbox selection of each item.
Currently the requirement is to load more than 100 records in drop down so implemented the virtualization. We fetched more than 100 records from server and binded to dropdown, using virtualization scroll the records. When we click on select check box the record is selected. however if we search in drop down the record which selected is showing unchecked.
currently not using serverfiltering, we using filter : contains.
Before implementation of virtualization the functionality working fine.

**Comment by zdravkov** [comment] 2018-03-13 10:29
The issue is not quite clear from the provided description. Would you please try to isolate it in a [dojo page](http://dojo.telerik.com/) so we could observe it locally?

**Comment by Dimitar-Goshev** [comment] 2018-03-13 12:41
@aryanisml This is a known issue - [Virtualized MultiSelect doesn't add k-state-selected to filtered items](https://github.com/telerik/kendo-ui-core/issues/2661). I am closing this one as duplicate.

**Closed by Dimitar-Goshev** 2018-03-13 12:41 UTC
Labels: Bug, C: MultiSelect, Kendo2
