### ISSUE TITLE
The Spreadsheet custom editor button is not visible on cell belonging to the last frozen column

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4090] opened 2018-03-16 07:34 UTC
### Bug report
The Spreadsheet custom editor button is not visible on cell belonging to the last frozen column.

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/exIGoyON/2);
* Click in cell B1 or B2 - the custom editor button will not be visible even if the place, where it should be can be clicked. The editor will just flicker for a second;

**Comment by mishoo** [comment] 2018-07-03 12:45
Closing as duplicate of #3862.

**Closed by mishoo** 2018-07-03 12:45 UTC
Labels: Appearance, Bug, C: Spreadsheet, Kendo2, SEV: Low
