### ISSUE TITLE
Toolbar show and hide methods toggle items in both the container and overflow popup

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5115] opened 2019-06-17 10:20 UTC
### Bug report
Toolbar's show() and hide() method toggle items visibility in the overflow popup and the Toolbar container. A selector is used as a parameter to determine which button to be controlled. Although the id selector for a button outside the overflow is different than the id selector of the same button when in overflow, the methods would control the visibility of the button in both cases. This contradicts to the expected behavior - targeting a button through its selector.

### Reproduction of the problem
Case 1: [https://dojo.telerik.com/aXEyIrEW/14](https://dojo.telerik.com/aXEyIrEW/14)

The 'Button' is visible in both the Toolbar and the overflow popup initially.

Case 2: [https://dojo.telerik.com/erEnafir/39](https://dojo.telerik.com/erEnafir/39)

When the Toolbar is resized so that the 'Dashboard' button is not visible, the 'Dashboard' button is also not visible in the overflow popup.

### Current behavior

Toolbar's show() and hide() method toggle items visibility in the overflow popup and the Toolbar container. 

### Expected/desired behavior

Using the show() and hide() methods should provide a more consistent way of showing and hiding items in the Toolbar container or the overflow popup.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by Juveniel** [comment] 2019-06-18 07:28
The documentation for the [show()](https://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar/methods/show) and [hide()](https://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar/methods/hide) methods currently indicates that using the methods should show/hide the specified item in both the ToolBar container and the overflow popup if resizable is set to true. 

This behavior could be improved further to allow hiding only the specified element. Thus, a further investigation is needed in order to verify if such a change should be introduced.

**Comment by Dimitar-Goshev** [comment] 2022-03-11 14:24
I am closing this as the current behavior matches the expected behavior per documentation and it is not a bug. A feature request item may be logged in Kendo UI for jQuery feedback portal for changing this behavior.

**Closed by Dimitar-Goshev** 2022-03-11 14:24 UTC
Labels: Bug, C: ToolBar, SEV: Medium, jQuery2, FP: Unplanned
