### ISSUE TITLE
Grid - exporting to PDF with nested TABLE elements in cells breaks the layout

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#4927] opened 2019-03-20 08:07 UTC
### Bug report

When the PDF export **paperSize** is set, when there are nested TABLE elements in the Grid cells, the layout breaks on export.

### Reproduction of the problem
[https://dojo.telerik.com/UzafiBed/2](https://dojo.telerik.com/UzafiBed/2)
The exported file will have broken structure for the cells

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by sspasova** [comment] 2023-11-27 10:34
The issue is fixed with Kendo UI version 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/uNaQafOY

**Closed by sspasova** 2023-11-27 10:34 UTC
Labels: Bug, SEV: Low, C: Grid, F: PDF Export, jQuery, Triaged
