### ISSUE TITLE
Virtualized DropDownList does not change its value upon filtering and press Tab/Enter

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6363] opened 2021-04-05 13:44 UTC
### Bug report
Virtualized DropDownList does not change its value upon filtering and press Tab/Enter. This is jQuery 3 specific issue. In could not be replicated with jQuery 2 and jQuery 1.

### Reproduction of the problem
* run the following Dojo: https://dojo.telerik.com/IrESEJaf/4
* Click the DDL to open its pop-up
* Type "hen" to filter its values
* Press Tab
* Notice that in the change event the selected value in the DropDownList is not the one that matches the displayed item. It remains the previously selected ("10248")

### Expected/desired behavior
The value should already be updated when the change event fires.

### Environment
* **Kendo UI version:** 2021.1.330
* **jQuery version:** 3*
* **Browser:** [all]

**Comment by sspasova** [comment] 2024-01-02 13:47
I am closing this issue because it is no longer reproducible using Kendo UI 2023.3.1114 and Chrome. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/aReJoLAN

**Closed by sspasova** 2024-01-02 13:47 UTC
Labels: Bug, C: DropDownList, SEV: Medium, jQuery, FP: Unplanned
