### ISSUE TITLE
Spreadsheet steals the focus from the focused element when keyboard down / up arrow is pressed

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3315] opened 2017-06-12 13:23 UTC
### Bug report
Spreadsheet steals the focus from the focused element when the down / up arrow is pressed. This is a browser related bug, that could be observed in Chrome. In FireFox pressing the arrows will have no effect. IE and Edge behave as expected - the focused container is being scrolled down / up.

It also may be related to [the following issue](https://github.com/telerik/kendo/issues/6953).

### Reproduction of the problem
* Run the following [Dojo](http://dojo.telerik.com/EQewu/15);
* Press Up or Down arrow to navigate - the focus will be removed from the list of Buttons;
* Press Up or Down arrow a second time - the selection in the Spreadsheet will be moved to the respective cell.

### Environment
* **Browser:** [ Chrome XX]

**Comment by Dimitar-Goshev** [comment] 2017-07-21 13:01
When tested with the reproduction sample, the scrollable container is scrolled in Firefox as well on my side. After the fix above is applied, the issue is resolved in Chrome as well.

**Closed by Dimitar-Goshev** 2017-07-21 13:01 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: Low
