### ISSUE TITLE
Window content overlaps the bottom border after calling setOptions() followed by open()

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4349] opened 2018-07-02 11:59 UTC
### Bug report

Window content overlaps the bottom border after calling setOptions() followed by open() 
div.k-window.k-widget is overlapped by div.k-window-content.k-content

### Reproduction of the problem
https://dojo.telerik.com/ULIJUjiS/4

### Current behavior
The content overlaps the bottom border 

### Expected/desired behavior
The content is not overlapping the window wrapper

### Environment
* **Kendo UI version:** 2017.2.504

The problem is reproducible since R2 2017
Workaround: Call setOptions() after open()

**Comment by Dimitar-Goshev** [comment] 2018-08-21 10:10
Closing this one as s duplicate of the issue related above - https://github.com/telerik/kendo-ui-core/issues/4242

**Closed by Dimitar-Goshev** 2018-08-21 10:10 UTC
Labels: Appearance, Bug, C: Window, Kendo2, Priority 5
