### ISSUE TITLE
Text in Spreadsheet wrapped cells is overlapped when exported to PDF in Safari

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6417] opened 2021-05-12 13:38 UTC
### Bug report

When Spreadsheet that contains wrapped cells is exported to PDF, the text of the wrapped cells is overlapping

### Reproduction of the problem
1. Open the [Demo](https://demos.telerik.com/kendo-ui/spreadsheet/index) in Safari
2. Write a long text in a cell and select the 'Wrap text' option, so the text to be wrapped.
3. Export to PDF

### Current behavior
In the PDF file the text in the cell is overlapped 
![image](https://user-images.githubusercontent.com/14364791/117983585-c5eeb880-b33f-11eb-8baf-f239bf733d6c.png)

### Expected/desired behavior
The text in the wrapped cell should not be overlapped when exporting to PDF. 

### Environment

* **Kendo UI version:** 2021.2.511
* **Browser:** [Safari]

**Comment by sspasova** [comment] 2023-12-15 07:52
Closing this issue because it is no longer reproducible using Kendo UI version 2023.3.1114. Tested with Safari Version 17.1.2 (19616.2.9.11.12)

**Closed by sspasova** 2023-12-15 07:52 UTC
Labels: Bug, SEV: Low, C: Spreadsheet, jQuery, FP: Unplanned, Triaged
