### ISSUE TITLE
RadioGroup checked radio button is unchecked when nested in a TileLayout and the tile is reordered

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7002] opened 2022-08-25 16:15 UTC
### Reproduction of the problem
Dojo example: https://dojo.telerik.com/@sspasova/iGAhIdoT
1. Drag tile A and drop it after tile B

### Current behavior
The checked radio button of the RadioGroup appears unchecked. 

### Expected/desired behavior
The RadioGroup check state remains the same. 

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by iordanGrancharov** [comment] 2024-11-07 10:08
This is not a bug related to the Kendo component. 

The drag hint is an element clone of the dragged target. The checked state of the radio button disappears because when the hint is created, the cloned inputs have the same `name` attribute as the original ones, which tricks the browser to consider them as part of the radio-group. Since there can be only one checked element in a radio-group, the checked state is transferred to the cloned element.

Check this Dojo that showcases the issue with a normal radio-group: https://dojo.telerik.com/aAfAfmQz

**Closed by iordanGrancharov** 2024-11-07 10:08 UTC
Labels: Bug, SEV: High, jQuery, FP: Unplanned, C: TileLayout, C: RadioGroup
