### ISSUE TITLE
Showing horizontal scrollbar after pasting text in Editor in RTL mode in Firefox

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#3957] opened 2018-02-01 09:41 UTC
### Bug report
Ticket 1151167 ID

### Reproduction of the problem
1. Open the folwoing sample in Firefox https://dojo.telerik.com/iPoHOxiC
2. Paste some text in the Editor

### Current behavior
![2018-02-01_1138](https://user-images.githubusercontent.com/4389590/35671566-821a13a2-0744-11e8-82ac-5b04f6985cce.png)

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** Firefox

**Comment by Juveniel** [comment] 2019-10-14 10:44
This issue is not reproducible with the latest release ([Dojo example](https://dojo.telerik.com/iPoHOxiC/5)). The issue is probably related to a specific Firefox version.

Closing.

**Closed by Juveniel** 2019-10-14 10:44 UTC
Labels: Appearance, Bug, C: Editor, Kendo2, SEV: Low, Triaged
