### ISSUE TITLE
Memory leak issues with Kendo Grid

### ISSUE THREAD

**Issue by ElsaZap** [telerik/kendo-ui-core#4605] opened 2018-10-22 16:12 UTC
### Bug report

We are a company using Kendo UI Grid for their application. We found

 a memory leak issue with Kendo UI Grid.

### Reproduction of the problem
Use Kendo UI Grid
Launch the application from User Interface
Open the Task manager from Chrome
Take the mesure of the memory used before navigate in the application : 170 896 Ko memory used
Then open the menu where the grid Kendo is implemented
Open the task manager : 340 696 Ko memory used
Then use the sorts in the grid, click on the next page
Open the task manager : 454 116 ko memory used.

We can see that after changing pages (page size = 25) a few times, memory is not deallocated resulting in important memory leaks.
When the memory of the navigator is saturated the application is crashing.

### Code sample :
** Import list

import '@progress/kendo-ui';
import '@progress/kendo-theme-material/dist/all.css';
import { Grid, GridColumn, GridInstaller } from '@progress/kendo-grid-vue-wrapper'; 

** Instantiation

 new kendo.data.DataSource({
  transport    : {
    read : (options) => {
      itemIndex = 0;

      return this.getData(options);
    }
  },
  schema       : {
    data  : ({ resources }) => resources.map(copy),
    total : ({ total }) => {
      data.rowCount = total;

      return total;
    }
  },
  page         : this.table.options.page,
  pageSize     : DEFAULT_PAGE_SIZE,
  serverPaging : true
}); 

** Template

<kendo-grid class="firco-table__grid"
            v-bind:data-source="dataSource"
            v-bind:pageable="pageable">
    <kendo-grid-column v-for="column in columns"
                      v-bind:key="column.field"
                      v-bind:template="itemTemplate"
                      v-bind:headerTemplate="headerTemplate"
                      v-bind="column">
    </kendo-grid-column>
</kendo-grid> 

### Expected/desired behavior

The application should not crash and Kendo UI should not cause performance issues

### Environment

* **Kendo UI version:** 
"@progress/kendo-grid-vue-wrapper": "2018.1.313",
"@progress/kendo-theme-material": "^1.3.0",
"@progress/kendo-ui": "^2018.3.911", 
* **jQuery version:** None
* **Browser:**  [ Chrome 69.0.3497.100 | Firefox 62.0.3 | IE 11.1088.15063.0 ]

**Comment by Iankodj** [comment] 2018-10-24 10:50
@ElsaZap typically, the kendo-grid-column component is not designed to be used with the v-for directive. 

However, I tested similar case locally and I was unable to examine any performance issues. 

Can you provide a sample that will enable us to reproduce the issue described? With the code provide it is not clear how data is loaded and whether there are other dynamic changes to the Grid component that cause a recursive loading of data.

**Comment by zdravkov** [comment] 2019-02-01 09:21
We are closing the issue because there is not enough information to replicate it locally.

**Closed by zdravkov** 2019-02-01 09:21 UTC
Labels: Kendo1, Kendo2, S: Wrappers (Vue)
