### ISSUE TITLE
The border styles are not correctly applied on merged cell.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2224] opened 2016-09-27 11:14 UTC
### Bug report

The border styles are not correctly applied on merged cell.
### Reproduction of the problem

The issue can be observed in the following Dojo example: http://dojo.telerik.com/UpUGe

Notice that the right border is not applied. 

Additionally, if the same sheet is exported the borders are visible in the _exported_ Excel.
### Environment
- **Browser:** all

**Comment by mishoo** [comment] 2016-09-27 15:24
Workaround is to set the `right` border last: http://dojo.telerik.com/@mishoo/ahoMO

When the `left` border is set on a cell, the `right` border of the previous cell is cleared.  This appears to be by design (see [here](https://github.com/telerik/kendo/blob/master/src/spreadsheet/range.js#L118) and [here](https://github.com/telerik/kendo/blob/master/src/spreadsheet/range.js#L24)).  Similar happens with `top` and `bottom`.

Indeed, this code appears to be buggy with merged cells, will investigate further.

**Comment by jwbqv** [comment] 2016-11-30 12:27
Are there any updates on this issue?   Thank you.

**Comment by gyoshev** [comment] 2016-12-09 08:28
@mishoo I think the reset of sibling borders is an artifact of the previous (table-based) rendering. It made borders behave predictably, and also fixed export issues when you set the same border through different cells. If these scenarios are covered, the mentioned code can be deleted.

**Comment by jwbqv** [comment] 2017-01-18 18:51
Are there any updates on this issue? Thank you.

**Comment by mishoo** [comment] 2017-01-19 18:19
I think the implementation for this is unnecessarily complex.  We hold 4 property bags (border left/right/top/bottom), when it clearly doesn't make sense to have two different borders between adjacent cells.  2 would suffice (vertical borders and horizontal borders).

Unfortunately, as things usually go, it takes more time to simplify things than to make 'em simple in the first place.  Hard to estimate how long this would take, but it does seem like a non-trivial change.  I feel up to the task, if you guys think it's worth the time effort.

**Comment by mishoo** [comment] 2017-03-06 09:15
I pushed a pretty large refactoring of border rendering.  Reopening for QA.

**Closed** 2017-03-14 15:31 UTC
Labels: Bug, C: Spreadsheet, In Testing, SEV: Medium
