### ISSUE TITLE
DateRangePicker. Cannot set the Date Range Picker value with Year/Decade depth and start options.

### ISSUE THREAD

**Issue by bloodlanser** [telerik/kendo-ui-core#4988] opened 2019-04-15 13:12 UTC
### Bug report

Cannot apply Date Range Picker value if year/ decade selected as **depth** and **start** options.

### Reproduction of the problem
https://dojo.telerik.com/axiMADUh

### Expected/desired behavior
Selected Range is applied.

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by matanasov** [comment] 2019-04-23 12:35
Duplicate of https://github.com/telerik/kendo-ui-core/issues/4975

**Closed by matanasov** 2019-04-23 12:35 UTC
