### ISSUE TITLE
Horizontal scroll jump from left to right when click cell to edit mode.

### ISSUE THREAD

**Issue by AdamTur** [telerik/kendo-ui-core#5202] opened 2019-08-01 10:37 UTC
### Describe the bug
Problem is with KendoGrid in on when we have many columns (horizontal scroll  in grid is active).

Click on the last cell in row to enable edit mode (only part of cell is visible).

![image](https://user-images.githubusercontent.com/53558224/62278585-aa573e00-b448-11e9-9400-d80b8e52fb93.png)

After that scroll with whole grid quickly go to the left and after that return to good scroll position.
After that we can click on random cells to enable edit mode and we have the same problem.
 
### Enviroment
IE 11

### Expected behavior
After enable edit mode in cell, scroll cannot jump to the start position and return, but must have  the same behaviour like in other browsers. Also cell (only part of cell is visible) in edit mode have to be whole visible after click.

**Comment by dmanova** [comment] 2019-08-06 08:34
Closed as duplicate of: #4620

**Closed by dmanova** 2019-08-06 08:34 UTC

**Comment by AdamTur** [comment] 2019-08-27 07:26
Please look once again at this task. I have updated this issue because it concerns Kendo for Angular
