### ISSUE TITLE
Tooltip hides its target when it has no width set and its content wraps

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#4619] opened 2018-10-26 09:12 UTC
### Bug report

In some cases, the Tooltip shows over its target when the widget has no specific width set and its text wraps.

The problem is reproducible if showing a tooltip on the Chart labels like shown in this Dojo:
[https://dojo.telerik.com/UJEdEyeD](https://dojo.telerik.com/UJEdEyeD)

### Reproduction of the problem
Hover the Chart category labels (Problem is sometimes not reproducible in Chrome (based on screen resolution) but is always reproducible in IE))

### Current behavior
The first time the labels are hovered, the tooltip covers the label text.

### Expected/desired behavior
The tooltip should display above the labels.

The issue is reproduced only with the Less themes. It works as expected with the Sass themes.

### Environment

* **Kendo UI version:** 2018.3.1017

Reported in: 1347920

**Comment by Dimitar-Goshev** [comment] 2018-10-29 09:41
Duplicate of https://github.com/telerik/kendo-ui-core/issues/3733

**Closed by Dimitar-Goshev** 2018-10-29 09:41 UTC
Labels: Bug, C: Tooltip, Kendo2, Priority 1, SEV: Low
