### ISSUE TITLE
In Diagram selectable.key option does not change the way shapes are being selected

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2451] opened 2016-11-18 13:43 UTC
### Bug report

selectable.key should enable you to add a key for a selection keyboard shortcut: http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/diagram#configuration-selectable.key. 

### Reproduction of the problem
Test this configuration here and try selecting:
http://dojo.telerik.com/iHugi

Selection is enabled no matter the key defined. 

### Current behavior
http://dojo.telerik.com/iHugi

### Expected/desired behavior
http://dojo.telerik.com/evequg

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** 1.9.1
* **Browser:** [all]

**Comment by nlazarov** [comment] 2017-04-06 10:38
The described change is the expected behavior.

The `selectable.key` option defines the meta key to use when selecting shapes using the visual selection, i.e. drawing a rectangle around multiple shapes. This option will not change the behavior of click/tap on a shape.

I have updated the documentation API reference on [selectable.key](http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/diagram#configuration-selectable.key) and [pannable.key](http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/diagram#configuration-pannable.key) accordingly.

Since this is not a bug I am closing this issue with won't fix tag.

**Closed** 2017-04-06 10:38 UTC
Labels: Bug, C: Diagram, SEV: Critical, Won't Fix
