### ISSUE TITLE
Grid InCell editor flickers and exits edit mode immediately with jQuery 3.1.1

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2554] opened 2016-12-21 12:07 UTC
### Reproduction of the problem
When using a widget as an editor in Grid with InCell EditMode, you are unable to edit the cell.
[Grid - InCell Editing using MultiSelect with ServerFiltering.zip](https://github.com/telerik/kendo-ui-core/files/666272/Grid.-.InCell.Editing.using.MultiSelect.with.ServerFiltering.zip)
[screencast](http://screencast.com/t/qT7yYCvyG8V7)

### Current behavior
[screencast](http://screencast.com/t/qT7yYCvyG8V7)

### Expected/desired behavior
[screencast](http://screencast.com/t/fehiaQOITqeR)

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 3.1.1
* **Browser:** [all] 

Related item:
[Grid closes an opened cell for editing automatically if jQuery version is 3.1.1](https://github.com/telerik/kendo/issues/6604)

**Comment by BobBonser** [comment] 2017-01-30 16:15
This problem needs fixed asap.  It is holding up a release to production for us and has been open for well over a month now.  Come on Telerik, get on the ball!

**Comment by wazahuis** [comment] 2017-02-15 21:33
I concur I need this fixed asap.  Too much time to roll everything back to jquery 1.12.

**Comment by msereda** [comment] 2017-02-16 14:26
+1 to getting it fixed asap.  We have annoyed users at our company due to bugs in the last release (that were fixed in 2017R1), but until these jQ3 bugs are fixed (this and #2493 ) we can't upgrade Kendo or they'll be even more annoyed at us due to new bugs.

**Comment by hadjieva** [comment] 2017-02-16 16:01
We were able to isolate the cause of the problem, which is due to the changed behavior of the jQuery(callback). A fix that resolve the closing of the cells issue is currently being tested.

**Closed** 2017-02-23 16:22 UTC
Labels: Bug, C: Grid, S: Wrappers (ASP.NET MVC), SEV: Medium
