### ISSUE TITLE
Borders of minorTick slots are incorrectly styled for cells after the first one

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-ui-core#1886] opened 2016-07-06 10:50 UTC
Borders of minorTick slots are incorrectly styled for cells after the first one. This can be observed in the following demo:
-  [http://dojo.telerik.com/eDese](http://dojo.telerik.com/eDese)

![image](https://cloud.githubusercontent.com/assets/2195951/16615609/8debc6fa-4380-11e6-8284-8be1414679b4.png)

**Comment by Dimitar-Goshev** [comment] 2018-08-13 13:50
Closing it as duplicate of https://github.com/telerik/kendo-ui-core/issues/2671

**Closed by Dimitar-Goshev** 2018-08-13 13:50 UTC
Labels: Bug, C: Scheduler, Kendo2, SEV: Low
