### ISSUE TITLE
ImageEditor throws a javascript exception on resizing and setting image width or height to 0

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6659] opened 2021-12-13 16:19 UTC
### Reproduction of the problem
Reproducible in the demos: [https://demos.telerik.com/kendo-ui/imageeditor/index](https://demos.telerik.com/kendo-ui/imageeditor/index)
1. Open the browser's devtools console
2. Click the "Resize" tool in the ImageEditor's toolbar. 
3. Change the image Width or Height value to 0 and blur the input. 

### Current behavior
A js exception is thrown after blurring the input:
**Uncaught RangeError: Maximum call stack size exceeded**

Subsequently, on attempting to enter a valid width/height value, the same exception is thrown and resizing the image becomes impossible.

### Expected/desired behavior
No js exceptions are thrown.

### Environment

* **Kendo UI version:** 2021.3.1207
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by sspasova** [comment] 2024-02-21 12:41
I am closing this issue because it is no longer reproducible using Kendo UI 2024.1.130.

**Closed by sspasova** 2024-02-21 12:41 UTC
Labels: Bug, SEV: Medium, jQuery, FP: Unplanned, C: ImageEditor, Triaged
