### ISSUE TITLE
The Grid shown multiple groups with the same name when serverPaging is used.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3806] opened 2017-11-29 07:07 UTC
### Bug report

The Grid shows multiple groups with the same name when serverPaging is used.

### Reproduction of the problem

The issue can be observed at the following Dojo: http://dojo.telerik.com/aJUyU

Collapse the items and notice how the items with value true are divided into multiple groups.

### Environment

* **Browser:** [all]

**Comment by Alex-Bubblemaster** [comment] 2017-12-18 16:21
I believe this is because of the endless scroll. Here is the same Dojo without the endless scrolling functionality and it works correctly - [http://dojo.telerik.com/@bubblemaster/eCeseh](http://dojo.telerik.com/@bubblemaster/eCeseh)

**Comment by ag-petrov** [comment] 2017-12-20 09:32
@Alex-Bubblemaster is right. The described behavior is caused by the way the grid from the dojo is configured. When **serverPaging** is enabled without **serverGrouping** the datasource will extract only a subset of items and group them on the client. In order to correct this behavior one should enable **serverGrouping**(have in mind that the service should be configured to group the items) as mentioned [here ](https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#endless-scrolling)or bind the grid to local data as shown [here](https://demos.telerik.com/kendo-ui/grid/endless-scrolling-local).

**Comment by simonssspirit** [comment] 2018-01-04 13:23
After additional tests, the example is not working with serverGrouping as well when the ToDataSourceResult method is used.

Re-opening the issue.

**Comment by simonssspirit** [comment] 2018-02-08 11:29
raising the priority

**Comment by TsvetinaIvanova** [comment] 2018-02-12 15:15
There is also an issue with group footers.
[http://dojo.telerik.com/@tsveti/oZomE/2](http://dojo.telerik.com/@tsveti/oZomE/2)

Collapse group footer until the Grid makes a page request (collapse until Supplier ID : 7). When the Grid loads, there are duplicate footers at the end of the first page.

Reported in: 1151515

**Comment by TsvetinaIvanova** [comment] 2018-02-20 14:55
The multiple groups problem is also reported in 1153386.

**Comment by hadjieva** [comment] 2018-02-28 16:29
The problem with multiple group footers is also reported in 1152921

**Comment by ag-petrov** [comment] 2018-03-12 14:17
The problem occurs when server grouping is used. Currently there are two ways one can enable such behavior. In MVC, use server operations for the grid and force the controller action to use our ToDataSourceResult method or create your own service with custom grouping and return the data in the format explained [here](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/configuration/schema#schema.groups). Both cases are affected by my commit and we will consider the issue as closed as soon as QAs verify the fix.

**Closed** 2018-03-15 15:07 UTC
Labels: C: Grid, Kendo1, Priority 4, SEV: Medium
