### ISSUE TITLE
Opening a valid PDF file after trying to open a corrupted PDF file in the PDF Viewer throws a JavaScript error

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6604] opened 2021-10-14 11:10 UTC
### Bug report

Opening a valid PDF file after trying to open a corrupted PDF file in the PDF Viewer throws a JavaScript error. As a result opening a valid PDF file is not possible.
```
Uncaught TypeError: Cannot read properties of null (reading 'sendWithStream')
    at PDFPageProxy.streamTextContent (api.js:1114)
    at PDFPageProxy.getTextContent (api.js:1132)
    at init._renderTextLayer (kendo.all.js:170740)
    at init.render (kendo.all.js:170727)
    at kendo.all.js:171384
    at Array.forEach (<anonymous>)
    at r.exec (kendo.all.js:171381)
    at init.execute (kendo.all.js:171959)
    at init.zoom (kendo.all.js:171949)
    at init.fromFile (kendo.all.js:172026)
```
### Reproduction of the problem
1. Navigate to the [PDFViewer Demo](https://demos.telerik.com/kendo-ui/pdfviewer/index)
2. Open a corrupted PDF file, for example [CorruptedPdfFile.pdf](https://github.com/telerik/kendo-ui-core/files/7345450/CorruptedPdfFile.pdf)
3. Try to open a valid, working PDF file 

[Screencast](https://www.screencast.com/t/VkTEXWZdRyT)

### Current behavior
A valid PDF file cannot be opened after a corrupted file was loaded

### Expected/desired behavior
It should be possible that a valid PDF file can be opened after a corrupted file has failed to be opened.

### Environment

* **Kendo UI version:** 2021.3.914
* **Browser:** [all]

**Comment by sspasova** [comment] 2023-12-19 13:50
I am closing this issue because I cannot reproduce it using Kendo UI version 2023.3.1114.

**Closed as completed by sspasova** 2023-12-19 13:50 UTC
Labels: Bug, SEV: High, jQuery, FP: Completed, C: PDFViewer
