### ISSUE TITLE
display: flex on Body tag causes DropDownList to instantly close when in a scrollable area that is scrolled

### ISSUE THREAD

**Issue by Skintkingle** [telerik/kendo-ui-core#1275] opened 2015-11-24 14:52 UTC
When the body tag has applied the display: flex; CSS attribute and the dropdownlist is in a container that is set to overflow: auto; or overflow: scroll (or any x/y specific alternative) and you scroll to anywhere that isn't the top, the dropdown list will retract as soon as it opens. this happens only on firefox. 

Issue exampled here: http://dojo.telerik.com/aWeYE/2
Issue workaround here: http://dojo.telerik.com/aWeYE/3

**Comment by ggkrustev** [comment] 2015-12-10 17:22
Hi @Skintkingle,

After extensive investigation, we found out that the cause of the issue is due to outerHeight/outerWidth calls done during popup wrapping:
- https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L1689

Basically, when we check the outer height/width of the popup element, browser triggers `scroll` event of the scrollable element. This forces the popup to close, as this is the desired behavior (close the popup on scroll).

It seems that setting `display:flex` to the BODY element breaks Firefox somehow. Here is a test demo that demonstrates the issue:
- http://runner.telerik.io/fullscreen/aWeYE/5

As you can see, the problem is not related to Kendo UI by any means, but rather is browser behavior/bug. I am afraid that there is no fix for this behavior that we can apply on our side.

The solution is to avoid setting display:flex to the body or wrap the content in div, as you do.

**Closed by ggkrustev** 2015-12-10 17:22 UTC
Labels: C: ComboBox, C: DatePicker, C: DateTimePicker, C: DropDownList, C: MultiSelect, SEV: Low, Wontfix
