### ISSUE TITLE
Spreadsheet toolbar dropdowns do not popup on iOS (Chrome and Safari)

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#2138] opened 2016-09-08 14:14 UTC
### Bug report

Spreadsheet toolbar dropdowns do not popup in Chrome on iOS

### Reproduction of the problem

Download and install [Chrome on iOS](https://itunes.apple.com/gb/app/chrome-web-browser-by-google/id535886823?mt=8) + _Now also in iOS Safari, so no need to download Chrome for iOS to reproduce._

Open the [Spreadheet demo](https://demos.telerik.com/kendo-ui/spreadsheet/index)

Click the color, backround and border buttons. The corresponding popups do not open.

Versions: latests as of 08-Sep-2009.

**Comment by underlog** [comment] 2016-09-08 18:32
Most likely, this means that all our popups don't work in Chrome on iOS. This sounds strange, to be honest. Chrome wraps the webkit view, same one that Safari uses, and we work there. @ggkrustev - have you encountered such thing?

**Comment by jlchereau** [comment] 2016-09-08 18:36
The demos of ColorPicker, DataPicker and DropdwonList work.

**Comment by ggkrustev** [comment] 2016-09-14 09:26
@underlog, I haven't. It seems that the popup is opened, but misplaced due to some specifics of Chrome for iOS browser. We will further investigate the case, but probably the browser reports incorrect offset information.

**Comment by jlchereau** [comment] 2016-09-21 14:47
I am surprised I did not realize in the first place, but this also affects iOS Safari.

**Comment by jlchereau** [comment] 2016-10-13 17:48
Will it make its way to 2016.3.SP1? It is very painful for our iPad users.

**Comment by ggkrustev** [comment] 2016-10-14 16:40
We were able to track down the cause of this issue and a fix is on its way. It will be included in the next service pack (2016.3.SP1).

**Closed** 2016-10-14 16:44 UTC
Labels: Bug, C: Spreadsheet, SEV: Medium
