### ISSUE TITLE
Parent task collapses after preventing changes in a Child Task in the TreeList within the save event

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6814] opened 2022-04-26 08:30 UTC
### Bug report

~~With e.preventDefault in the save event of the Gantt, the TreeList becomes unresponsive when blurring a task field.~~

With e.preventDefault in the save event of the Gantt, the previously expanded parent task collapses. That is because the `dataBound` is triggered.

**Regression introduced with  version 2020.3.915**

### Reproduction of the problem

1. Open this example - https://dojo.telerik.com/aWaHadaL/19
2. Add a child task under Task 1.
3. Double click on a field of the Child task in the TreeList.
4. Edit the field.
5. Blur the edit form

### Current behavior

The parent task collapses ~~and becomes unresponsive~~

### Expected/desired behavior
The parent task should not collapse ~~and become unresponsive~~

### Environment

* **Kendo UI version:** 2022.1.412
* **Browser:** [all]

**Comment by veselints** [comment] 2022-05-02 10:16
The `defaultValue` field in the `schema.model.fields` should always have the same value for all items in the DataSource. That default value signifies that a task has been created without being synced with the remote (if present). If the scenario requires an id for the task to be generated on the client, that should be done in the `add` event of Gantt instead:
```js
add: (e) => {
  e.task.set('ID', CreateGuid());
},
```

Moreover, the type of the id field value must be equal for all items in the DataSource. As the `CreateGuid()` function returns a string, a string value should be used for the Task initially present in the DS:
```js
ID: "1",
```

The default value also needs to be of the same type:
```js
id: { from: "ID",  defaultValue: "0"},
```

Here is a Dojo that properly implements the scenario in question:
https://dojo.telerik.com/aWaHadaL/32

As per the `expanded` state, that seems to be a real regression. Hence, I have altered the name of the GitHub issue.

**Comment by nelito987** [comment] 2022-05-05 10:49
An additional scenario related to the bug that is not covered, yet:

**_Behavior before the fix_** 
- Run the Dojo example - https://dojo.telerik.com/@NeliKondova/oxIXamoT
- Create two new child tasks for Task 1
- Change the start date to one of the child tasks and exit the edit mode

Previous behavior: A third child task is created - [screencast](https://www.screencast.com/t/wDflWGYu)

**_Behavior after the fix_**
- Follow the same steps
- After the fix, the task with the updated date disappears - https://www.screencast.com/t/uHqXu3IQs

**Comment by veselints** [comment] 2022-05-09 10:27
I beg your pardon for misleading you with my previous suggestion of how to assign an `id` to the newly created task. Handling the  `add` event of the Gantt will not properly set the `id` of the task. What needs to be done is to implement [`dataSource.transport`](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/configuration/transport) instead of the `dataSource.data`. The `create` function in the `transport` configuration should take care of the `id` generation and assignment:
```js
transport: {
    read: function(op) {
        op.success([
            {
                ID: "1",
                OrderID: 0,
                ParentID: null,
                Title: "Task1",
                Start: new Date("2014/6/17 9:00"),
                End: new Date("2014/6/17 11:00")
            }
        ]);
    },
    create: function(op) {
        op.data.ID = CreateGuid();
        op.success(op.data)
    },
    update: function(op) {
        op.success(op.data)
    },
    destroy: function(op) {
        op.success(op.data)
    }
},
```

Here is an updated version of the Dojo sample implementing the above:
https://dojo.telerik.com/IjIdUwen

That being said, after the fix the above described by @nelito987 additional scenario will no longer result in issue in the widget. Hence, I am closing the current issue.

**Closed by veselints** 2022-05-09 10:27 UTC
Labels: Bug, SEV: Low, C: Gantt, jQuery2, Priority 5, FP: In Development
