### ISSUE TITLE
Paste cleanup inserts lists as text in the Editor (Edge) 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4316] opened 2018-06-14 14:30 UTC
### Bug report
Lists copied from Word and pasted in the Editor are inserted as lines of text separated by <br /> tags in Edge. 

### Reproduction of the problem
[Screencast](https://www.screencast.com/t/iI31rlYbcjq4). Reproducible in the following [demo](https://demos.telerik.com/kendo-ui/editor/paste-cleanup). 

1. Check msAllFormatting, msConvertLists, msTags
2. Create a list in Word and copy/paste it in the Editor.

### Current behavior
No ul and li tags are created in Edge

### Expected/desired behavior
ul and li tags are created in Edge

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** x.y
* **Browser:** [Edge]

**Comment by sspasova** [comment] 2023-11-15 07:32
Closing this because the issue is no longer reproducible on Edge using Kendo UI 2023.3.1114.

**Closed by sspasova** 2023-11-15 07:32 UTC
Labels: Bug, SEV: Medium, C: Editor, jQuery, Triaged
