### ISSUE TITLE
Kendo menu popup is not visible when placed inside TabStrip header which is scrollable

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4424] opened 2018-08-03 14:08 UTC
### Bug report

When several tabs are added dynamically so that the header becomes scrollable, the menu popup becomes invisible.

### Reproduction of the problem
2017.2.621: http://dojo.telerik.com/egELUdeC/4
2018.2.620:  http://dojo.telerik.com/egELUdeC 
1. Add several tabs so the header becomes scrollable
1. Hover over Baseball menu item in the tab header

### Current behavior
2017.2.621: The menu popup hides behind the content
2018.2.620:  The menu popup is invisible

### Expected/desired behavior
Menu popup is visible

### Environment

* **Kendo UI version:** 2017.2.621
* **Kendo UI version:** 2018.2.620

**Comment by lwwells** [comment] 2018-09-02 14:16
Hi, all,

I am the developer who brought this to light.  I just anted to say that I am i the process of building an enterprise software package with kendo, and having this fixed is quite important to us.  If you have any kind of ETA on this, please let me know...or even if you have a hacky workaround for now, that would be greatly appreciated.  Thanks!

Leigh Wells
lwells@p3dev.com

**Comment by joneff** [comment] 2018-10-14 21:46
The issue is caused by a fix about a year ago telerik/kendo#353 so we can't really revert the behaviour.

One possible option would be to extend the menu functionality to allow `appendTo` just like with context menu.

@lwwells, I tried several hacky ways, but not yielded a result. That's not to say you can't achieve what you need too -- you could use context menu. I've created a small example to illustrate: https://dojo.telerik.com/@joneff/uJovEKus

**Comment by joneff** [comment] 2019-01-03 12:47
As an alternative, `overflow: hidden` can be undone with a bit of css. Here is an example: http://dojo.telerik.com/@joneff/UyIDUXiH.

There is a related item #2113 for exposing popup options in widgets.

Closing this item.

**Closed by joneff** 2019-01-03 12:47 UTC
Labels: Appearance, Bug, C: TabStrip, Priority 5, SEV: High, Won't Fix

**Comment by lwwells** [comment] 2019-01-03 14:19
joneff, sorry if I am missing something, but in your dojo, if I add enough tabs to make the strip scrollable, I still can't see the menus.

**Comment by joneff** [comment] 2019-01-03 14:47
When the tabstrip is scrollable, we explicitly force it to have `overflow: hidden`, so we could create a sort of "clip" area, in which the tabstrip is scrolled.

For that particular case, one of my previous examples, the one with context menu, should suffice. Context menus can be appended outside of the container, hence avoid the clipping.

**Comment by lwwells** [comment] 2019-01-03 15:07
OK, thanks, I will give that a shot.

**Comment by lwwells** [comment] 2019-01-03 16:00
You example menus don't seem to work in the appended tabs, only in the ones that are already there.  Any thoughts?
