### ISSUE TITLE
Hovering a textbox in a Menu/submenu item closes the item in the latest Chrome version

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2524] opened 2016-12-09 08:33 UTC
### Bug report

When the cursor enters a textbox that is inside of a submenu item, the respective submenu is closed. Observable only in the latest version of Google Chrome (55.0.2883.75 m).

### Reproduction of the problem
[http://dojo.telerik.com/OvURe](http://dojo.telerik.com/OvURe)
[http://dojo.telerik.com/ipihu/3](http://dojo.telerik.com/ipihu/3)

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** [Chrome 55.0.2883.75 m]

**Comment by Alex-Bubblemaster** [comment] 2016-12-19 07:13
Duplicate of #2526

**Closed** 2016-12-19 07:55 UTC
Labels: Bug, C: Menu, SEV: High, Team2
