### ISSUE TITLE
Editor table wizard does not apply styling to all cells

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5758] opened 2020-05-11 15:56 UTC
### Bug report
The Editor table wizard does not apply styling to all cells

### Reproduction of the problem
1. Open [this demo](https://demos.telerik.com/kendo-ui/editor/table-editing)
1. Select February Actual cell
1. Open table wizard
1. Select the Cell tab
1. Create a border  - for example, 6px double red border, click OK

### Current behavior
The specified border is not applied. Selecting the February header instead and repeating the steps above applies the border styling

### Expected/desired behavior
The styling applied through the wizard should be applied to the table cell 

### Environment

* **Kendo UI version:** 2020.1.406
* **Browser:** [all]

**Comment by sspasova** [comment] 2024-01-17 11:12
I am closing this issue because it is no longer reproducible using Kendo UI 2023.3.1114.

**Closed by sspasova** 2024-01-17 11:12 UTC
Labels: Bug, SEV: Low, C: Editor, jQuery, FP: Unplanned, Triaged
