### ISSUE TITLE
[Duplicate] Column menu toggles wrong column visibility when menu: false is set

### ISSUE THREAD

**Issue by zampage** [telerik/kendo-ui-core#5976] opened 2020-08-18 10:41 UTC
### Bug report

Wrong column visibility is toggled when one of the columns has `menu: false`.

### Reproduction of the problem
1. https://dojo.telerik.com/uSEloLEV/3
2. Open column menu
3. click "age" to hide column age

### Current behavior

The wrong column is hidden. (in the provided example, column "name" gets hidden, while checkbox of "age" is untouched.

### Expected/desired behavior

The correct column is hidden.

### Environment

* **Kendo UI version:** 2020.2.617
* **Browser:** all 

### Additional information

I have traced it back to this part in the kendo code where columns which are hidden from the column menu get sorted out and then mapped with the columnIndexMap. But I can't quite make it out why it bugs this way...

![kendo-grid-bug](https://user-images.githubusercontent.com/18336255/90503498-cc088d80-e14f-11ea-9792-6d967a2e77f5.PNG)

**Comment by zampage** [comment] 2020-08-18 10:42
Might this be a bug which occured after fixing #5700 ?

**Comment by dmanova** [comment] 2020-08-24 12:42
This is related to https://github.com/telerik/kendo-ui-core/issues/5870 and it has been fixed. At the moment the fix is available within the [Internal Build](https://www.telerik.com/support/whats-new/kendo-ui/release-history/kendo-ui-2020-2-812-internal-build)  and will be available in the next Major Release (R3 2020). 
Have in mind that the CDN is not available for Internal Builds. Here is more information on the topic:
https://docs.telerik.com/kendo-ui/intro/installation/cdn-service#it-is-not-possible-to-refer-kendo-ui-internal-builds-from-cdn

**Comment by dmanova** [comment] 2020-08-24 12:44
Duplicate of https://github.com/telerik/kendo-ui-core/issues/5870

**Closed** 2020-08-24 12:45 UTC
