### ISSUE TITLE
Unexpected Spreadsheet cell borders' artifacts when printing exported PDF

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#2739] opened 2017-02-08 15:56 UTC
### Bug report
When Spreadsheet with all borders applied is exported to PDF and that PDF is printed to OneNote or on a physical printer, there are border lines stretching out of the Spreadsheet.
Note - I could reproduce the issue only when printing to OneNote. Printing on a physical printer did not reproduce the issue.

### Reproduction of the problem
1. Go to http://demos.telerik.com/kendo-ui/spreadsheet/index
2. Select A1:G15 cells.
3. Switch off the grid lines to make it easier to see the border burrs.
4. Export to PDF with "Fit to Page" enabled.
5. Open the PDF with Chrome or Adobe Acrobat Reader.
6. Print the PDF - make sure that "Print as image" option is disabled (it could be in advanced options).

### Current behavior
[Screenshot from printing the PDF to OneNote](https://www.screencast.com/t/LKkIg1ySSs8O)

### Expected/desired behavior
[Screenshot from the actual exported PDF](https://www.screencast.com/t/ZgZozQkAD)

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by mishoo** [comment] 2017-02-10 10:30
I can't reproduce this, either on screen or when printing the result on paper.  I cannot test it from OneNote, but if the artefacts appear only there I would assume it's a bug in OneNote's PDF renderer and there's nothing we can do about it.

Closing this; please reopen if you can provide a reliable way to reproduce the issue with Adobe Reader or Chrome.  (I also tried [Evince](https://wiki.gnome.org/Apps/Evince/Downloads), [GhostScript](https://ghostscript.com/download/gsdnld.html) and [Okular](https://okular.kde.org/), all render it properly).

**Comment by jwbqv** [comment] 2017-02-15 18:54
Mishoo,   this is a critical issue for our customers & it has been reproduced by your support team.   The use of One Note was only for demonstration purposes, to make uploading the result easy.   Our clients are reporting the problem when printing to paper printers and we have reproduced it to paper printers as well in our office.   Thank you.

**Comment by mishoo** [comment] 2017-02-15 19:10
@jwbqv I would be more than happy to look into it, but I could not reproduce the issue.  If you can provide reliable instructions to demonstrate the issue with Adobe Reader or Chrome's PDF renderer, please let us know.

As noted in the issue description, our support colleague could only reproduce the issue in OneNote.

**Comment by jwbqv** [comment] 2017-02-15 19:14
The instructions included in the ticket reproduce it very reliably for us with the Chrome / Adobe combination.

I personally have an HP Officejet Pro 6830 on my desktop that prints the burrs when I following the instructions.    You have to make sure that “Print as image” is disabled in the printer’s advanced options, which may or may not be the default depending on your printer & how it was installed.

Thank you

Wes

**Comment by jwbqv** [comment] 2017-02-15 19:14
Reproduction of the problem

  1.  Go to http://demos.telerik.com/kendo-ui/spreadsheet/index
  2.  Select A1:G15 cells.
  3.  Switch off the grid lines to make it easier to see the border burrs.
  4.  Export to PDF with "Fit to Page" enabled.
  5.  Open the PDF with Chrome or Adobe Acrobat Reader.
  6.  Print the PDF - make sure that "Print as image" option is disabled (it could be in advanced options).

**Comment by mishoo** [comment] 2017-02-15 19:26
Alright, will take another look.  Reopening.

**Comment by Dimitar-Goshev** [comment] 2017-02-16 14:12
I followed the reproduction steps once again and the issue is reproducible only when printing to One Note:
- [Video with exporting steps](https://www.screencast.com/t/BocMzXD5s)
- [Printing options used](https://www.screencast.com/t/ns3CWsew)
- [OneNote printing result](https://www.screencast.com/t/1dO9m5Z6i8w)
- [Physically printed copy 1](https://www.screencast.com/t/QzOGTrSA)
- [Physically printed copy 2](https://www.screencast.com/t/89Nbc4iqDmD)

**Comment by mishoo** [comment] 2017-02-17 08:27
@Dimitar-Goshev I think the issue was about borders, not about the guidelines.  But regardless, I still cannot reproduce it with any PDF renderer I tried.

It seems like a technical impossibility, since borders have the exact same coordinates as the background rectangles — so there is no reason why they should be a little stretched vertically; this indicates a problem with the PDF renderer, which may be One Note or the printer driver (maybe that's why the issue doesn't occur when “print as image” is enabled).

I would also like to add that the border drawing code went unchanged for about a year, yet this is the only time such issue came up.  Since I can't repro, I can't help, sorry about that. :-\

**Closed by mishoo** 2017-02-17 08:27 UTC
Labels: Bug, C: Spreadsheet, SEV: Low, Won't Fix

**Comment by jwbqv** [comment] 2017-02-17 13:34
Actually, you guys have reproduced it with One Note.   As I previously noted that’s not our primary problem because our customers are having it also happen on their paper printers; however the fact that it also happens in One Note & that your team has reproduced it within One Note seems like something you could work on.

**Comment by tsvetomir** [comment] 2017-02-17 14:14
It is very likely that this is an issue with the OneNote PDF rendering implementation. We can't be certain what is causing the problem without access to its source code.

My recommendation is to file a bug report with Microsoft. We're willing to update our implementation, but we have to know _exactly how_.

**Comment by jwbqv** [comment] 2017-02-17 14:15
Once again, One Note is just a single example of where it’s happening and is available for your troubleshooting.   It also happens with paper printers.  I’ve reproduced it with the HP Officejet Pro 6830 which is what I have on my desktop; however our customers are seeing it also on other paper printers.

**Comment by tsvetomir** [comment] 2017-02-17 14:18
Are you printing from OneNote or from Adobe Reader?

**Comment by jwbqv** [comment] 2017-02-17 14:19
Paper printing is being done from either Adobe Reader or from Chrome.   We & our customers have seen it happen in both cases.

**Comment by tsvetomir** [comment] 2017-02-17 14:24
Okay, we'll try to reproduce it without OneNote.

We'd welcome:
* Specific versions of Adobe Reader, Chrome and the printer drivers
* Screenshots of the print dialog settings

**Comment by jwbqv** [comment] 2017-02-17 14:26
Here’s something that may help.
I tried printing your example PDF on several printers & none of them had burrs;
however, your PDF does not contain the cell borders that are necessary to get the burrs to appear.
Per my steps to reproduce, you need to select all the cells in the table & enable all the cell borders and you also need to disable the guidelines.
Try that & see if you can reproduce the burrs on paper printers also.
Thank you

**Comment by jwbqv** [comment] 2017-02-17 16:33
New info … it turns out that your PDF does print burrs when printed from within Chrome:

… when printed from Adobe Acrobat Pro DC version 15.023.20056, your PDF prints without any burr artifacts.

… when printed from within Chrome version 56.0.2924.87, your PDF prints with burr artifacts of the guidelines similar – but not exactly the same – as what we are seeing with cell borders.   For example our PDF with cell borders shows burrs inside the merged header cell (the one with Invoice #52 in it).  Your PDF with guidelines but no borders doesn’t have the burrs inside the merged header; however they both have the burrs around the exterior of the grid.

Both versions were printed to an HP Officejet Pro 6830 connected via USB cable, from a Windows 10 Pro computer with all updates applied from Microsoft.

The HP Officejet Pro 6830 driver version is 14.40.0.3447

Here are screen shots of the printing dialogs & also a scan of your PDF printed from within Chrome.


[cid:image001.png@01D288FC.A56F8110]

[cid:image002.png@01D288FC.A56F8110]

[cid:image003.png@01D288FC.A56F8110]




Thank you

Wes


From: Wes Byrne
Sent: Friday, February 17, 2017 8:26 AM
To: 'telerik/kendo-ui-core' <reply@reply.github.com>; telerik/kendo-ui-core <kendo-ui-core@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [telerik/kendo-ui-core] Unexpected Spreadsheet cell borders' artifacts when printing exported PDF (#2739)

Here’s something that may help.
I tried printing your example PDF on several printers & none of them had burrs;
however, your PDF does not contain the cell borders that are necessary to get the burrs to appear.
Per my steps to reproduce, you need to select all the cells in the table & enable all the cell borders and you also need to disable the guidelines.
Try that & see if you can reproduce the burrs on paper printers also.
Thank you

**Comment by Dimitar-Goshev** [comment] 2017-02-20 15:20
Hi,
I am afraid that the screenshots attached to your last reply are not visible in this thread.
In addition, it seems that we are duplicating communication threads - here and in the respective support ticket. Could we continue this discussion in only one of the threads to avoid duplication and miscommunication. I am pasting my reply from today below:

The PDF I sent you was created following the steps provided by you in the GitHub issue. The borders step is skipped there and as they were newer than those from the beginning of this thread, I assumed that they are still OK:
_jwbqv commented 5 days ago_
_Reproduction of the problem_
_1. Go to http://demos.telerik.com/kendo-ui/spreadsheet/index_
_2. Select A1:G15 cells._
_3. Switch off the grid lines to make it easier to see the border burrs._
_4. Export to PDF with "Fit to Page" enabled._
_5. Open the PDF with Chrome or Adobe Acrobat Reader._
_6. Print the PDF - make sure that "Print as image" option is disabled (it could be in advanced options)._

I followed the initial steps and still the issue is not reproducible on my side:
- [Video of Export](https://www.screencast.com/t/nADfvtIrwS0)
- [Print options](https://www.screencast.com/t/KsttyeEuIEg)
- [Print outcome](https://www.screencast.com/t/a4F2pB6am8)

It seems that the reproduction may depend on the printer settings, as you could reproduce the issue when printing with Chrome, but not with Acrobat. I tried to find "Print as Image" option when printing from Chrome, but I could not find it on my side. So I printed using Acrobat. Could you check if there are differences in the printer settings which could contribute for the issue reproduction? Also please send us an exported PDF, which we could print on our side.

**Comment by jwbqv** [comment] 2017-02-20 16:01
Hi Dimitar,

Up until now I had not noticed that the steps in the github ticket left out my step #2 where the borders are turned on.     Turning on the cell borders has been our most reliable way of making the issue happen and is the scenario that our customers are running into;   however I did also see burr artifacts when printing your PDF without borders – but with guidelines – when printed from within Chrome.
RE: duplicate communications I believe that’s because different people may be posted responses to both the Support ticket 1088865 and the github issue 2739 on your end?  I’m generally just replying to the e-mails that come through from the two systems.

RE: sending a PDF, I’ll get that over to you today.

Thank you

Wes
