### ISSUE TITLE
When a Window is not focused, clicking on a DropDownList in the Window results in the DropDownList not gaining focus

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6286] opened 2021-02-10 08:37 UTC
### Bug report
When a Window is not focused, clicking on a DropDownList in the Window results in the DropDownList not gaining focus and the popup opening and immediately closing.
This is a regression introduced with v2021.1.119

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/atUdebaY)
2. Click outside of the Window, so it loses focus
3. Click on the DropDownList

### Expected/desired behavior
The DropDownList should gain focus and the popup should remain open as in [v2020.3.1118](https://dojo.telerik.com/@AleksandarEvangelatov/uvILaXap)
### Environment

* **Kendo UI version:** 2021.1.119
* **Browser:** [all]

**Comment by Iankodj** [comment] 2021-02-16 07:42
Related to: https://github.com/telerik/kendo-ui-core/issues/6248

**Comment by Iankodj** [comment] 2021-02-16 07:47
Fixed in [https://github.com/telerik/kendo/tree/fix-window-dropdowns-open](https://github.com/telerik/kendo/tree/fix-window-dropdowns-open)

**Comment by antonmironovv** [comment] 2022-05-09 11:07
Represented in ticket #1564181

**Comment by martintabakov** [comment] 2023-08-24 11:42
The issue reproduces again with the latest version https://dojo.telerik.com/eYEragOh

**Comment by gdenchevprog** [comment] 2023-11-03 16:07
I am unable to reproduce the exact same issue using latest(at least with the steps from this issue). Is it possible that the problem that is currently being described is the following one - #7576 ?

**Closed** 2023-11-22 14:18 UTC
Labels: Bug, C: Window, SEV: Low, jQuery, Priority 5, Next LIB, FP: In Development
