### ISSUE TITLE
Delete button missing in the Scheduler's occurrence editing dialog

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5325] opened 2019-10-10 08:09 UTC
### Bug report
An occurrence can be deleted from the "x" button in the event's top right corner, but when it is edited a "Delete" button is not displayed in the editor.  

### Reproduction of the problem
Reproducible in the demos and also with **editRecurringMode: "occurrence"** ([dojo example](https://dojo.telerik.com/UnaNiLak)).

### Current behavior
Delete button is not displayed.

### Expected/desired behavior
Delete button is displayed.

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2019-12-06 13:58
Duplicate of: https://github.com/telerik/kendo-ui-core/issues/2514

**Closed by Dimitar-Goshev** 2019-12-06 13:58 UTC
Labels: Bug, C: Scheduler, Kendo2, SEV: Medium
