### ISSUE TITLE
The height of the window in percent incorrect~

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-ui-core#5399] opened 2019-11-08 06:46 UTC
### Bug report
The height of the window in percent incorrect~

### Reproduction of the problem
```css
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.3.1023/styles/kendo.default-v2.min.css">
```
```html
<button class="k-button k-state-selected" id="divWindow" type="button">Popup Window</button>
```
```js
$('#divWindow').click(function () {
      var divWindow = $('<div class="window-box"></div>').kendoWindow({
          animation: {open: {effects: 'fade:in'}, close: {effects: 'fade:out'}},
          title: 'test',
          width: '80%',
          height: '80%',
          modal: true,
          pinned: true,
          resizable: false,
          close: function () {
              divWindow.destroy();
          }
      }).data('kendoWindow');
      divWindow.content('The window height is not correct!').center().open();
});
```

### Current behavior
I found that the height seemed to be correct when I set half the standard value~ In the above example I have to set it to '40%'~

### Expected/desired behavior
The height of the window in percent correct~

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2019-11-11 08:14
@IKKI2000 Thank you for your feedback. This is a duplicate of the following Window issue:
https://github.com/telerik/kendo-ui-core/issues/5343

**Closed by Dimitar-Goshev** 2019-11-11 08:14 UTC
