### ISSUE TITLE
AutoComplete stops working on Edge 38 with special characters

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2487] opened 2016-11-28 09:23 UTC
### Bug report

AutoComplete stops working when a special character is pressed - e.g. Danish letters:

> å, æ, é, ø

Ticket ID: 1076163

### Reproduction of the problem

[Video](https://www.youtube.com/watch?v=A2CxdS3kLv8)
[Dojo](http://dojo.telerik.com/uwake/7)

### Current behavior

AutoComplete works until the danish letter is enetered.

E.g. dataItem - "skål". 

1) Type "skå" - "skål" is shown in AutoComplete popup as expected
2) On adding "l",  shows "No Data"

### Environment

* **Kendo UI version:** 2016.2.714, 2016.3.914, 2016.3.1028, 2016.3.1118
* **jQuery version:** 1.12
* **Browser:** [Edge 38.14393.0.0 ]

**Comment by arturkula** [comment] 2017-02-09 13:02
Hi, just wanted to ask what is the status of this bug?  Is this on progress? When it will be fixed? Thanks for the info.

**Comment by IvanDanchev** [comment] 2017-04-05 13:00
The issue is also reproducible when filtering Spanish characters (ñ) when using Edge version 38.14393.0.0 and jQuery 1.12 or 3.0+.

**Comment by EpsilonProgNET** [comment] 2017-05-25 10:20
Any news about this issue? It hasn't been assigned yet and I really need to be solved asap.
Is it solved in latest version of KendoUI professional?

**Comment by nstoychev** [comment] 2017-06-01 16:15
The following expression "skål!".lastIndexOf("skå", 0) === 0 returns true in all browsers except Edge v.38. This is a browser issue and it looks like it is resolved ([#EdgeBug .string.lastIndexOf is broken when used as startsWith when string contains an Umlaut](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9271625/)).

**Comment by mparvanov** [comment] 2017-06-07 11:30
The issue is no more reproducible in Edge 40

**Closed by mparvanov** 2017-06-07 11:30 UTC
Labels: Bug, C: AutoComplete, Kendo2, Needs QA, SEV: Medium
