### ISSUE TITLE
Kendo Vue wrapper (kendo-dropdowns-vue-wrapper) data type problem

### ISSUE THREAD

**Issue by umutozel** [telerik/kendo-ui-core#3844] opened 2017-12-13 07:57 UTC
### Bug report
kendo-dropdowns-vue-wrapper should not limit the type of "value" prop to string.
Props definition for AutoComplete, ComboBox and DropDownList have this line:
    value: String,

### Reproduction of the problem
Binding a "Number" typed field to "value" property of AutoComplete, ComboBox and DropDownList component.

### Current behavior
We get this warning (copied from console)
vue.esm.js:476 [Vue warn]: Invalid prop: type check failed for prop "value". Expected String, got Number.

### Expected/desired behavior
No error. Value prop should be like this:
    value: String | Number,

### Environment

* **Kendo UI version:** 2017.3.1116
* **jQuery version:** 3.2.1
* **Browser:** [all]

**Comment by Iankodj** [comment] 2017-12-13 08:49
The issue is a duplicate of https://github.com/telerik/kendo-ui-core/issues/3843

**Closed by Iankodj** 2017-12-13 08:49 UTC
