### ISSUE TITLE
Spreadsheet displays no more than 76694 rows in IE

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2854] opened 2017-03-03 11:39 UTC
### Bug report
Spreadsheet displays no more than 76694 rows in IE

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/Ukute/3)

### Expected/desired behavior
Spreadsheet should display all rows (100,000) as the other browsers do

**Comment by mishoo** [comment] 2017-03-10 08:02
I suspect there is a hard browser limit here.  See this: http://stackoverflow.com/questions/18708598/ie-fundamental-limit-of-scrolltop-in-a-large-scrollable-div

I wouldn't say this is of “medium” severity.

**Comment by tsvetomir** [comment] 2017-03-10 13:24
Doesn't look fixable to me.

**Comment by catmanjan** [comment] 2017-04-04 07:11
If the problem is max element size, why not create a new element once you reach the threshold.

**Comment by mparvanov** [comment] 2019-11-08 13:39
Closing due to browser limitation.

**Closed by mparvanov** 2019-11-08 13:39 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: Medium, Triaged
