### ISSUE TITLE
kendo.support.mobileOS returns false on mobile devices in Desktop mode

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5924] opened 2020-07-15 17:27 UTC
### Bug report
Reported for iPad Air 2, tested and reproduced on iPad Pro 2020 12.9' iOS 13.5.1.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/uLiXUsiL) example.
1. The result of kendo.support.mobileOS is displayed with an alert.

### Current behavior
mobileOS returns false.

### Expected/desired behavior
mobileOS returns an object with information about the mobile OS, device and browser.

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [ iOS XX Safari | iOS Firefox ]

**Comment by dmanova** [comment] 2020-11-04 13:59
The issue is valid also for Android mobile devices when in Desktop mode. iPad users start experiencing it more often because since iOS 13 the Desktop mode is the default one for iPad. Before this version, the Mobile mode was the default one.

As a workaround in most cases `kendo.support.mobileOS` could be replaced by `kendo.support.touch`

**Comment by Dimitar-Goshev** [comment] 2022-02-03 08:31
The fix for this issue https://github.com/telerik/kendo-ui-core/issues/5552 fixes kendo.support.mobileOS to return object, instead of false for Safari on iPad with iOS 14. The Android issue mentioned in comments is will not be addressed at this time. Feel free to log it as a separate issue, if there are reports for this scenario.

**Closed by Dimitar-Goshev** 2022-02-03 08:31 UTC
Labels: Bug, SEV: Medium, jQuery2, jQuery1, Touch Devices, FP: In Development
