### ISSUE TITLE
PDF export of the Spreadsheet does not display all borders when there is a set background

### ISSUE THREAD

**Issue by zstoyanova9** [telerik/kendo-ui-core#7531] opened 2023-09-21 12:32 UTC
### Bug report

When exporting a Spreadsheet with a set background to a PDF file, some of its borders are not displayed.

### Reproduction of the problem
1. Open the following Dojo example - https://dojo.telerik.com/@sspasova/eQeROMar
2. Export the Spreadsheet to PDF

### Current behavior
Some borders of the Spreadsheet are missing in the exported PDF file.

### Expected/desired behavior
All borders of the Spreadsheet should be displayed in the PDF file.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by pepinho24** [comment] 2024-11-28 10:59
Closing as duplicate of https://github.com/telerik/kendo-ui-core/issues/4763

**Closed by pepinho24** 2024-11-28 10:59 UTC
Labels: Bug, SEV: Low, F: PDF Export, C: Spreadsheet, FP: Unplanned
