### ISSUE TITLE
Acrobat error when opening PDF exported from Grid in Firefox

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2699] opened 2017-01-31 19:07 UTC
### Bug report

When the Grid is filterable the new filter icons are not exported properly - they are not visible when the file is exported in Chrome, and the file cannot be opened (an error occurs) when the Grid is exported in Firefox (v. 51). Observed with Kendo UI 2017.1.118 only.

### Current behavior
[http://dojo.telerik.com/AHenE](http://dojo.telerik.com/AHenE)
### Expected/desired behavior
Filter icons are properly exported.

* **Kendo UI version:** 2017.1.118

**Comment by mishoo** [comment] 2017-01-31 19:18
Closing as duplicate of #2687.  Please reopen if the issue still occurs with *latest* code. (fix is pushed to `production` branch as well)

**Closed by mishoo** 2017-01-31 19:18 UTC
Labels: Bug, C: Grid, F: PDF Export, SEV: High
