### ISSUE TITLE
Selecting a tab from the TabStrip scrolls to the top of the page

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6660] opened 2021-12-13 18:07 UTC
### Bug report
Selecting a tab from the TabStrip causes the page to scroll to the top. The body height must be at least 746px in order to reproduce the bug.
Regression since 2021.3.914

### Reproduction of the problem
1. Open this Dojo example  - https://dojo.telerik.com/@Dimitar-Goshev/ANOkAfor
2. Scroll down the page until the tab's content is visible.
3. Select another tab, then select another tab.

### Current behavior
The page scrolls to the top. After that, each tab selection scrolls to the top.

### Expected/desired behavior
Selecting a tab shouldn't cause scrolling.

### Environment
* **Kendo UI version:** 2021.3.1207
* **Browser:** [all]

**Comment by veselints** [comment] 2022-01-18 15:46
Inroduced with:
https://github.com/telerik/kendo/commit/ccdae889298a112079ec6c1ca76d787da6701786

**Comment by Dimitar-Goshev** [comment] 2022-04-18 09:01
The issue is still reproducible when clicking once again on a tab, which was previously active, e.g. on the [sample Dojo](https://dojo.telerik.com/@Dimitar-Goshev/IvAwIgiw) clicking on New York, and then clicking on Paris. The scrolling is not reproducible the first time a tab is activated, but it is reproducible the second time it is activated.

**Comment by veselints** [comment] 2022-04-18 09:57
@joneff can you review the case?

**Comment by joneff** [comment] 2022-05-09 11:29
At the time of authoring, the code was working OK i.e. was getting the correct min height. now it's returning 0.

Perhaps a new patch could have an extra step to fetch the height and compare with min height and return the bigger of the two numbers and use that for setting min height.

**Comment by carenrose** [comment] 2023-03-30 21:53
I did a little testing by directly editing the minified js, to see if I could figure out what was causing the issue. This is what I discovered:

Using the unminified [kendo.tabstrip.js](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.tabstrip.js) as reference - on line 432, after the activated tab's content is shown, the tabstrip's `min-height` is set back to its previous value (`oldMinHeight`).

It appears that the issue occurs because the *first* time a tab is activated, there is no `min-height` set on the tabstrip, and thus `var oldMinHeight = that.element.css('min-height');` (at line 404) will contain `"0px"`. The `min-height` is temporarily set to the current `outerHeight()` on line 405, but then on line 432, that `"0px"` value is being set as the `min-height` of the tabstrip. The next time a tab is activated, it gets the `min-height` again, and it will still be `"0px"`. It will always be `"0px"`.

The fix seems simple - at line 432, simply check that `oldMinHeight` does not equal `"0px"`.  
`if (oldMinHeight != "0px") {
    that.element.css('min-height', oldMinHeight);
}`

There is still some minor jumping that occurs when switching from a new tab that is taller to a tab that is shorter, or when a tab's height increases and you then switch to another tab. I'm not sure what the intended behavior is, if this jumping is intended or is another bug. I also don't really know if there's any reason that the `!= "0px"` check should/shouldn't be used.

Hope this helps?

**Comment by veselints** [comment] 2023-04-06 14:59
Thank you for your input @carenrose!
I believe the issue here is related to animation timing. The old (0px) min height is set before the execution of the collapse/expand animation. That would force the TabStrip element to shrink. Having that said, the `that.element.css('min-height', oldMinHeight);` call must be executed after the animation finishes. I have just committed such a fix. Let's see how it goes in testing.
Once again, thank you for your input as it pointed me to the proper (I believe) direction for the fix!

**Closed** 2023-04-19 13:03 UTC
Labels: Bug, C: TabStrip, SEV: Medium, jQuery, Priority 5, FP: Planned
