### ISSUE TITLE
Window is not getting focused when using jQuery 3.6.0

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6572] opened 2021-09-21 07:01 UTC
### Bug report

Upon opening the Window, the widget is not getting focused when using jQuery 3.6.0.

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/@martin.tabakov@progress.com/EcIheNif/3

### Current behavior
The Window is not focused upon opening.

### Expected/desired behavior
The Window should be focused upon opening.

### Environment

* **Kendo UI version:** 2021.3.914
* **jQuery version:** 3.6.0
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2023-11-22 14:23
The issue is reproducible with jQuery versions 3.6.0-3.6.4
The issue is not reproducible with jQuery 3.7.0 and 3.7.1 - [Working Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/aniruney) .
Closing the issue as Won't fix. Please use jQuery 3.7.0+

**Closed by Dimitar-Goshev** 2023-11-22 14:23 UTC
Labels: Bug, C: Window, SEV: Medium, jQuery, Priority 1
