### ISSUE TITLE
Pdf export functionality repeats the first page multiple times when papersize is not set.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-ui-core#4291] opened 2018-06-05 12:35 UTC
1.Navigate to:
https://dojo.telerik.com/@milena/OPojixuy 
Click 'Export to PDF' button and open the exported file.
Result:
[Export (20).pdf](https://github.com/telerik/kendo-ui-core/files/2072343/Export.20.pdf)

**Comment by mishoo** [comment] 2018-06-15 07:09
This appears to happen because of a CSS issue.  If we load the more “traditional” `kendo.common.min.css` and `kendo.default.min.css` (instead of `kendo.default-v2.min.css`), the issue is gone: https://dojo.telerik.com/ApeJIPAr

Still not sure what exactly could cause it.

**Comment by mishoo** [comment] 2018-06-15 08:16
On further investigation, it seems that some [PDF-related styles](https://github.com/telerik/kendo/blob/master/styles/web/common/grid.less#L825) for the grid are not included in the new SASS themes.  Also, note that there could be other widgets showing similar problems with the new themes.

If we just add the styles to the page, it works properly: https://dojo.telerik.com/AToReQuT

Assigning to Ivan as discussed.

**Comment by twurm** [comment] 2019-01-17 14:34
@mishoo adding those styles doesn't completely fix the issue.  The PDF output should be the same as the export from: [https://dojo.telerik.com/EHUFIJOg](https://dojo.telerik.com/EHUFIJOg).

**Comment by TeyaVes** [comment] 2019-02-08 09:52
> @mishoo adding those styles doesn't completely fix the issue. The PDF output should be the same as the export from: https://dojo.telerik.com/EHUFIJOg.

@twurm , the layout of the PDF export in the Dojo that you have provided is different because it uses a predefined template. However, the template configuration works only when the paperSize is defined, as pointed out in the documentation here: https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/pdf.template

**Closed** 2019-02-15 08:20 UTC
Labels: Bug, C: Grid, F: PDF Export, Kendo1, Kendo2, Priority 5, SEV: High
