### ISSUE TITLE
Validation tooltip not shown for dirty cells in batch mode

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3935] opened 2018-01-24 09:33 UTC
### Bug report

Reported in Ticket ID: 1149719

### Reproduction of the problem

Steps: 

1. Edit a cell in the ProductName column, for example "Chai -> Shai"
1. Tab or click, to allow the cell to be closed and dirty
1. Return to the cell and enter a lowercased(invalid) name "Shai -> shai"

Bootstrap V3 theme - the tooltip is present with `display: block` but it is invisible, the cell cannot close because it is invalid:  https://dojo.telerik.com/@bubblemaster/iTIru

Metro Black - the tooltip works as expected https://dojo.telerik.com/oYOSI

### Expected/desired behavior

Tooltip should be shown when the cell is invalid

### Workaround

```
  .k-grid .k-dirty-cell.k-edit-cell {
      position: static;
    }
```

### Environment

* **Kendo UI version:** 2018.1.117

**Comment by matanasov** [comment] 2018-03-28 14:19
Duplicate of https://github.com/telerik/kendo-ui-core/issues/4103

**Closed by matanasov** 2018-03-28 14:19 UTC
Labels: Bug, C: Grid, C: Tooltip, C: Validator, Kendo1, Priority 1, SEV: Medium
