### ISSUE TITLE
Editor in Tabstrip: Cannot initialize the Editor before the Tapstrip is initialized 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5010] opened 2019-04-23 13:34 UTC
### Bug report
When an Editor is used inside a Tabstip if the Editor is initialized before the Tabstrip all its toolbar elements and textarea are not usable. If a tab is changed, the following exception is being thrown in the console: 

> Uncaught TypeError: Cannot use 'in' operator to search for 'getSelection' in undefined

### Reproduction of the problem

1. Open and run [this Dojo](https://dojo.telerik.com/EmaSAPix).
2. There are no errors in the console and the Editor inside the Tabstrip is unusable. 
3. Switch to the "Editor2" tab. Nothing appears in the tab and the mentioned TypeError is being thrown. 

### Expected/desired behavior
Open the above Dojo and move the Editors' initialization after the initialization of the TabStrip. Both the Editors in "Editor1" and "Editor2" tabs are working properly. 

![editor](https://user-images.githubusercontent.com/41293735/56584299-2ccb9880-65e4-11e9-9edc-15736ab061fb.png)

* **Kendo UI version:** 2019.1.220
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by adampresley** [comment] 2019-10-22 03:05
I experience the same issue when using the Vue version of the Editor and Tabs. Version: 2019.3.917

**Comment by nenchef** [comment] 2020-07-13 13:04
Issue reported in TID: 1474893. 
The case in this thread is using tag helper to initialize the Editor widget. Runnable sample attached.
[TestProj.zip](https://github.com/telerik/kendo-ui-core/files/4912555/TestProj.zip)

WORKAROUND FOR TAGHELPERS:
Initializing the component from div tag:

```js
<kendo-editor name="TestEditor" tag="div">
</kendo-editor>

```

**Comment by veselints** [comment] 2020-10-21 08:50
Closing the issue as it is not a bug in the Editor widget. When initializing the Editor in an element which has been later moved in the DOM, the Editor needs to adjust its iframe content after the DOM change has finished. Therefore, in the scenario in question, after the TabStrip is initialized the [`Editor.refresh()`](https://docs.telerik.com/kendo-ui/api/javascript/ui/editor/methods/refresh) method should be called:
```js
$("#tabstrip").kendoTabStrip({
  animation: {
    open: {
      effects: "fadeIn"
    }
  }
});

$("#editor1").getKendoEditor().refresh();
$("#editor2").getKendoEditor().refresh();
```

Here is a modified version of the above Dojo sample, in which both Editors work properly:
https://dojo.telerik.com/EmaSAPix/17

**Closed by veselints** 2020-10-21 08:50 UTC
Labels: Bug, C: Editor, C: TabStrip, FP: In Development, Kendo2, Priority 3, SEV: Medium
