### ISSUE TITLE
Fix for #364 causes complications with custom validators

### ISSUE THREAD

**Issue by troybugos** [telerik/kendo-ui-core#1035] opened 2015-08-13 16:05 UTC
The fix for #364, https://github.com/telerik/kendo-ui-core/commit/8473836ecde526a9400012e7287bdbe5ea2619f8, causes downstream issues when creating custom validators.

Since the fix only hides the invalidly appended error messages, they are still there.  So, if you are authoring custom validators you have to deal with these all over again sometimes (ex. if you try to re-style the message's CSS "display" property or if you need to perform different DOM searches).

During customization, a person can spend a lot of time trying to "fix" their own code and, also, researching how it's happening. 

Can #364, and the ghost error message nodes in general, be addressed such that they aren't put into the DOM in the first place?

 Now that I know, I can hack around this, but, at a minimum, it should be noted in the Kendo docs that these ghost nodes can appear in the DOM.

**Comment by troybugos** [comment] 2015-08-13 16:32
here's an example of my custom fix to the fix.  it's a custom rule to enforce that one member of a checkbox array was checked.

```
       rules: {
            checkboxrequired: function(input) {
               $timeout(() => {
                    var dataFor = $('[data-for]');

                    _.forEach(dataFor, (theNode) => {
                        theNode = $(theNode);
                        var dataForVal = theNode.attr('data-for');
                        var nameValOfPreviousSibling = theNode.prev().attr('name');
                        if (dataForVal !== nameValOfPreviousSibling)  {
                            theNode.hide();
                        }
                    });
                }, 10);

                return ($('[zg-cb-required]:checked').length > 0)
                    ? true
                    : false;
            }
        },
```

**Comment by rkonstantinov** [comment] 2015-08-24 07:15
Could you please provide a simplified test case (using a http://dojo.telerik.com/)  which demonstrates the issue you are experiencing. This will allow us to get better understanding about the scenario in question.

**Comment by underlog** [comment] 2016-07-14 13:22
Closing due to lack of reproduction scenario. @troybugos - reopen if you have one.

**Closed by underlog** 2016-07-14 13:22 UTC
Labels: Bug, C: Validator, SEV: Low
