### ISSUE TITLE
Spreadsheet formula-input does not wrap long text

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3407] opened 2017-07-14 08:33 UTC
### Bug report
Long text in formula input overflows it.

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/omUCECIb) example.

### Current behavior
The text in the formula bar does not wrap and goes outside the boundaries of the widget.
![image](https://user-images.githubusercontent.com/6614183/48823334-1e453080-ed69-11e8-9528-b4b3f82f802e.png)

### Expected/desired behavior
The text in the formula bar wraps. 

### Workaround: 
```html
<style>  
  // for the formula-input in the formula bar and the cell edit element
  .k-spreadsheet .k-spreadsheet-formula-input {
    white-space: normal !important;
    overflow-y: scroll !important;
  }

  // for the formula-input in the cell edit element
  .k-spreadsheet .k-spreadsheet-view .k-spreadsheet-formula-input {
    height: auto !important;
  }
</style>

// render event handler for the formula-input in the edited cell
render: function(e) {
  var selected = $('.k-spreadsheet-selection');
  var leftPosition = selected.position().left;
  var offset = 780 - leftPosition;
  var offsetInPx = offset.toString() + 'px';
  var editorWrapper = $('.k-spreadsheet .k-spreadsheet-view .k-spreadsheet-formula-input');
  editorWrapper.css('width', offsetInPx);
},
```

[Workaround Dojo here](http://dojo.telerik.com/Ejowa/7)

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2020-09-10 09:14
Duplicate of https://github.com/telerik/kendo-ui-core/issues/5387 - keeping the other issue open as it has corresponding feedback portal item as well.

**Closed by Dimitar-Goshev** 2020-09-10 09:14 UTC
Labels: Bug, C: Spreadsheet, Kendo2, Priority 1, SEV: Low
