### ISSUE TITLE
Defined formatting is reset upon input

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-ui-core#1723] opened 2016-05-27 08:26 UTC
If a cell has a format set (say, `@`, indicating that it will contain text), it will reset its formatting when the user inputs a value.

Currently, there is no way to enter the text `10/10/10` and keep it like that (it gets converted to a date and sets the format, then if you apply `@` as a format, it will be converted to the number of the date). MS Excel keeps the formatting, and it feels correct.

Seems like a bug? @ggkrustev @mishoo what do you think?

**Comment by mishoo** [comment] 2016-05-27 09:00
We should probably not attempt to parse the value if format is `"@"`?  The issue is on [this line](https://github.com/telerik/kendo/blob/master/src/spreadsheet/range.js#L184) — if the input looks like a date, it's unconditionally converted to the numeric date representation.

We should still parse input that starts with `=` though (formulas) even if format is plain text.

**Comment by gyoshev** [comment] 2016-05-27 13:22
From what I tested, if the cell has a format set (no matter what the format is), Excel does not try to guess its format. Formulas are computed, but still use the previously defined format. That appears to be intentional in telerik/kendo@f8ef2153, but I could not see why. Or am I missing something?

**Comment by DavidSoMighty** [comment] 2016-06-06 22:05
Is the intended behavior of assigning a format a "@" to treat it as text and only text? 

http://dojo.telerik.com/eMaWo/7

and the bug is if you enter a value that looks like a date (6/6/16), it will automatically try and convert it to a date instead of retaining it's pure text formatting?

**Comment by mishoo** [comment] 2016-06-07 08:11
@DavidSoMighty Yes, that is the issue.  We should parse as a date only if the existing formatting is not plain text (`@`).

**Comment by mishoo** [comment] 2016-06-07 09:17
I've checked Excel and Google Sheets more closely.  There's a bigger issue we have (doesn't seem critical to me, but our behavior differs): both of them interpret a value as numeric *when needed*, rather than when inputted.

Example: if you format `A1` as plain text and type `1/2/2016` into it, the string `1/2/2016` will be stored.  Then if you type in `B1: =A1+1`, instead of getting a `#VALUE!` error (which is what we return when adding a string to a number), you get `42372` because Excel parses the string as numeric representation of the date, *at formula evaluation time*.

> (FYI, there's no Github emoticon for **facepalm**)

This isn't unfixable, but it might slow down sane scenarious, as well as add more mess to a function that starts with this comment: `// Lasciate ogni speranza, voi ch'entrate.`.

Thoughts?

**Comment by underlog** [comment] 2016-06-07 09:30
The cost of addressing this sounds like it's not worth it. I suggest that we close this issue and redirect customers to 👍 it. Let's revisit if it turns into a common problem many people face.

**Comment by mishoo** [comment] 2016-06-07 09:33
@underlog This issue itself can be fixed (don't parse input as date if the format is text).  I'll push a fix for that.  What I outlined above is different.

**Closed** 2016-06-07 11:15 UTC
Labels: C: Spreadsheet, Question

**Comment by DavidSoMighty** [comment] 2016-06-07 16:02
Thank you for the response. I'm still a bit confused now.  The issue was closed, but does that mean it's going to be fixed in an upcoming release?  Or is it going to be left in, to be voted on?

**Comment by mishoo** [comment] 2016-06-07 16:20
@DavidSoMighty the issue as described is fixed and the fix will be available in an internal build soon.  Then there's this bigger problem that I described in a comment above; that one is still open to discussion.  I'll log a separate issue for it.

BTW, there *is* currently a way to input any string and leave it unparsed — prefix with an apostrophe.  This works like in Excel.  If you type `'1/2/2016` then the value `1/2/2016` will be stored as a string, rather than numeric date value, and it won't override the existing format.
