### ISSUE TITLE
Switch is not working in Chrome on Android devices

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7313] opened 2023-04-24 05:30 UTC
### Bug report

Switch component can not be turned on/off in Chrome on Android devices.

### Reproduction of the problem
1. [Open the demos](https://demos.telerik.com/kendo-ui/switch/index) in Chrome on Android device in mobile mode.

### Current behavior
The Switch can not be turned on/off.  
The Switch works as expected when the browsers is switched to desktop mode.

### Expected/desired behavior
The Switch should work as expected in Chrome in Andorid. 

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all ]

**Comment by nelito987** [comment] 2023-05-04 12:41
Reported in ticket ID: 1607627

**Comment by sspasova** [comment] 2024-01-09 13:30
I am closing this because the issue is no longer reproducible with Kendo UI 2023.3.1114. Tested on Android & iOS.

**Closed by sspasova** 2024-01-09 13:30 UTC
Labels: Bug, SEV: High, jQuery, Priority 1, C: Switch, FP: Unplanned
