### ISSUE TITLE
When all values in a Heatmap are 0 the background is black

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#6650] opened 2021-12-06 09:49 UTC
### Bug report

In a scenario when all the values in a Heatmap are zero, the background is black with fill property = "NaNNaNNaN"

### Reproduction of the problem

Run the following dojo example:
[https://dojo.telerik.com/@anton.mironov/eVESohAp](https://dojo.telerik.com/@anton.mironov/eVESohAp)

### Environment

* **Kendo UI version:** 2021.3.1109
* **Browser:** [all]

**Comment by sspasova** [comment] 2024-01-03 12:56
I am closing this as the issue is already fixed. Not reproducible with Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/utUpIFEn

**Closed by sspasova** 2024-01-03 12:56 UTC
Labels: Bug, C: Chart
