### ISSUE TITLE
Autocomplete heisenbug: highlighting first item when asynchronous search

### ISSUE THREAD

**Issue by v-olg** [telerik/kendo-ui-core#6443] opened 2021-06-01 19:31 UTC
### Bug report
We have the kendoAutoComplete with roughly following code:

```
const autocomplete = searchEditbox.kendoAutoComplete({
    highlightFirst: false,
    delay: 0,
    dataTextField: "Text",
    ignoreCase: true,
    filter: "contains",
    dataSource: this.constantDataSource,
    filtering: (e: kendo.ui.AutoCompleteFilteringEvent) => {
        const value = e.filter.value;
        
        this.GetSearchSuggestionRequest(value)).then(
            (r) => {
                autocomplete.dataSource.data([...this.constantDataSource, ...r.GetData()]);
                // constantDataSource for example [{ Text: "Search by MdmId:"}]
            });
    },
    select: (e: AutoCompleteSelectEvent) => {
        // some logic
    }
}).data("kendoAutoComplete");
```
I encounter the same problem when use Kendo server filtering instead requests from "filtering" method. In this case the bug is reproduced, but much less often. 

```
dataSource: {
                serverFiltering: true,
                schema: {
                    data: "Results"
                },
                transport: {
                    read: {
                        type: "get",
                        dataType: "json",
                        url: "/cis.svc/Search/Suggest",
                        contentType: "application/json",
                        data: {
                            q: function () {
                                return searchEditbox.val();
                            },
                            fuzzy: false,
                        },
                    },
                },
            },
```

### Reproduction of the problem
If put some search term (say, 123), it will show up a suggestion dropdown, with first auto selected. Then if you press enter key, the first one will be searched instead of term in input.

I was able to reproduce the bug in [dojo](https://demos.telerik.com/kendo-ui/autocomplete/serverfiltering), please check the gif.

![repro_authocomplete](https://user-images.githubusercontent.com/77701769/120377762-39279100-c326-11eb-911c-f58575846598.gif)

### Expected/desired behavior
If "highlightFirst: false" must never autoselect first item. Even the request from "filtering" method.

I have debbuged and found that [open flag](https://github.com/telerik/kendo-ui-core/blob/f348db26ce5317eccc95b459e5ee8c55a5f14021/src/kendo.autocomplete.js#L462) still false when it must be true to remove focus of first item. (probably race condition cause asynchronous operations)

### Environment

* **Kendo UI version:** "2021.2.511" and "2020.3.1118" checked
* **Browser:** Chrome  90.0.4430.212

**Comment by Dimitar-Goshev** [comment] 2021-06-02 10:03
@v-olg Thank you for this report. This issue is duplicate of the following one - https://github.com/telerik/kendo-ui-core/issues/3852 . I added more details to the initial issue and the reproduction gif and I increased its Priority. I am closing this issue as duplicate.

**Closed by Dimitar-Goshev** 2021-06-02 10:03 UTC
Labels: C: AutoComplete, jQuery2
