### ISSUE TITLE
RTL Kendo Grid Navigation Results in unexpected scrolling

### ISSUE THREAD

**Issue by behnam7171** [telerik/kendo-ui-core#6084] opened 2020-10-20 11:15 UTC
### Bug report

In the RTL grid, when navigation is set to true and there is horizontal scrolling in the grid when the user scrolls to the end, and clicks (either click or right-click, this happens on mousedown event) a cell, grid scrolls back to the right.

### Reproduction of the problem
https://dojo.telerik.com/oLuToGek/8

### Current behavior
by clicking a cell, the grid scrolls back to the initial position at the right.

### Expected/desired behavior
scroll stays at same position.

### Environment

Kendo UI version: tested on 2018+
jQuery version: any
Browser: Chrome 86, Edge(chromium) 86. --> CSSOM View Scroll Coordinates flag does not affect the bug and the bug still persists when this flag is disabled.
FireFox seems to be fine and the bug can not be produced.

**Comment by ag-petrov** [comment] 2020-10-20 11:39
Chrome altered the way scrolling is handled(in RTL cases) in the latest versions and we are aware of this. We even integrated a fix for this issue but it will be released with the upcoming service pack. That said I suggest upgrading after it becomes available. I will leave the item opened for now and will close it after the release is public and we have checked that the dojo works with it.

**Comment by behnam7171** [comment] 2020-10-20 12:51
@ag-petrov thank you for the reply. just wanted to say In this case, as I mentioned, disabling the flag does not resolve the issue, where as the RTL bug at https://github.com/telerik/kendo-ui-core/issues/6004 which I reported myself, was fixed by disabling the flag.
Thank you for your time.

**Comment by Dimitar-Goshev** [comment] 2020-10-21 12:58
@behnam7171 We have just released R3 2020 SP1 - 2020.3.1021 , which addresses the RTL Chrome change globally throughout Kendo UI. The issue is not reproducible on my side with it - https://dojo.telerik.com/@Dimitar-Goshev/INAtiJit

**Closed by Dimitar-Goshev** 2020-10-21 12:58 UTC
