### ISSUE TITLE
Kendo Grid Missing class "k-input-inner" for date input with Filter Customization

### ISSUE THREAD

**Issue by supertx2** [telerik/kendo-ui-core#6699] opened 2022-01-28 10:24 UTC
When using filter customization it's not adding the class k-input-inner to the input causing the field to not be correctly formatted
![image](https://user-images.githubusercontent.com/13727650/151529957-12ade823-3471-48da-b027-18fc689c58a3.png)

https://dojo.telerik.com/ENaSiHOn

Default behavior without filter customization:
![image](https://user-images.githubusercontent.com/13727650/151530380-ca6f570a-a698-48af-aa09-1c42d4583a61.png)

**Comment by MilenaCh** [comment] 2022-04-27 11:39
The issue is resolved in the latest official release, you can verify the current behavior [here](https://dojo.telerik.com/ENaSiHOn/3).

**Closed by MilenaCh** 2022-04-27 11:39 UTC
