### ISSUE TITLE
MultiCheck filter menu height is incorrectly calculated

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-ui-core#2477] opened 2016-11-24 12:15 UTC
### Bug report

Filter menu does not adjust height properly when rapidly entering a non-matching criteria.

### Reproduction of the problem
 Demo [official demo Kendo UI Grid filter checkbox menu ](http://demos.telerik.com/kendo-ui/grid/filter-multi-checkboxes)
1. Open Product Name filter menu and rapidly enter a random text

### Current behavior
The menu's popup container has enormous height although it's empty 
![image](https://cloud.githubusercontent.com/assets/5184468/20597881/df2773a6-b24e-11e6-917f-83fff4bd39c2.png)

### Expected/desired behavior
Resize the menu container just enough so it shows the content:
![image](https://cloud.githubusercontent.com/assets/5184468/20597905/067e0ec4-b24f-11e6-850d-527f391a659a.png)

### Environment

*  **Kendo UI version: 2016.3.1118**
* **jQuery version: 1.12.3**
* **Browser: IE11.x**

**Comment by Xizario** [comment] 2016-11-24 12:55
@joneff, need your help here.

I noticed that when the problem happens, if you inspect the element and remove the max-height from .k-multicheck-wrap the issue resolves, and if you set it again it continues to work correctly. It resolves as well if you remove the display=false of some item, and set it again.

Are you aware of any reflow problem in IE, that happens if UL element have no visible items?

**Comment by theOrlin** [comment] 2018-01-11 09:04
Closing as a duplicate of https://github.com/telerik/kendo-ui-core/issues/2898

**Closed by theOrlin** 2018-01-11 09:04 UTC
Labels: Bug, C: Grid, Kendo1, SEV: Low
