### ISSUE TITLE
Widget loses precision in rounding operations

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#132] opened 2014-06-20 10:13 UTC
Can be reproduced here: http://jsbin.com/tuyujubi/1/edit

As this behavior is expected due to the rounding operations, maybe it is a good idea to implement functionality for disabling the rounding and using fixed number of digits.

Ref. ID 830911

**Comment by filippomonti** [comment] 2015-01-19 13:48
the problem is raisen even with 15 decimals. Try "11.123456789012345"

**Comment by KirilNN** [comment] 2015-01-19 15:12
Hi @filippomonti 
The example shows a know JS limitation and the same can be reproduced without Kendo UI, like in this example:

http://dojo.telerik.com/@Kiril/oFaxO

We strive to improve this behavior, however this is not a trivial task and we can not commit to any deadlines .Of course, any pull request that solves this problem is appreciated!

**Comment by filippomonti** [comment] 2015-01-19 15:41
Hi @KirilNN 
I know :( the problem is related to the JS internal representation of the number. But it would be unthinkable that you could manage the data like a string (so without losing precision) and then convert to a number?

**Comment by scribbs** [comment] 2015-03-17 17:02
I would like to request the functionality proposed in the original post: "**maybe it is a good idea to implement functionality for disabling the rounding and using fixed number of digits**".  My concern is not with the precision of rounding after 16 digits passed the decimal, it is simply a need to limit user input to a certain number of digits without performing any rounding.  Ideally, when the specified number of digits is reached through keyboard input, any additional input would be prevented.

**Comment by ggkrustev** [comment] 2015-03-19 13:22
Hi @scribbs,
I would suggest you open a [UserVoice](http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback) discussion on the subject, as the functionality you are describing is an enhancement specifically in the NumericTextBox widget. 

This thread discusses concretely the rounding precision.

**Comment by scribbs** [comment] 2015-03-19 16:22
Hi Georgi,
Thanks for the reply.  I will open a UserVoice discussion.  I was pointed to
this particular discussion by the sales team when I asked about the need for
an option to turn off rounding and to limit user input to the decimals
specified for the NumericTextBox.

Thanks,
‹Steven
___________________
Steven Cribbs
Prevalent Software, Inc.
www.prevasoft.com

From:  Georgi Krustev <notifications@github.com>
Reply-To:  telerik/kendo-ui-core
<reply+00afdb4d290d083197bff4c2b211fbfbcf61e901ffaccc2592cf0000000111228fac9
2a169ce0227b158@reply.github.com>
Date:  Thursday, March 19, 2015 at 7:22 AM
To:  telerik/kendo-ui-core <kendo-ui-core@noreply.github.com>
Cc:  Steven Cribbs <scribbs@prevasoft.com>
Subject:  Re: [kendo-ui-core] Widget loses precision in rounding operations
(#132)


Hi @scribbs <https://github.com/scribbs> ,
I would suggest you open a UserVoice
<http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback
>  discussion on the subject, as the functionality you are describing is an
enhancement specifically in the NumericTextBox widget.

This thread discusses concretely the rounding precision.

‹
Reply to this email directly or view it on GitHub
<https://github.com/telerik/kendo-ui-core/issues/132#issuecomment-83561992>
.

**Comment by jayesh-jayakumar** [comment] 2016-01-20 15:34
Hello All,

I don't know whether this thread is still alive, but I want to pull your attention to another issue related to rounding. 

Today while testing, I inserted  the 12345678987654321 number to a kendo numeric textbox having configuration (min: 0, format: "#", decimal: 0). To my surprise on tabbing, the number got changed automatically to 12345678987654320. I also noticed the same behavior happens only when the 17th digit is an odd number (1,3,5,7,9). 

Is this a known issue or a bug with Kendo Numeric text box ?

**Comment by ggkrustev** [comment] 2016-01-20 15:56
I would suggest you check our [Known issue](http://docs.telerik.com/kendo-ui/controls/editors/numerictextbox/overview#known-limitations) help topic.

Also there is another issue (telerik/kendo-ui-core#423) related to `kendo.toString` method, which is actually used in the NumericTextBox.

As to this particular thread. It is marked as `won't fix`, as the problem is a limitation in JavaScript and not in the widgets.

**Closed by ggkrustev** 2016-01-20 15:56 UTC
Labels: Bug, C: NumericTextBox, Enhancement, SEV: Low, Wontfix
