### ISSUE TITLE
Spreadsheet absolute references inconsistently displayed in formula

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4393] opened 2018-07-19 12:50 UTC
### Reproduction of the problem
Reproducible in the [demos](https://demos.telerik.com/kendo-ui/spreadsheet/index).

### Current behavior
1. Select cell H5
2. Enter the following formula **=sum($A$5:A9)**
3. Press Enter key. Enter the same formula in cell H6. 

### Expected/desired behavior
Both cells display the same formula that was entered: **=sum($A$5:A9)**

###Actual behavior
H5 displays **=sum($A$5:A9)**
H6 displays **=sum(A9:$A$5)**

### Environment

* **Kendo UI version:** 2018.2.620
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by mishoo** [comment] 2018-08-06 08:57
Duplicate of telerik/kendo-ui-core#4278 (fixed).

**Closed by mishoo** 2018-08-06 08:57 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: Low
