### ISSUE TITLE
If two Grids are on the same page have aggregates for a field with the same name an ArgumentException is thrown.(MVC wrappers)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3582] opened 2017-09-14 10:22 UTC
### Bug report

If two Grids are not the page and have aggregates for fields with the same name an ArgumentException is thrown.

### Reproduction of the problem

More information with detailed description, steps and runnable example can be found in ticket: 1129790

The workarounds are:

1) Add the hidden field to the grid (to the model) and aggregate sth (for ex: sum) for this field. (if you have more than 2 grids with such problem, don't forget that these hidden fields must have different names, otherwise, it won't help)
2) You can rename a field in one of the grids

* **Browser:** [all]

**Comment by Thorlake** [comment] 2017-11-03 07:03
Sorry guys that I distract you, but almost two months have passed and no one has assigned this ticket.
For me it's a fatal error :/ Of course I've fixed this error and recompiled Kendo MVC project for myself, nevertheless I can't predict future problems of my fix (I suppose there are no problems, but... it's better to check your version too)
p.s. I just moved "rwLock.UpgradeToWriterLock" from method "CreateDynamicClass" in method "GetDynamicClass" (class "ClassFactory") before checking a key in dictionary with name "classes"
I don't know how other people work with current Kendo MVC (btw, this error still exists in new versions)
I have N grids with similar aggregates and unfortunately even their models are equal 

Looking forward to your reply, have a nice day

**Comment by Alex-Bubblemaster** [comment] 2017-11-06 11:05
Also encountered in the thread with ID 1138380. raising the priority.

**Comment by jrummell** [comment] 2018-09-20 21:57
I'm still seeing this in 2018.2.620.545

**Comment by Alex-Bubblemaster** [comment] 2019-01-07 15:00
@jrummell - I am sorry we did not see your comment here. It would have been better to report this in the support channels so we could have reacted quicker.

Reported in ticket with ID: 1381826 

I am able to reproduce this with R1 2018. It is easy to miss this one when testing because the error is thrown only the first time. Steps:

- Create a project with two grids which have the same aggregate names
- Copy paste this grid, changing only its name, e.g. "GridTwo"
- Run the project (clean run from scratch rather than Ctrl + F5)

![image](https://user-images.githubusercontent.com/10980842/50774826-261b4e80-129d-11e9-9342-9eba9d304782.png)

```
@(Html.Kendo().Grid<AjaxGridWithSelection.Models.OrderViewModel>()
                      .Name("GridOne")
                      .HtmlAttributes(new { @style = "height: 80%" })
                     .Columns(columns =>
                     {
                         columns.Bound(p => p.OrderID).Filterable(false);
                         columns.Bound(p => p.Freight);
                         columns.Bound(p => p.ShipName);
                         columns.Bound(p => p.ShipCity);
                     })
                     .DataSource(ds => ds
                         .Ajax()
                         .PageSize(20)
                         .Read(read => read.Action("Orders_Read", "Grid"))
                        .Model(m=>m.Id("OrderID"))
                     .Aggregates(aggregates =>
                     {
                         aggregates.Add(a => a.Freight).Sum();
                     })
            )
            .Scrollable()
            )
```

### Workaround

- Set GridTwo with `AutoBind(false)`
- Add dataBound event handler and read GridTwo data source

```
 @(Html.Kendo().Grid<OrderViewModel>()
       .Name("GridOne")
       .Events(e=>e.DataBound("onDataBound"))
 )

 @(Html.Kendo().Grid<OrderViewModel>()
       .Name("GridTwo")
       .AutoBind(false)
 )
<script>
    function onDataBound(e){
        $("#GridTwo").data("kendoGrid").dataSource.read();
    }
</script>

```
- Use models with different names

**Closed** 2019-02-14 16:32 UTC
Labels: Bug, C: Grid, Kendo1, Priority 3, S: Wrappers (ASP.NET MVC), SEV: Medium

**Comment by FransiskusAriyanto** [comment] 2023-10-18 18:38
I'm still seeing this in 2023
