### ISSUE TITLE
Virtualized MultiColumnComboBox Row Border Misaligned

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6770] opened 2022-03-15 14:42 UTC
### Bug report

The Virtualized MultiColumnComboBox is having an appearance issue with its row borders with LESS themes.

### Reproduction of the problem

1. Visit [this Progress Kendo UI Dojo](https://dojo.telerik.com/@PMcDonou/ADucohem)
2. Open the DropDown

### Current behavior
The border's alignment appears off:
![image](https://user-images.githubusercontent.com/19593058/158401964-6b3299e0-0a0c-42af-84bc-636c8f816e4a.png)

### Expected/desired behavior
The MultiColumnComboBox should appear like it does with [the SASS themes.](https://demos.telerik.com/kendo-ui/multicolumncombobox/virtualization?autoRun=true&theme=bootstrap-main)

### Environment

* **Kendo UI version:** 2022.1.301
* **jQuery version:** All supported versions
* **Browser:**  all

**Comment by magdalenaan** [comment] 2022-10-03 11:20
The issue is reproducible in SASS and LESS themes as well. For SASS themes is less visible because of missing bottom borders of list items. We are not able to fix the appearance in themes because of specific rendering approach for virtualization. To resolve the issue it is necessary to make an investigation of order of list items DOM elements when virtualization is used.

**Comment by sspasova** [comment] 2024-02-21 13:22
I am closing this issue because it is no longer reproducible using Kendo UI 2024.1.130. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/IqecUcaF

**Closed by sspasova** 2024-02-21 13:22 UTC
Labels: Bug, SEV: Low, jQuery, C: MultiColumnComboBox, Triaged
