### ISSUE TITLE
Root Menu item is not focused after leaving a submenu with keyboard (Esc or arrow keys) in IE and Edge

### ISSUE THREAD

**Issue by sebastian-webstar** [telerik/kendo-ui-core#4876] opened 2019-03-01 06:05 UTC
### Bug report
If you navigate in Internet Explorer (tested with IE 11) in the Kendo Menu (https://demos.telerik.com/kendo-ui/menu) by keyboard and step into a sub-menu you always see the focused element because it has an outline. 
But if you leave the submenu by pressing ESC or the left/right arrow key, the "focus" is lost and no main-menu item has an outline. If you press the right arrow key (or down arrow key for vertical orientated menus) the first main menu item gets the "focus" and you can see the outline. 

In FF/Chrome all is fine and after leaving the sub menu the corresponding main menu item has the focus (appears outlined) immediately.

### Reproduction of the problem
1. Open https://demos.telerik.com/kendo-ui/menu/index in IE 11 / Edge
1. Click in the "Search demos" text input
1. Step with tab key to the menu (the first main menu item has now the focus and has an outline)
1. Navigate with right/left arrow keys to an main menu item and step into this by pressing Enter or the down arrow key
1. Navigate in this sub menu with the down or up arrow keys
1. Leave the sub menu by pressing ESC or right/left arrow key

### Current behavior
No main menu item has the focus. If you navigate by pressing the right arrow key the first main menu item gets the focus

### Expected/desired behavior
Like in FF & Chrome the corresponding main menu item gets the focus.
- if you leave the sub menu with ESC the main menu item of this sub menu gets the focus 
- if you leave the sub menu by pressing the left/right arrow key the next main menu item gets the focus

### Environment
* **Kendo UI version:** 2021.2.511
* **Browser:** IE 11, Edge 40

**Comment by Dimitar-Goshev** [comment] 2023-01-19 13:14
Closing this issue as IE is not supported since R1 2023.
And Microsoft Edge is now based on Chromium engine and its current version is 108. The issue is not reproducible with it.

**Closed by Dimitar-Goshev** 2023-01-19 13:14 UTC
Labels: Bug, C: Menu, C: ContextMenu, SEV: Medium, jQuery
