### ISSUE TITLE
Rating is unresponsive when nested in a dynamically added Wizard step

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6029] opened 2020-09-21 09:42 UTC
### Reproduction of the problem
1. Run the project attached on in 16.9.2020 in Ticket ID: 1484793
2. Check the "Add 3rd Step" checkbox
3. Navigate to the 3rd step - the Rating is unresponsive and its value cannot be changed 

### Current behavior
The Rating is unresponsive. 

### Expected/desired behavior
The Rating works properly.

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by veselints** [comment] 2020-10-20 13:41
The described is not a bug. The issue is present because the DatePicker and the Rating widgets are first initialized and after that their HTML gets transferred from the `<div id='page3-container'>` element to become a Wizard Step content. The logic should be altered, so that initially the deferred call initializes only the deferred widgets present only on the loaded steps (Step 1 and Step 2):
```
@Html.Kendo().DeferredScriptsFor("SelectedLocationJobTitles")
@Html.Kendo().DeferredScriptsFor("SelectedLocationJobDescriptions")
@Html.Kendo().DeferredScriptsFor("IsPublicView")
```

Later, upon execution of the logic that adds Step 3 to the Wizard, the initialization of the widgets present on that step should be performed:
```
if (ele.checked && wizardJobApplication._steps.length < 3) {
    var step3 = {
        title: "Page 3",
        contentId: "page3-container"
    }
    wizardJobApplication.insertAt(2, step3);

    ...
    resetButtonElement.remove();

    @Html.Kendo().DeferredScriptsFor("EvaluationRating", false)
    @Html.Kendo().DeferredScriptsFor("EvaluatedOn", false)
}
```

**Closed by veselints** 2020-10-20 13:41 UTC
Labels: Bug, C: Rating, C: Wizard, FP: In Development, Kendo2, S: Wrappers (ASP.NET Core), SEV: Medium
