### ISSUE TITLE
Menu items do not collapse properly

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7472] opened 2023-08-09 11:56 UTC
### Bug report

When the [hoverDelay](https://docs.telerik.com/kendo-ui/api/javascript/ui/menu/configuration/hoverdelay) of the Menu widget is enabled the items of the Menu do not collapse properly after their initial expand.

This bug is a regression from the behavior in version 2023.1.425.

### Reproduction of the problem
1. Run [this Dojo](https://dojo.telerik.com/@Stoyan/aTAxiDeL)
2. Hover fast over multiple items
   or
1. Run the [TagHelper Demo](https://demos.telerik.com/aspnet-core/menu/tag-helper)
2. Hover fast over the **Using model binding** Menu's items

Behavior occurs only on first expand of the items.
If the behavior isn't reproducible at initially refresh the page and try again.

### Expected behavior
Menu Items that aren't currently hovered over should collapse.

### Current behavior
Menu Items remain expanded.

### Environment

* **Kendo UI version:** 2023.2.606

**Comment by germaine-robinson** [comment] 2023-08-09 15:21
Just for clarification to avoid any confusion, we weren't able to reproduce the bug (multiple menus remaining open at the same time) in that [Dojo](https://dojo.telerik.com/@Stoyan/aTAxiDeL) example mentioned in "Reproduction of the problem" Step 1 above. 

But, as mentioned in our original support ticket ([here](https://www.telerik.com/account/support-center/view-ticket/1619073)) and as you mentioned in Step 3 above, when using the [Telerik UI for ASP.NET Core Menu TagHelper](https://demos.telerik.com/aspnet-core/menu/tag-helper?_ga=2.78348436.160135383.1691418993-454242989.1648584953&_gl=1*1a9cwco*_ga*NDU0MjQyOTg5LjE2NDg1ODQ5NTM.*_ga_9JSNBCSF54*MTY5MTU5MDkxMC40MC4xLjE2OTE1OTI2OTcuNjAuMC4w) demo page the bug is consistently reproducible.  I also included screenshots (below) of the bug from the original Support Ticket using this Menu TagHelper demo page, in case they help with identifying/troubleshooting the bug.

Also, the Kendo UI version we were using was 2023.2.606.  To our knowledge, this was the version that introduced the bug.

### Screenshot 1:
![Menu TagHelper Screenshot 1](https://github.com/telerik/kendo-ui-core/assets/81763897/ec29b10d-0430-45e0-b3e9-2199f0203dda)

### Screenshot 2:
![Menu TagHelper Screenshot 2](https://github.com/telerik/kendo-ui-core/assets/81763897/cc3642a3-1ea2-4450-bd52-a12d70ed4751)

**Comment by aaron-kruse** [comment] 2023-08-10 13:40
Is there any sort of timeline for a fix for this? Is this something you guys are actively investigating since this is a bug/regression, or is this just in the backlog and needs enough "votes" before it gets some more attention?

I'm just trying to get a little more information so we know what to expect and can determine how we want to proceed. We had to roll back after attempting to update to 2023.2.606 and this issue is still present in 2023.2.718, so this is currently preventing us from installing updates. Is there any chance a fix might be included in the upcoming August or October updates, or are we looking at next year at best?

**Comment by alestoya** [comment] 2023-10-26 10:54
Reported in 1628289

**Comment by ag-petrov** [comment] 2023-11-03 08:20
@germaine-robinson thank you for the clarification. For tracing purposes I am linking the opened issue in regards of the hover delay and I am closing this one as its initial idea were the multiple menus being opened 

Related issue - https://github.com/telerik/kendo-ui-core/issues/7573

**Closed by ag-petrov** 2023-11-03 08:20 UTC
Labels: Bug, C: Menu, SEV: Low, jQuery, Priority 5, FP: Planned
