### ISSUE TITLE
Spreadsheet's Copy toolbar button copies the entire html for the clipboard

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2705] opened 2017-02-01 13:30 UTC
### Bug report

Reported in Ticket ID: 1086909

### Reproduction of the problem

1. Selected a cell to copy
2. Click the Copy toolbar button
3. Paste the copied content, using mouse (Paste) or keyboard (Ctrl + V)

see video:
[https://www.screencast.com/t/zCWljwHx75](https://www.screencast.com/t/zCWljwHx75)

### Current behavior

The html, containing the cell style, format, value etc is pasted

### Expected/desired behavior
Should paste only the value of the coped cell

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment] 2017-08-25 09:01
Duplicate of: https://github.com/telerik/kendo-ui-core/issues/1837

**Closed by Dimitar-Goshev** 2017-08-25 09:01 UTC
Labels: Bug, C: Spreadsheet, SEV: Medium
