### ISSUE TITLE
k-state classes are not updated according to the new rendering and exists in some of the itemsTag.java files

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7094] opened 2022-10-24 08:46 UTC
### Bug report

The 'k-state-' classes are supposed to be updated when UI for JSP is used. However, the classes are still present in some of the ItemsTag.java files, thus the classes are added to the rendering. 

### Reproduction of the problem
1. Run the JSP demos locally 
2. Open a TabStrip demo and inspect it

### Current behavior
Both classes '_k-state-active_' and '_k-active_' are applied ([screencast](https://www.screencast.com/t/Jhm4Vrpx1tA)).
Other classes that appear in the ITemTag.java files are _k-state-disabled_ and _k-state-selected_. Components that should be revised are - - ContextMenu, 
- Menu, 
- PanelBar,
- TreeView

### Expected/desired behavior
The state classes should be upgraded when using the UI for JSP wrappers according to the new rendering. 
https://docs.telerik.com/kendo-ui/styles-and-layout/components-rendering-overview#state-classes

### Environment

* **Kendo UI version:** 2022.3.913
* **Browser:** [all ]

**Comment by nelito987** [comment] 2022-10-28 06:22
The issue can be replicated also with the PHP Wrappers ([screencast](https://www.screencast.com/t/NkkxdmEkKJ))
Reported in ticket: 1584278

**Comment by Dimitar-Goshev** [comment] 2022-11-15 11:12
Duplicate of https://github.com/telerik/kendo-ui-core/issues/6995

**Closed by Dimitar-Goshev** 2022-11-15 11:12 UTC
Labels: C: Menu, C: PanelBar, C: TabStrip, C: ContextMenu, SEV: Medium, C: TreeView, S: Wrappers (Java), S: Wrappers (PHP), jQuery2, Priority 1, FP: Unplanned
