### ISSUE TITLE
Icons are missing in the components when custom script is generated with gulp

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7747] opened 2024-03-02 14:33 UTC
### Bug report

Icons are missing in the components when a custom script is generated with Gulp

### Reproduction of the problem
1. Follow the steps described in the link here - https://github.com/telerik/kendo-ui-core?tab=readme-ov-file#building-kendo-ui-core
2. Create a custom script for DropDownList or Window `npx gulp custom -c window,dropdownlist`
3. Try to load the script and create the components

### Current behavior
The Window is missing the icons and the actions are not working. The DrpDownList works as expected, but the arrow icon is not visible

### Expected/desired behavior
The components should work as expectedwhen custom scirpt is created

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all  ]

**Comment by pepinho24** [comment] 2024-03-05 11:39
There might be other components with the same issue, review if we have many components missing the icons dependency and check if adding the dependency in kendo.core.js is a viable solution (it might require removing the explicit dependency import in the file of the component).

**Comment by gdenchevprog** [comment] 2024-09-03 11:24
This seems to be no longer reproducible. I am closing the issue.
In case somebody else comes across the same problem using the latest version, please leave a comment with the details here.

**Closed by gdenchevprog** 2024-09-03 11:24 UTC
Labels: Bug, SEV: Medium, jQuery
