### ISSUE TITLE
cell connection in Spreadsheet is not working when the sheet contains 1.0 in the name

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#6213] opened 2021-01-05 13:26 UTC
### Bug report

cell connection in Spreadsheet is not working when the sheet contains 1.0 in the name

### Reproduction of the problem
download the file from ticket - 1500102 
open our demo - https://demos.telerik.com/kendo-ui/spreadsheet/index
open the file from the ticket in the Kendo Spreadsheet

### Current behavior
cell F17 is not connected with cell B12 from the second sheet

### Expected/desired behavior
cell F17 is  connected with cell B12 from the second sheet

note: if the name of the sheet is changed to something different than 1.00 for example 'A' the cells are connected
### Environment

* **Kendo UI version:2020.3.1118

**Comment by veselints** [comment] 2021-01-07 09:30
The issue in this case is the format in which the external Sheet cell reference is specified. If you review the xlsx file you will notice the following cell definition is present in the `xl/worksheets/sheet1.xml`:
```
<c r="F17" s="11" t="str">
    <f>=(1.0INTERMEDIATECIVILTECH!B11)</f>
...
```
while it should be either:
```
<c r="F17" s="11">
    <f>('1.0INTERMEDIATECIVILTECH'!B11)</f>
...
```
or:
```
<c r="F17" s="11">
    <f>'1.0INTERMEDIATECIVILTECH'!B11</f>
...
```

Here is the appropriate Excel documentation section:
https://support.microsoft.com/en-us/office/create-or-change-a-cell-reference-c7b8b95d-c594-4488-947e-c835903cebaa

Note the last line of the examples table:
```
=Sheet2!B2 | Cell B2 on Sheet2 | The value in cell B2 on Sheet2.
```

Moreover, the file fails validation in the [Open XML SDK 2.5 Productivity Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30425).

Having that said, the problem is caused by the xlsx file contents and not by a bug in the Spreadsheet. Hence, I am closing this issue.

**Closed by veselints** 2021-01-07 09:30 UTC
Labels: Bug, C: Spreadsheet, FP: In Development, Kendo2
