### ISSUE TITLE
Scheduler RecurrenceEditor is not localized in adaptive rendering

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2427] opened 2016-11-08 12:07 UTC
### Bug report
When the **mobile** configuration option is set to true, "phone" or "tablet" the recurrence editor is not localized. 

### Reproduction of the problem
Can be reproduced in the localization [demo](http://demos.telerik.com/kendo-ui/scheduler/localization)(**mobile** needs to be set). [Screenshot](https://www.screencast.com/t/AGbuTrRuh1Sb)

[DOJO](https://dojo.telerik.com/iHOdaZUP)

### Current behavior
The messages in the recurrence editor are not localized

### Expected/desired behavior
The messages in the recurrence editor are localized just like the other messages in the Scheduler's editor. 

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2020-05-22 10:37
The issue is fixed. Moving it to Done. We should close it once we merge the fixes branch.

**Closed** 2020-06-02 15:06 UTC
Labels: Bug, C: Scheduler, FP: Completed, Kendo2, Next LIB, SEV: Medium
