### ISSUE TITLE
 Virtualized MultiSelect shows loading and skips items when scrolling

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2959] opened 2017-03-24 09:50 UTC
### Bug report
Virtualized MultiSelect shows loading and skips items when scrolling

~~http://dojo.telerik.com/anAsINUC~~
[Dojo with corrected Id field casing - 2019.3.917](https://dojo.telerik.com/@Dimitar-Goshev/OZaPURuh)
Click on the control and scroll down

### Current behavior
Some of the items are skipped and some are displayed with loading..

### Expected/desired behavior
All items are displayed

Note: The issue is not reproducible with 2016.1.112
~~https://dojo.telerik.com/AleDOyUp/3~~
[Dojo with corrected Id field casing - 2016.1.112](https://dojo.telerik.com/@Dimitar-Goshev/iMUGijeZ)

### Environment
* **Kendo UI version:** 2019.3.917

**Comment by harlankoehn** [comment] 2017-03-24 13:25
I've confirmed that this problem was introduced in version 2016.2.607. Version 2016.2.504 works correctly.

I might have to dig into this issue further myself to see that it gets fixed in a timely manner. If any of the developers have any advice on what might be the issue please let me know. I'm wondering if it might be in the throttling.

**Comment by harlankoehn** [comment] 2017-03-24 17:40
Well, I haven't figured out just where the problem is but I've found a work-around that will work for now. In Kendo UI Core, kendo.virtuallist.js line 1326 I've changed the _whenChanged: function to look like this:

`        _whenChanged: function(getter, callback) {
            var current;

            return function(force) {
                var theNew = getter(force);

                if (theNew !== current && theNew.items[0].item != null) {
                    current = theNew;
                    callback(theNew, force);
                }
            };
        },`

**Comment by veselints** [comment] 2019-10-08 14:09
The issue is caused by the Data passed to the widget. Testing the same with generated Data results in the expected behavior of the MultiSelect:
https://dojo.telerik.com/AleDOyUp/6

**Comment by Dimitar-Goshev** [comment] 2019-10-11 10:15
@veselints It seems working on your Dojo, because accidentally it uses Kendo UI 2016.1.112, which is before the issue starts to appear.
The following [DOJO](https://dojo.telerik.com/@Dimitar-Goshev/ifEcAtor) uses Kendo UI **2019.3.917** and the issue is reproducible.

### Current behavior
Tag 1972, Tag 1983 and Tag 1985 are selected. Expanding the dropdown, these items are NOT loaded and showing as loading

### Expected behavior
Tag 1972, Tag 1983 and Tag 1985 are selected. Expanding the dropdown, these items are loaded and showing as selected.

As a side note, as you mentioned offline, the initial examples mismatch in Id field casing - in the data they are all listed as "ID", instead of "Id". That is why on both Dojo snippets from the initial logging of the issue, there are no selected items in the MultiSelect, when running them. So I updated these Dojos with fixed Id casing.

**Comment by veselints** [comment] 2019-10-14 15:40
@Dimitar-Goshev Going further on with testing, I noticed that the issue is only present if the AngularJS `$q` is used to return a promise which resolves with the Data:
```js
return $q(function(resolve, reject) {
    resolve($scope.tagData);
});
```

The problem is not present either when using the browser Promise() object, or when using the jQuery.deffered. Here is a modified Dojo:
https://dojo.telerik.com/OgaZejud/4

Again, that leads to an issue with the way data is passed to the DataSource (using a fake promise-like object) and not to the widget (or the DataSource) itself.

**Comment by Dimitar-Goshev** [comment] 2019-10-17 10:32
@veselints Thank you for researching this issue. I confirm that the recommended approach for fixing this issue is using a promise or jQuery.deferred instead of AngularJS $q. The following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/AguSoTEc) works as expected with both approaches.

**Closed by Dimitar-Goshev** 2019-10-17 10:32 UTC
Labels: Bug, C: MultiSelect, F: AngularJS, FP: In Development, Kendo2, Priority 5, SEV: Medium, Triaged
