### ISSUE TITLE
Long running script evaluation of 6 to 7 seconds, when loading kendo.all.min.js in IE 11, if "Disable script debugging" setting is checked

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3670] opened 2017-10-11 12:38 UTC
### Bug report
 Long running script evaluation of 6 to 7 seconds, when loading kendo.all.min.js in IE 11. It is present in the following versions:
* IE 11.0.9600.18792 (Windows 7);
* IE 11.103.10586.0 (Windows 10);
* IE 11.1106.10586 (Windows 10);

The same script evaluation is executed for around 600 ms in:
* IE 11.540.15063.0 (Windows 10);
* IE 11.0.9600.18793 (Windows 8.1);
* IE 11.0.9600.17801 (Windows 7).

**NOTE:** When tested with the IE versions, which replicate the issue, it is NOT reproducible, if **Disable script debugging** checkbox is unchecked in **IE Advanced settings**. The checkbox is checked by default:
![image](https://user-images.githubusercontent.com/6614183/31536687-34004c42-b008-11e7-9835-ca9b79a3c706.png)

The same setting does not seem to affect performance when tested with the second group of IE versions. Checking or unchecking this setting does not lead to such performance difference.

### Reproduction of the problem
Open any Kendo demo (e.g. kendoui.for.jquery.2017.3.913.commercial\examples\dialog\predefined-dialogs.html) with one of the above versions of IE 11 and capture the performance (UI Responsiveness). The Script evaluation of kendo.all.min.js takes 6 to 7 seconds on initial load.

This problem is not related to the CDN, as it could be observed when loading local scripts too.

The issue is reproducible with a local version of Kendo UI demos. Extract a distribution zip, e.g. kendoui.for.jquery.2017.3.913.commercial.zip , then go to examples\dialog\predefined-dialogs.html demo or examples/button/index.html demo and load it in IE. Reproduction video - https://www.screencast.com/t/jKtXaYuZj (open it in IE).

### Environment
* **Browser:** [ IE 11 version 11.0.9600.18792 (Windows 7), 11.0.9600.18793 (Windows 8.1) or 11.103.10586.0 (Windows 10) ]

**Comment by kemmis** [comment] 2017-10-20 13:08
+1 
I am experiencing this issue as well. Using version 2017.3.913 from here: https://kendo.cdn.telerik.com/2017.3.913/js/kendo.all.min.js

**Comment by kendouser** [comment] 2017-10-25 08:04
Dear veselints.
I have the same problem as above.
I have tested The 2017.3.1018 version, but the issue is same thing.
Is there any other solution without changing the above  Internet Option Advanced Setting?

if setting is not checked "Disable script debugging", there are many pop-up windows.
so we are always supposed to check in.
 
Thank you for your support

**Comment by Dimitar-Goshev** [comment] 2017-10-31 08:25
Dear @kendouser ,
I am afraid that currently there is no workaround for this issue. I am increasing its Priority now.

**Comment by mariozam** [comment] 2017-11-02 13:56
Hi Dimitar,

What does increasing the priority mean? can you tell me when this issue will be resolved?

Best Regards,

**Comment by ivanchev** [comment] 2017-11-02 14:11
We started working on it, moving other items on the agenda aside. As for when it will be fixed - it cannot be said until we find the issue first.

**Comment by shy2020** [comment] 2017-11-09 07:40
Hi Ivanchev,

I have the same difficulty about long running script on IE.
I hope you can find the issue and fix the problem soon.

I will look forward to your reply.

Thanks & best regards,

**Comment by ivanchev** [comment] 2017-11-09 09:45
We are still working on this, but are having issues with reliably reproducing the issue, on every version of IE 11 we test on. Any additional information by the community would be beneficial to resolving this, or at least finding a way to circumvent it. For instance any additional finding on what versions of Windows and IE are the people reproducing the issue using, and is the issue apparent after a specific Windows update?

**Comment by ivanchev** [comment] 2019-03-21 10:02
We've spent a good amount of time on the issue, but to no avail. And since it only affects a very specific small amount of IE browsers, and there hasn't been any further input from the community for over a year, I'm closing it as Won't fix.

If some new information that helps track this down pops up, we can evaluate it and reopen the issue if needed.

**Closed by ivanchev** 2019-03-21 10:02 UTC
Labels: Enhancement, Kendo1, Kendo2, Priority 5, SEV: Medium
