### ISSUE TITLE
Spreadsheet Date type fields validation Issue 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5524] opened 2020-01-17 09:25 UTC
### Bug report

Thre is a validation issue with the Date type fields if the validation range parameters are referenced from another cell.

### Reproduction of the problem
1. Open [this demo](https://demos.telerik.com/kendo-ui/spreadsheet/index)
2. Import attached xlsx file. 
[Date Validation Issue.xlsx](https://github.com/telerik/kendo-ui-core/files/13674137/Date.Validation.Issue.xlsx)

4. There are two date cells (B1 & B2), B2 has a data validation (Date between B1 to ToDay)
5. Try to edit the date using the calendar icon from B2. An empty calendar appears

Note: If the data validation is defined as in the below screenshot(remove reference of B1 and put hard coded date) the calendar appears correctly.
![download](https://user-images.githubusercontent.com/41293735/72600189-d5ace700-391b-11ea-9979-258d7b839b89.png)

### Current behavior
The calendar that appears when trying to change the value of the Date cell is blank. 

### Expected/desired behavior
The calendar that appears when trying to change the value of the Date cell should appear correctly no matter if there is a validation set for this field. 

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by sspasova** [comment] 2023-12-15 07:16
Closing this issue because it is no longer reproducible using Kendo UI version 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/ePAGoBUH

**Closed by sspasova** 2023-12-15 07:16 UTC
Labels: Bug, SEV: Low, C: Spreadsheet, jQuery, FP: Unplanned, Triaged
