### ISSUE TITLE
Copied negative percentage value from excel is pasted as string in the Spreadsheet

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4598] opened 2018-10-19 11:41 UTC
### Bug report

When trying to copy/paste a negative percentage value from MS Excel to Kendo Spreadsheet - it is pasted a string value. This is not the case in the same scenario, but with a positive percentage value

### Reproduction of the problem
1. Create an excel and have a certain cell with percentage format.
2. Fill a negative value in the cell
3. Paste it in Kendo Spreadsheet

Video: [https://monosnap.com/file/60h13jUJd4u79xlzK1NgErnOj1Bumb](https://monosnap.com/file/60h13jUJd4u79xlzK1NgErnOj1Bumb)

### Current behavior
The pasted value is in a string format

### Expected/desired behavior
The pasted value should be in number format

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by mishoo** [comment] 2018-10-29 11:41
The same happens even when you input a negative percent value in the cell editor, that is, the issue isn't about copy/paste but about parsing negative percent values.  Pushed a fix, it should now be able to parse various number formats followed by percent, e.g.: `-20%`, `-20 %`, `1,234.50 %` etc.

**Closed** 2018-10-29 16:59 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: High
