### ISSUE TITLE
Incorrect Spreadsheet validation dropdown auto-resize

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3027] opened 2017-04-07 10:50 UTC
### Bug report
The Spreadsheet validation dropdown does not set its width properly when reopened after closing another validation dropdown.

### Reproduction of the problem
Sample [dojo](http://dojo.telerik.com/oZAxA). 
1. Click B2. Open the validation dropdown. "United States" is not wrapped. [Screenshot](https://www.screencast.com/t/qHl1dlcyrp).
2. Click on A2. Open its validation dropdown.
3. Click on B2 again. Open its dropdown. "United States" is wrapped. [Screenshot](https://www.screencast.com/t/GgvKzQ0Rm).

### Current behavior
The validation dropdown's width is affected by previously opened validation dropdowns. 

### Expected/desired behavior
The validation dropdown's width is correctly calculated and is not affected by opening other dropdowns. 

A possible workaround is to apply **white-space: nowrap** to the dropdown's li elements: 
    .k-list .k-item {
      white-space: nowrap;
    }

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mparvanov** [comment] 2019-10-25 12:49
Tested with 2019.3.1023  - http://dojo.telerik.com/UbaJAsAN/2

- The issue is reproducible with 2017.1.223 in the original Dojo, but not reproducible with 2019.3.1023 in Firefox.

- In Chrome, IE and Edge  the validation dropdown does not set its width properly when reopened both initially and after closing another validation dropdown.

**Closed** 2020-11-02 12:44 UTC
Labels: Bug, C: Spreadsheet, FP: In Development, Kendo2, Priority 1, SEV: Low
