### ISSUE TITLE
Grid columnReorder event oldIndex is incorrect when using locked group columns

### ISSUE THREAD

**Issue by metoule** [telerik/kendo-ui-core#5974] opened 2020-08-17 16:01 UTC
### Reproduction of the problem

When a grid has locked grouped columns, the `oldIndex` property of the `columnReorder` event is incorrect: the index includes the number of columns inside the locked group columns (for example, if there are 3 columns inside the locked grouped columns, the index is shifted by 3). This is probably due to `flatColumnsInDomOrder`, which first flattens the locked columns before flattening the non-locked columns.

Repro: 

https://dojo.telerik.com/ImOvamUd

### Current behavior
_(optional)_

In the above example, when ordering the column `Drinks` before the column `Food`, it outputs `undefined 1 4` (field, new index, old index) while there are only 3 grouped columns.

### Expected/desired behavior
Explain what the expected behavior of the functionality is:

It should output `undefined 1 2`

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by ag-petrov** [comment] 2021-06-16 11:48
Indeed the behavior is caused by the flattening of the columns structure. When working with multi-column headers this is to correct approach to index the columns. Even if the indexes are changed as stated in the expected output the end developer will not be able to directly get the columns using them(you may be able only for a top level but not for nested levels and there may be 2,3 or more).  Moreover the index logic is really old and anyone who depended on it will experience a break in the functionality if we alter it to match the levels structure. Considering the aforementioned I am marking this as wont fix

**Closed by ag-petrov** 2021-06-16 11:48 UTC
Labels: Bug, C: Grid, FP: In Development, FP: Unplanned, Priority 1, SEV: Low, Won't Fix, jQuery1
