### ISSUE TITLE
Upload events are not exposed

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5933] opened 2020-07-21 06:23 UTC
### Bug report

Relevant Upload events can be triggered through the FileManager widget directly (like [upload](https://docs.telerik.com/kendo-ui/api/javascript/ui/upload/events/upload)). 

### Reproduction of the problem
Upload events are missing from the wrapper components.

### Workaround
Handling the events with client-side code: 

```
@(Html.Kendo().FileManager().Name("filemanager")
    ...
)

<script>
    $(document).ready(function () {
        var filemanager = $("#filemanager").getKendoFileManager();

        filemanager.upload.bind("upload", function (e) {
             e.data = {
                additionalInfo: "additionalInfo"
            };
        })
    })
</script>

```

**Comment by Dimitar-Goshev** [comment] 2020-07-21 14:06
Duplicate of #5841

**Closed by Dimitar-Goshev** 2020-07-21 14:06 UTC
Labels: Bug, C: FileManager, S: Wrappers (ASP.NET Core), S: Wrappers (ASP.NET MVC), SEV: Medium
