### ISSUE TITLE
Cannot prevent image that is dragged from filesystem into Editor from being added to widget

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6565] opened 2021-09-14 13:49 UTC
### Bug report

We are trying to prevent users from dropping an image file from their computer directly onto the Editor with Firefox.  When this happens the browser converts the image into a uri encoded version of the image.  When we define a custom PasteCleanup function to handle this, the Editor will sometimes work as expected but other times it will throw an error when trying to execute the function.  This seems to be random after each page load. 

### Reproduction of the problem

1. Open [this Dojo](https://dojo.telerik.com/IrOzOYAM) with Firefox
2. Run the Dojo and drag and drop an image from your machine

Please note that the reproduction of the error is inconsistent. However the CustomPasteCleanUp doesn't prevent the addition of the image, nor does the prevention of the Drop event.

[Screen capture](https://www.screencast.com/t/FxM2pZzPF) of reproduction in ASP .NET Core.
[Screen capture](https://www.screencast.com/t/rr0pu9nRsJ) of reproduction in Dojo.
More information about issue and reproduction available in ticket: 1534730

### Current behavior
An image file that is dragged and drop by the user to the Editor is always added to the widget.

### Expected/desired behavior
The current behavior should be preventable and an error must not occur.

### Environment

* **Kendo UI version:** 2021.2.616
* **Browser:** [ Chrome 93  | Firefox 92 ]

**Comment by sspasova** [comment] 2024-01-26 12:46
I am closing this issue because it is no longer reproducible.

**Closed by sspasova** 2024-01-26 12:46 UTC
Labels: Bug, SEV: High, C: Editor, FP: Unplanned
