### ISSUE TITLE
ListView paging is not applied when a new item is created

### ISSUE THREAD

**Issue by yanisslav** [telerik/kendo-ui-core#6855] opened 2022-05-20 13:16 UTC
### Bug report

When ServerOperation(true) is set, the paging is not applied after creating a new record.

### Reproduction of the problem

https://demos.telerik.com/aspnet-mvc/listview/editing

### Current behavior

PageSize is set to 4, but after inserting a new item, it appears along with the other items. 

### Expected/desired behavior

https://demos.telerik.com/kendo-ui/listview/editing
When a new item is created, remove the last one from the current page. 

### Environment

* **Kendo UI version:** 2022.1.301
* **Browser:** [all ]

**Comment by gyankov** [comment] 2022-05-24 13:31
The issue is caused because we do not assign the skip and take parameters when processing the query with server paging enabled:

- https://github.com/telerik/kendo/blob/master/src/kendo.data.js#L4043

This seems intentional as it was added with the following commit: 

- https://github.com/telerik/kendo/commit/f28f6e22e8ab49f31d0353aa884e6eeae13a8a89

As there is no related issue with the above commit, I cannot tell what's the reason behind it. @ag-petrov could you please confirm that this behavior is intended, and if it is, please close this issue.

**Comment by ag-petrov** [comment] 2024-01-29 09:44
@gyankov It would be difficult to determine why was the datasource forced to function in such a way. The best approach we could take here is to evaluate again what is the best approach and apply changes if necessary

**Comment by ag-petrov** [comment] 2024-02-22 15:38
As this seems intentional I am closing the bug for now unless it gets popularity and requires fixing.

**Closed by ag-petrov** 2024-02-22 15:38 UTC
Labels: Bug, F: DataSource, SEV: Low, FP: Unplanned
