### ISSUE TITLE
Pasting in inline elements trims br tags

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3354] opened 2017-06-28 10:30 UTC
### Bug report

When user pastes in an inline element with a br tag inside, the br tag is removed after paste. 

This is the line of code that removes the `<br>` tag: https://github.com/telerik/kendo/blob/master/src/editor/dom.js#L577-L579. 

### Reproduction of the problem

http://demos.telerik.com/kendo-ui/editor/index

1. Clean the content area;
1. Click the Bold tool to create an inline element (`<strong>`);
1. Type one word;
1. Press `Shift+Enter` to add a `<br>` tag;
1. Type second word;
1. Paste something. 

### Current behavior
The `<br>` tag is removed and formatting is different. 

### Expected/desired behavior
The `<br>` tag to stay in place.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Iankodj** [comment] 2018-05-11 12:57
Not reproducible with latest version (staging or 2018 R2).

**Comment by Dimitar-Goshev** [comment] 2018-05-30 12:52
The issue is fixed in R2 2018. It is reproducible with earlier versions.

**Closed by Dimitar-Goshev** 2018-05-30 12:52 UTC
Labels: Bug, C: Editor, Kendo2, Priority 1, SEV: Medium
