### ISSUE TITLE
NumericTextBox does not allow numbers with commas to be pasted

### ISSUE THREAD

**Issue by alienonland** [telerik/kendo-ui-core#2773] opened 2017-02-14 17:21 UTC
### Bug report

When I paste a number including group separators like a comma, my edit is lost and the value reverts to the previous value.

### Reproduction of the problem
Copy 1,000,000.00
In http://dojo.telerik.com/UnUyE paste the number into the NumericTextBox. 

### Current behavior
The number parses successfully, but fails the numeric regex so IsValid is false.

### Expected/desired behavior
Number should be pasted successfully and formatted according to the format string provided. Below I've added code to include the parsed value when an invalid number that parses successfully is pasted.

### Environment

* **Kendo UI version:** 2016.3.914 - 2017.1.118, 2021.1.119 - 2021.2.511
* **Browser:** [all] 

` 
if (result === NULL || that._adjust(result) !== result || !isValid) {
   if (result !== NULL) {
       that._update(result);
   }
   else {
       that._update(value);
   }  
}
`

**Comment by simonssspirit** [comment] 2017-05-18 05:57
Possible fix:
`
_paste: function (e) {
            var that = this;
            var element = e.target;
            var value = element.value;
            var numberFormat = that._format(that.options.format);
            setTimeout(function () {
                var result = that._parse(element.value);
                var isValid = that._numericRegex(numberFormat).test(result);
                //var isValid = that._numericRegex(numberFormat).test(element.value);
                if (result === NULL || that._adjust(result) !== result || !isValid) {
                    that._update(value);
                }
            });
        },
`

**Comment by simonssspirit** [comment] 2017-07-24 14:06
fixed with: https://github.com/telerik/kendo-ui-core/pull/3235/commits/a59dd053ac9183c34404abb8fb89ec05d9b93d12

**Comment by karinaalaya** [comment] 2018-02-22 19:47
Hi, in what version of kendo this was fixed? Or do you know when it's going to be released?

Thanks in advance

**Comment by matanasov** [comment] 2019-03-25 08:59
The issue is fixed in 2017 R2 SP1 (2017.2.621) version of the Kendo UI for jQuery numeric text box.

**Comment by dhansenAllvue** [comment] 2021-02-10 22:48
This seems to be broken again as of the 2020 R1 SP1 build.

**Closed** 2021-05-17 10:46 UTC
Labels: Bug, C: NumericTextBox, FP: Completed, Kendo1, Next LIB, Priority 5, SEV: Low
