### ISSUE TITLE
The Grid is scrolling when the Popup window is shown for editing (iOS).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2881] opened 2017-03-10 08:05 UTC
### Bug report
The Grid is scrolling when the Popup window is shown for editing. When the Popup window is shown the Grid can still be scrolled on the background on iOS devices. The Grid is even scrolled when the user tries to scroll over the popup.

### Reproduction of the problem
1. The issue can be observed on our demo using an iOS device: http://demos.telerik.com/kendo-ui/grid/editing-popup
1. Edit a record.
1. Tap on the grid below the modal and try to scroll

### Current behavior
The grid rows and columns can be scrolled.

### Expected behavior
The grid rows and columns cannot be scrolled.

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [mobile  iOS Safari]

**Comment by ag-petrov** [comment] 2019-10-04 07:42
This seems be to fixed with the latest scripts from master. Adding for testing.

**Comment by dmanova** [comment] 2019-10-17 13:38
This is reproducible with LESS themes and iOS<v.13

**Comment by ag-petrov** [comment] 2020-10-06 06:47
Since it is reproducible with old version of iOS I am closing the case.

**Closed by ag-petrov** 2020-10-06 06:47 UTC
Labels: Bug, C: Grid, Kendo1, SEV: Low, Touch Devices
