### ISSUE TITLE
Changing font size in spreadsheet is slow

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3626] opened 2017-09-27 10:14 UTC
Based on customer feedback

> I'm on a spreadsheet, i select all the rows and columns in the spreadsheet and then i change the font size from 11 to 12 or 14, it takes me around 20 seconds or more to update the style

![5af99fee-c31b-4bb5-a7e0-91fb1d11558f_ox-sheet](https://user-images.githubusercontent.com/8048/30908224-a00bbf8c-a385-11e7-961a-26a0a47482fb.gif)

TID: 1131732

**Comment by mishoo** [comment] 2018-07-03 11:33
Closing as duplicate of #2582.

**Closed by mishoo** 2018-07-03 11:33 UTC
Labels: C: Spreadsheet, Kendo2, Priority 1, Question, SEV: Low
