### ISSUE TITLE
Timeline views are not rendered correctly when using Sass Default theme in Chrome

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4593] opened 2018-10-17 15:09 UTC
### Bug report
When using Sass Default theme the columns are slightly shifted compared to the header. 

### Reproduction of the problem
1. Open the [Timeline demos](https://demos.telerik.com/kendo-ui/scheduler/timeline)
2. Select Default SASS theme
3. Select 'Timeline Week' or 'Timeline Work Week'

### Current behavior
[screenshot](https://www.screencast.com/t/vUT8p1od)

![image](https://user-images.githubusercontent.com/14364791/47096154-48ba4000-d237-11e8-99de-743c1aea4066.png)

### Expected/desired behavior
The columns for the events should not be shifted. The appearance should be as in the rest of the themes.

### Environment

* **Kendo UI version:** 2018.3.911
* **Browser:** [Chrome ]

**Comment by Dimitar-Goshev** [comment] 2019-01-30 10:48
This issue is duplicate of one of the points from the following [Kendo Themes issue](https://github.com/telerik/kendo-themes/issues/315).

**Closed by Dimitar-Goshev** 2019-01-30 10:48 UTC
Labels: Appearance, Bug, C: Scheduler, Kendo2, SEV: Low
