### ISSUE TITLE
Combobox noDataTemplate not available for C#

### ISSUE THREAD

**Issue by aconfee** [telerik/kendo-ui-core#2915] opened 2017-03-16 16:26 UTC
Hello,

I see that there is a way to edit the text that is displayed in a combobox dropdown when the input doesn't match anything. This seems to be done using a comboBoxOption property called noDataTemplate as seen here: http://docs.telerik.com/kendo-ui/api/javascript/ui/combobox.

However, this doesn't seem to work for the C# version. The member doesn't exist on ComboBoxOptions, and throws a compiler error as expected. 

Is this feature available to C#?

**Comment by zdravkov** [comment] 2017-09-27 13:33
Duplicate of #2424

**Closed** 2017-09-27 13:33 UTC
Labels: C: ComboBox
