### ISSUE TITLE
FileManager Cannot rename at left panel

### ISSUE THREAD

**Issue by angel199321** [telerik/kendo-ui-core#5556] opened 2020-01-27 17:16 UTC
### Bug report
When click rename button in contextmenu at left side. Rename dialog pop up. But input element cannot select. I can't enter new name.
### Environment
* **Kendo UI version:** 2020

**Comment by Dimitar-Goshev** [comment] 2020-01-28 11:41
@angel199321 Thank you for your feedback. I followed the reported steps on [FileManager Basic Usage demo](https://demos.telerik.com/kendo-ui/filemanager/index), but the issue is not reproducible in Chrome 79, Firefox 72, IE 11 and Edge 79.
Is the issue reproducible on your side? What browser is used and what is its version?

**Comment by angel199321** [comment] 2020-01-30 03:55
> @angel199321 Thank you for your feedback. I followed the reported steps on [FileManager Basic Usage demo](https://demos.telerik.com/kendo-ui/filemanager/index), but the issue is not reproducible in Chrome 79, Firefox 72, IE 11 and Edge 79.
> Is the issue reproducible on your side? What browser is used and what is its version?

More info about environment i used:
- Chrome and Vivaldi (using Chromium).
- Newest AspBoilerplate framework.

**Comment by Dimitar-Goshev** [comment] 2020-02-04 14:48
@angel199321 Is the issue reproducible on your side on any of the demo pages?
Are you using Window or MacOS and what version? Is the issue reproducible on Firefox or IE for example? If the issue is not reproducible on the demo page, but on a custom project, please open a support ticket and provide a runnable reproduction project to enable us reproduce and debug the issue.

**Comment by Dimitar-Goshev** [comment] 2020-07-08 08:48
I am closing this issue due to not being able to reproduce it on our side.

**Closed by Dimitar-Goshev** 2020-07-08 08:48 UTC
Labels: C: FileManager
