### ISSUE TITLE
Custom Filterable.Operators are not applied for the Kendo UI Grid for ASP.NET Core wrapper

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3023] opened 2017-04-06 11:19 UTC
### Bug report
Custom Filterable.Operators are not applied for the Kendo UI Grid for ASP.NET Core wrapper. The following configuration will not change the operators for "String" fields:

@(Html.Kendo().Grid<GridModel>()
            .Name("Grid")
            .Filterable(filterable => filterable
                .Extra(false)
                .Operators(operators => operators
                    .ForString(str => str
                        .Clear()
                        .Contains("Contains")
                        .DoesNotContain("Does not contain")
                        .StartsWith("Starts with")
                        .EndsWith("Ends with")
                        .IsEqualTo("Is equal to")
                        .IsNotEqualTo("Is not equal to ")
                    )
                )
            )

### Reproduction of the problem
The problem could also be observed in our current (version 2017.1.223) demo for customizing the filter menu:
[http://demos.telerik.com/aspnet-core/grid/filter-menu-customization](http://demos.telerik.com/aspnet-core/grid/filter-menu-customization)

### Environment
* **Kendo UI version:** 2017.1.223

**Comment by Xizario** [comment] 2017-04-07 14:08
Duplicate of this https://github.com/telerik/kendo-ui-core/issues/2346

**Closed by Xizario** 2017-04-07 14:08 UTC
Labels: Bug, Kendo1, S: Wrappers (ASP.NET Core), SEV: Low
