### ISSUE TITLE
Grid custom template editing DropDownList 3th cascading cannot bind data~

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-ui-core#5397] opened 2019-11-08 06:14 UTC
### Bug report
Grid custom template editing DropDownList 3th cascading cannot bind data~

### Reproduction of the problem
Please run [https://dojo.telerik.com/oDAxIMUC/4](https://dojo.telerik.com/oDAxIMUC/4)~

### Current behavior
1. General grid popup editing no problem~ Please see [https://dojo.telerik.com/oDAxIMUC/5](https://dojo.telerik.com/oDAxIMUC/5)~
2. This bug started to appear from 2019.1.220~
3. If you run [https://dojo.telerik.com/oDAxIMUC/4](https://dojo.telerik.com/oDAxIMUC/4) by 2019.1.115~ no bug appear~

### Expected/desired behavior
Grid custom template editing DropDownList 3th cascading can bind data~

### Environment
* **Kendo UI version:** from 2019.1.220 to 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by dmanova** [comment] 2019-11-11 12:30
Thank you for your feedback.
It seems this behaviour is observed when the kendoDropDownList is applied to <select> tag. 
Untill this is fixed you could use the <input> tag instead.

**Comment by IKKI2000** [comment] 2019-11-12 01:39
@dmanova Thanks~ I use 2019.1.115 instead untill this fixed~

**Comment by ag-petrov** [comment] 2024-01-08 09:42
Since the services used in the dojo were not available I recreated the dojo and the problem does not seem to reproduce with the latest version. Closing this one.

Dojo - https://dojo.telerik.com/oDAxIMUC/6

**Closed by ag-petrov** 2024-01-08 09:42 UTC
Labels: Bug, C: Grid, jQuery, Triaged
