### ISSUE TITLE
Toolbar Hide method does not hide an item, when the page is loaded under small resolution(when overflow arrow is shown)

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3038] opened 2017-04-11 08:10 UTC
### Bug report

Toolbar **Hide** method does not hide the item, when the page is loaded under small resolution(when overflow arrow is shown)

### Reproduction of the problem
Use this dojo example: http://dojo.telerik.com/AjIHAh

Resize the browser window, so that the overflow arrow could appear and test the behavior when resizing the window to a larger scale.

### Current behavior
The button7 is always visible and has overflow:always. Hence it is always placed under the arrow and the arrow is never hidden when resizing the window.
See video: https://www.screencast.com/t/oLxCS94b
### Expected/desired behavior
The item should be hidden.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by IvanDanchev** [comment] 2017-07-14 13:45
Workaround: [dojo](http://dojo.telerik.com/AVEbo)

**Comment by mparvanov** [comment] 2017-12-27 11:23
Closing as a duplicate of #1879

**Closed by mparvanov** 2017-12-27 11:23 UTC
Labels: Bug, C: ToolBar, Kendo2, SEV: Medium
