### ISSUE TITLE
Pinch zoom over a Chart does not work on iOS 13

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#5326] opened 2019-10-10 13:36 UTC
### Bug report

The default pinch zoom in or zoom out can not be performed on a iOS mobile device with the latest iOS version(13).  Ticket - # 1433562

### Reproduction of the problem
Open the official demos of the chart on a mobile device and try to pinch zoom in.

### Current behavior
Zoom in and zoom out do not work
### Expected/desired behavior
Zoom in and zoom out should work.

**Comment by sspasova** [comment] 2024-01-30 08:38
I am closing this because it cannot be reproduced using Kendo UI 2023.3.1114. Tested with iOS/Safari 17.2.1.

**Closed by sspasova** 2024-01-30 08:38 UTC
Labels: Bug, SEV: Medium, C: Chart, jQuery, Touch Devices, Triaged
