### ISSUE TITLE
Gantt throws a js exception on dragging/dropping a root task in the treelist

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6193] opened 2020-12-16 13:14 UTC
### Bug report
Regression introduced in R3 2020.

### Reproduction of the problem
Reproducible in the demos. Video attached.
[Recording47.zip](https://github.com/telerik/kendo-ui-core/files/5702865/Recording47.zip)

1. Run the "overview" demo and open the browser devtools console. 
2. In the treelist, drag the first task upwards until the "k-i-insert-middle" drag clue appears. The cursor should be positioned just under the treelist header.
3. Drop the task

### Current behavior
A js exception is thrown:

kendo.all.js:126843 Uncaught TypeError: Cannot read property 'orderId' of null

### Expected/desired behavior
No exceptions are thrown.

### Environment

* **Kendo UI version: 2020.3.1118
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment] 2020-12-16 13:24
Duplicate of https://github.com/telerik/kendo-ui-core/issues/6172

**Closed by Dimitar-Goshev** 2020-12-16 13:24 UTC
Labels: Bug, C: Gantt, FP: Planned, Kendo2, Priority 5, SEV: Low
