### ISSUE TITLE
JS error on Back button

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#761] opened 2015-04-24 14:41 UTC
Can be reproduced on: [http://dojo.telerik.com/UFiVa](http://dojo.telerik.com/UFiVa)

Steps: 
Press Home1
Press Index
Press Home2
Press Back

Result: Error: Syntax error, unrecognized expression: #!
Reproducible every time with Firefox (37.0.2) and sometimes with Chrome (40.0.2214.115)

Issue is present in build 2015.1.422
Not reproducible with build 2015.1.408

**Comment by lini** [comment] 2015-05-07 08:01
issue still present in current build 2015.1.430

**Comment by KirilNN** [comment] 2015-05-07 09:46
Hi @lini,

The issue is still with status open, which means that it is not yet resolved. As soon as the status is changed to closed the fix will be pushed to the official build.

**Comment by underlog** [comment] 2015-05-08 10:40
Should be fixed in dc2176a.

**Closed by underlog** 2015-05-08 10:40 UTC
Labels: Bug, C: Application, SEV: Medium
