### ISSUE TITLE
Allow ToolBar items of type ButtonGroup and template items to be hidden

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4115] opened 2018-03-27 07:21 UTC
Currently only items of type "button" and "splitButton" can be hidden through setting their **hidden: "true"** option ([dojo ](https://dojo.telerik.com/enEJICiB) example).

**Comment by Dimitar-Goshev** [comment] 2018-05-17 10:17
Closing it as duplicate of https://github.com/telerik/kendo-ui-core/issues/2289

**Closed by Dimitar-Goshev** 2018-05-17 10:17 UTC
Labels: C: ToolBar, Enhancement, Kendo2
