### ISSUE TITLE
Spreadsheet is adding underline styles after second server-side import of the same server-side exported file

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2143] opened 2016-09-09 10:59 UTC
### Bug report

The spreadsheet is adding different font-style after the first import of the previously exported file, and it is adding underline styles after the second import.
### Reproduction of the problem

The issue can be reproduced in our demo: http://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export

Steps:

1) Export the file as XLSX **server-side**.
2) Import the same file **server-side**, notice the font is changed.
3) Export it again **server-side**.
4) Import the newly exported file **server-side**, notice the text is underlined.

### Expected/desired behavior
The text is the same format.

### Environment

Working as expected up to version: 2016.2.504

**Comment by mishoo** [comment] 2016-09-30 07:51
I don't get any underlines, but the font is indeed different.  The cause appears to be that there isn't actually any font defined in [the original data](http://demos.telerik.com/kendo-ui/content/web/spreadsheet/products.json) (notice no `fontFamily` in the JSON), and the export code [outputs the Calibri font](https://github.com/telerik/kendo/blob/master/src/kendo.ooxml.js#L247) by default.

This seems to be intentional.  I'm not sure we should do anything about it (except perhaps fix the demo data to include `fontFamily: "Arial"`?)

**Comment by Dimitar-Goshev** [comment] 2017-01-09 09:08
@mishoo The issue is reproducible on my side as well, following the steps described above. Export the file and import it - font is changed. Then export it and import it again - all text is underlined.

**Comment by Dimitar-Goshev** [comment] 2017-05-24 12:24
https://github.com/telerik/kendo-ui-core/issues/3173

**Comment by Dmidcap** [comment] 2017-08-23 16:57
I have the same issue using Telerik.Web.Spreadsheet version 2016.2.620.40 and Kendo.MVC 2016.2.714.340 This is in an ASP.NET MVC C# web application.

Essentially, we have an application with embedded spreadsheets, when I save changes to the spreadsheet the first time, nothing happens. Then if I go back to the spreadsheet, let's say I write some text in a couple blank cells. When I save again, the new text is not underlined, but ALL of the other text in other cells is underlined. I also find that if I add text to an existing cell, when I save, all of the text in that cell is now underlined. I've added a video of the save process underlining everything in a zip file.

[spreadsheet-underline-error.zip](https://github.com/telerik/kendo-ui-core/files/1246285/spreadsheet-underline-error.zip)

**Comment by akashkc** [comment] 2017-10-18 01:03
The issue is still exists.  If you have some workaround, please let us know.

**Comment by veselints** [comment] 2017-11-23 11:15
Also reported in [Ticket ID: 1138514]https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1138514&SM=0

**Comment by mishoo** [comment] 2017-11-23 11:37
Sorry guys, I cannot help with server-side import/export.  This should be reassigned.

**Comment by veselints** [comment] 2017-12-06 10:24
The reason for the issue observed are the following lines in the `Workbook.ToDocument.cs` dpl:
```C#
if (cell.Underline.HasValue)
{
    selection.SetUnderline(UnderlineType.Single);
}
```

If the `cell.Underline.HasValue` has value, but it is set to `false`, the above code will set the `Underline` value for the cell in the Workbook document to `Single`, while it should be `None`.

**Closed** 2017-12-11 08:25 UTC
Labels: Bug, C: Spreadsheet, Kendo2, Priority 3, SEV: High
