### ISSUE TITLE
Widget should open the popup when filtering is enabled

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#295] opened 2014-09-09 13:43 UTC
### Description
Widget allows to filter data source, but to do that the popup needs to be opened. If it uses autoBind: false and no data is returned, the popup will not open, hence the filtering will not be available.

Reported in TicketID: 857677 

Repro demo:
http://dojo.telerik.com/@ggkrustev/iDaf

**Comment by HolgerPersch** [comment] 2015-02-23 07:21
Sorry to bother you again, but the second service pack is out and this important feature is still not available. Without this feature server filtering is completely useless.

Any news on this?

**Comment by ggkrustev** [comment] 2015-02-23 08:57
This functionality is scheduled for Q1 2015 release due the mid March. The widget also will receive some other valuable features.
Stay tuned!

**Comment by HolgerPersch** [comment] 2015-03-20 06:00
Hi,

it's me again. This issue seems to be still not resolved with the Kendo UI Q1 2015 release. I am missing something?

Regards,
Holger

**Comment by KirilNN** [comment] 2015-03-20 07:55
Hi @HolgerPersch,

As the issue still opened, it means that it was not resolved, as soon as the status of the issue is changed to closed, this will mean that the issue is resolved and the fix will be available with the next build.

**Comment by HolgerPersch** [comment] 2015-03-20 08:06
Hi @KirilNN,

I'm aware that the status of this issue has not been changed to resolved. 

I'm asking, because the solution first was scheduled for Q3 2014 SP1, then Q3 2014 SP2 and at last for Q1 2015.
By now it's still not resolved, very disappointing.

**Closed** 2015-03-21 17:57 UTC
Labels: C: DropDownList, Enhancement
