### ISSUE TITLE
Menu submenu detaches from its parent

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6680] opened 2022-01-17 16:34 UTC
### Bug report

A Menu submenu sometimes detaches from its parent when the root element is hovered. 

### Reproduction of the problem
This issue is difficult to reproduce. Multiple tries are needed.
1. Open the [Menu Orientation Demo](https://demos.telerik.com/aspnet-core/menu/orientation)
2. Hover over a Menu item to expand it and its subitems
3. Hover back over the root item

### Current behavior
![image](https://user-images.githubusercontent.com/35375994/149806906-49c6ae4f-d7f6-4b45-8320-bc05a0394006.png)

### Expected/desired behavior
The subitem should not detach from its parent

### Environment

* **Kendo UI version:** 2021.3.1207 and 2021.3.1109
* **Browser:** [all]

**Comment by StoyanGoranov** [comment] 2022-01-17 16:34
For more information refer to the ticket thread where the issue was first reported: [https://supportheroes.telerik.com/ticket/1549035](https://supportheroes.telerik.com/ticket/1549035)

**Comment by StoyanGoranov** [comment] 2022-01-19 14:56
For more information refer to the ticket thread where the issue was first reported 1549035

**Comment by sspasova** [comment] 2024-01-29 07:37
Possibly related to #6441

**Comment by sspasova** [comment] 2024-01-29 08:12
I am closing this issue because it cannot be reproduced anymore in https://demos.telerik.com/kendo-ui/menu/orientation. I've tested it using 2023.3.1114

**Closed by sspasova** 2024-01-29 08:12 UTC
Labels: Bug, C: Menu, SEV: Low, jQuery, Priority 1, Triaged
