### ISSUE TITLE
Blank space is exported to PDF when virtual scrolling of the Kendo UI Grid is enabled

### ISSUE THREAD

**Issue by CecoMilchev** [telerik/kendo-ui-core#5159] opened 2019-07-04 09:49 UTC
### Bug report

Upon exporting a Kendo UI Grid with virtual scrolling, a blank space is exported. The white space is actually the space previously occupied by the vertical scrollbar. 

A dojo in which the behavior could be observed:

[https://dojo.telerik.com/aNasEBUm](https://dojo.telerik.com/aNasEBUm)

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by dmanova** [comment] 2019-07-09 11:29
The fix seems fine when paperSize: "A4"/"A3"/"A5" or entered as units like "mm", "cm", "in" and "pt". However it is still reproducible with the default configuration when  **paperSize: "auto"**.  Should this case be also covered, or we need to add another issue for it?
The above is valid for browsers Chrome, FF, Edge.
Find attached the PDFs where the white space is fixed (paperSize: "A4") and where still not fixed (paperSize: "auto") 
[PDF Export - paperSize A4.pdf](https://github.com/telerik/kendo-ui-core/files/3372712/PDF.Export.-.paperSize.A4.pdf)
[PDF Export - paperSize auto.pdf](https://github.com/telerik/kendo-ui-core/files/3372713/PDF.Export.-.paperSize.auto.pdf)

**Comment by mishoo** [comment] 2019-12-09 09:53
Pushed a fix for the case with paperSize "auto".

**Closed** 2019-12-19 12:58 UTC
Labels: Bug, F: PDF Export, Kendo1, Priority 1, SEV: Low

**Comment by vishal079** [comment] 2019-12-20 06:28
CecoMilchev can you tell me which browser you are using. because as your dojo example i can't reproduce it in chrome browser. 
either you can rebind the grid on click of export to pdf and pass data without virtual scrolling and try to export.
