### ISSUE TITLE
Cell content in Spreadsheet are automatically underlined on second Save 

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3173] opened 2017-05-10 07:46 UTC
### Bug report

Cell content in Spreadsheet are automatically underlined on second Save - Telerik.Web.Spreadsheet.Workbook.Save(path)

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment] 2017-05-24 12:24
Closing this as a duplicate of the issue referenced above.

**Closed by Dimitar-Goshev** 2017-05-24 12:24 UTC
Labels: Bug, C: Spreadsheet, S: Wrappers (ASP.NET Core), S: Wrappers (ASP.NET MVC), SEV: Medium
