### ISSUE TITLE
Notification content is wrapped on two rows when using SASS theme

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#7152] opened 2022-12-14 12:55 UTC
### Bug report

When using a SASS theme the content of a Notification is wrapped on two rows.

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/eXunupUW)

### Current behavior
Note the notification content is on two rows: 
![image](https://user-images.githubusercontent.com/46348689/207609984-06949e7b-b9b2-406c-882f-e8ddd5fba7d7.png)

When a [LESS theme](https://dojo.telerik.com/uGELOMOv/2) is used this is not the case. In addition, if the notification text is updated to `Command Sent`  (capital **S**) the content is not wrapped on two rows when using the SASS theme - [example](https://dojo.telerik.com/@AleksandarEvangelatov/uQuMEzUF).
![image](https://user-images.githubusercontent.com/46348689/207610011-67cf9cbe-72bb-4807-9dff-b435acaef237.png)

### Expected/desired behavior
Content should not be wrapped. 

### Environment

* **Kendo UI version:** 2022.3.1109
* **Browser:** [Chrome]

**Comment by ag-petrov** [comment] 2023-05-31 11:43
The issue is now fixed.

**Closed** 2023-05-31 11:42 UTC
Labels: Bug, C: Notification, SEV: Low, jQuery, FP: Unplanned
