### ISSUE TITLE
KendoListBox performance issue with multiselect and transfer for larger datasets 

### ISSUE THREAD

**Issue by richardsheppard-avalara** [telerik/kendo-ui-core#4255] opened 2018-05-24 13:35 UTC
### Reproduction of the problem
If you have 2 KendoListBoxes with multiselect and transfer functionality enabled, there is some serious performance issues with larger datasets (over 15,000) rows in the datasource. You will notice that your browser will stop responding when selecting 5 or more items and then moving it to the other list box.

### Current behavior
Browser stops responding and may crash in certain cases.

### Expected/desired behavior
Able to transfer multiple items (for larger datasets) using list box without any performance issues.

### Environment
* **Kendo UI version:** 2018.2.516
* **jQuery version:** 3.3.1
* **Browser:** [all]

**Comment by matanasov** [comment] 2018-05-28 11:43
@richardsheppard-avalara 
Could you please provide a dojo example that we can debug to pinpoint the cause of the issue?

**Comment by richardsheppard-avalara** [comment] 2018-05-29 15:03
https://dojo.telerik.com/eriWOFIp/2

**Comment by matanasov** [comment] 2018-05-30 11:38
@richardsheppard-avalara 
Thank you for the example. This seems to be an issue on our side.
I am notifying our devs about this behavior

**Comment by Stamo-Gochev** [comment] 2018-05-31 05:55
Indeed, an optimization can be introduced as adding/removing items re-renders the whole view.

**Comment by gregfig** [comment] 2019-02-01 09:16
It's been 8 months without an update.  Any progress on this issue?

**Comment by Stamo-Gochev** [comment] 2019-02-01 10:54
When a certain item will be implemented depends on various factors and the roadmap, so I cannot provide a specific timeframe for when this will be available. As the ListBox is part of the open source set of widgets, we are also open for pull requests that can improve the performance.

**Comment by TeyaVes** [comment] 2020-01-27 11:43
reported also in ticket #1450628

**Comment by ag-petrov** [comment] 2020-02-04 15:33
I have applied a fix which improves the performance when a number of items is transferred. When moving all the items(for example 15000) a performance issue may still occur. The reason for this is that we internally create observable objects and are adding them to an observable collection. In order to further optimize the performance the datasource logic should be revised.

**Closed** 2020-02-14 16:59 UTC
Labels: Bug, C: ListBox, Kendo1, Priority 2, SEV: Low
