### ISSUE TITLE
Disable autofill if originating cell is disabled

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#1774] opened 2016-06-09 07:36 UTC
Things we should consider - what if multiple cells are selected and some of them are disabled. We should check the reference implementations.

**Comment by tsvetomir** [comment] 2016-09-09 07:19
Implementing this will introduce a regression to #1728. Currently the filled cells are not disabled.

**Comment by mparvanov** [comment] 2019-11-05 14:44
Closing due to lack of recent demand by the community and possible regression to be introduced.

**Closed by mparvanov** 2019-11-05 14:44 UTC
Labels: C: Spreadsheet, Enhancement, Kendo2
