### ISSUE TITLE
ComboBox does not filter the data based on the text in its input if minLength is not set

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3560] opened 2017-09-06 11:20 UTC
### Reproduction of the problem
[Dojo](http://dojo.telerik.com/uweho/2) example. 
1. Focus the ComboBox.
2. Type "che". The data is filtered as expected and items with text matching the input are returned.
3. Click outside the ComboBox to close its dropdown. 
4. Click the ComboBox dropdown arrow to open its dropdown. Expected: only items matching "che" (which is still the input's value) are returned, actual: all items are returned (the data is not filtered based on the input)  

Works as expected if minLength is set. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment] 2017-12-20 14:46
The fix for this issue caused a JavaScript error regression in the following scenario:
Video - https://www.screencast.com/t/67aTaI4chUs
1. Go to ComboBox Events demo on staging.
2. Click on the arrow to expand the ComboBox dropdown.
3. Select Item 3 by clicking on it.
4. Expand the dropdown.
5. Select Item 3 text in Combo's input and press Backspace to delete it.
6. Click outside the ComboBox to blur it.
7. Expand the dropdown.
8. Press Down Arrow to focus Item 1.

Expected - Item 1 is focused.
Actual - JavaScript error:
Uncaught TypeError: Cannot read property 'text' of undefined
    at init.onSelect

**Comment by mparvanov** [comment] 2017-12-27 11:55
The following issue is reproducible:
1) Open the Server filtering example on staging: http://kendobuild-staging.openstack.progress.com/dojo-staging/
2)  Type Chang
3) Click outside of combobox to blur
4) Expand the dropdown

Expected: only items matching "Chang" (which is still the input's value) are returned
Actual: all items are returned (the data is not filtered based on the input)

**Comment by zdravkov** [comment] 2017-12-28 08:30
We have inspected the issue and came to a conclusion that in this case 'Actual' is the expected behavior because a new value is set in the Combobox when the widget is blurred and the filter is cleared correctly.

**Closed** 2018-01-03 09:21 UTC
Labels: Bug, C: ComboBox, Kendo2, Priority 5, SEV: Medium
