### ISSUE TITLE
Kendo Resize Handler Misaligned

### ISSUE THREAD

**Issue by Sheing** [telerik/kendo-ui-core#5185] opened 2019-07-24 16:53 UTC
### Bug report

Kendo Resize Handler (k-resize-handle) misaligned when there's overflow. 

### Reproduction of the problem
https://dojo.telerik.com/ovIJuKUS/4

1. Add some width to the `div` so that it overflows on the x - axis. 
2. The hover cursor is gone, resize handler is no longer aligned.

### Current behavior
Column resize cursor is not visible when you scroll to the right slightly and hover over.
### Expected/desired behavior
Column resize cursor should always be visible when hover over.
### Additional
Seems to work fine in other kendo version except the latest version "Kendo UI R2 2019 SP1"

* **Kendo UI version: 2019.2.619 Kendo UI R2 2019 SP1
* **jQuery version: 1.12.3
* **Browser: ALL

**Comment by dmanova** [comment] 2019-07-29 06:48
Closed as duplicate of: #5137 (fixed)

**Closed by dmanova** 2019-07-29 06:48 UTC
