### ISSUE TITLE
Scheduler in Default v2 does not change the date format link, when the window is resized

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3690] opened 2017-10-17 08:48 UTC
### Bug report

Scheduler in Default v2 does not change the date format link, when the window is resized.

### Reproduction of the problem
Load the Basic Usage demo of the Kendo UI Scheduler with Default v2 theme selected ;
[http://demos.telerik.com/kendo-ui/scheduler/index](http://demos.telerik.com/kendo-ui/scheduler/index)

Resize the window and you will observe the following overflow of the dates link:
[https://monosnap.com/file/WKD8JnsLBqY7sPSCjVFTgANvb3Q387](https://monosnap.com/file/WKD8JnsLBqY7sPSCjVFTgANvb3Q387)

### Current behavior
The date format link is not changed, when the window is resized

### Expected/desired behavior
The date format link should change, when the window is resized

### Workaround

You can use the media query, in order to change the format and decrease the width of the dates link:
```
 <style>
      @media only screen and (max-width: 1024px) {
        .k-scheduler-toolbar li.k-nav-current .k-sm-date-format {
          display: inline;
        }
        .k-scheduler-toolbar li.k-nav-current .k-lg-date-format {
          display: none;
        }
      }
 </style>
```
dojo example: http://dojo.telerik.com/@joneff/OjoKI

### Environment
* **Kendo UI version:** 2019.2.514
* **Browser:** [all]

**Comment by joneff** [comment] 2017-10-17 10:43
The issue in particular is caused by different styles in different themes plus styles in the demo itself. I've unified the base styles (there are few different themes) and demo styles and I will unify them completely after 2017 R3 SP1.

**Comment by joneff** [comment] 2017-10-17 10:44
Target by 06ac9e7

**Comment by Dimitar-Goshev** [comment] 2018-03-12 09:26
@joneff After the fix, the format becomes shorter on smaller window size. Still there is an issue. With LESS themes when the window is small the dates are hidden and only the calendar button is visible. But with SASS themes the dates are visible and go out of the Scheduler:
![image](https://user-images.githubusercontent.com/6614183/37275557-3cb1088a-25e8-11e8-98b5-514ffc389f9c.png)

**Comment by Juveniel** [comment] 2020-10-22 06:40
After recent changes in the Scheduler toolbar rendering, the issue with the Less-based themes is resolved - the date is visible and wraps on a new line when there is not enough space to fit. 

The behavior with the Sass-based themes is identical to the one with the Less-based themes.

Taking the above into consideration, I am closing the issue.

**Closed by Juveniel** 2020-10-22 06:40 UTC
Labels: Appearance, Bug, C: Scheduler, Kendo2, Priority 1, SEV: Low
