### ISSUE TITLE
Kendo and Google Chrome Autocomplete open Simultaneously

### ISSUE THREAD

**Issue by jamesomac** [telerik/kendo-ui-core#4174] opened 2018-04-19 14:20 UTC
### Reproduction of the problem
The behaviour can be seen using the example below and attempting to type the first letter of any city which has been saved as part of an address within the user's Google Chrome autocomplete settings. This can only be seen with Google's Autocomplete turned on. The Google Autocomplete suggestion will appear on top of the Kendo suggestions.

An example can be found here: https://dojo.telerik.com/ekezApiZ

### Expected/desired behavior
The Kendo Autocomplete dropdown should appear, but the Google Chrome autocomplete should not.

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** 1.12.3
* **Browser:** Chrome 65.0.3325.181

**Comment by e2canoe** [comment] 2018-11-29 00:40
I believe this issue is caused by a change in how the <input> autocomplete="off" attribute is interpreted by Chrome. According to this [response from Chromium.org](https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164), Chrome was changed to ignore "off".

According to that same post, the solution to completely disabling Chrome's autocomplete is to give the input's autocomplete attribute a value that does not match any of the [WHATWG autocomplete tags](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) and Chrome will not display an autocomplete box. So, perhaps the kendo-combobox control could expose it's own autocomplete attribute whose value would be assigned to the rendered input's autocomplete so that developers can control whether the kendo-combobox can override the Chrome autocomplete.

**Comment by derrickh1980** [comment] 2019-03-14 17:18
I am experiencing the same behavior with the angular combobox as well. I don't have an id on the kendo-combobox but I have a label next to it with the text "Country" in it. If I change the text value in the label to "Countr y" the autocomplete turns off. I haven't been able to turn off the autocomplete any other way.

`<label>Country</label>
 <kendo-combobox
        [data]="countryItems | async"
        [allowCustom]="false"
        textField="value"
        valueField="id">
 </kendo-combobox>`

**Comment by AndersMad** [comment] 2019-03-14 18:30
This has been reported almost year a go - and the fix is simply to replace all `autocomplete="off"` to `autocomplete="disabled"` - so pleeease? ~:)

**Comment by timopb** [comment] 2019-06-19 13:51
> This has been reported almost year a go - and the fix is simply to replace all `autocomplete="off"` to `autocomplete="disabled"` - so pleeease? ~:)

autocomplete="disabled" will _fix_ the issue for chrome but then firefox will start to autocomplete the field as it is following w3c standards and expects autocomplete="off" to prevent autocomplete. So... no real fix here.

**Comment by fschlaef** [comment] 2019-06-20 07:51
@timopb it's ok, the Kendo team implemented it like this :

`AUTOCOMPLETEVALUE = support.browser.chrome ? 'disabled' : 'off'`

Everything should be OK

**Comment by fschlaef** [comment] 2019-07-02 08:06
I am still having this issue with Chrome 75 and Kendo UI 2019.2.619
On Firefox everything is OK but on Chrome the browser autocomplete popup still opens over the Kendo list.

@Juveniel  @mparvanov  @jivanova

**Comment by mparvanov** [comment] 2019-07-02 08:55
@fschlaef  I tried but was not able to replicate the problem with Kendo v. 2019.2.619 and Chrome 75 on my side.
Here is a screenshot of my test over the Kendo autocomplete https://take.ms/KAdku and on a simple input for the city field https://take.ms/sHNeg.

Could you confirm whether you are experiencing the issue with this [Dojo sample](https://dojo.telerik.com/UQutoGIM/2) on your side or provide a modified sample so we could replicate it on our side?

**Comment by fschlaef** [comment] 2019-07-02 13:08
@mparvanov the issue only triggers if there is a `name` attribute on the element, and if the element is contained within a `form` and submitted.
See here for repro with `kendoComboBox` : https://dojo.telerik.com/USoHopEc/3

How to repro, on Chrome 75 :

Open the menu and select any value (for example, "Chang")
Submit the form
Re-run the snippet
Open the menu again, then click on the text part of the menu (search)
Result :

![kendobug](https://user-images.githubusercontent.com/29452252/60515020-ff355680-9cda-11e9-9225-a564927216ed.jpg)

**Comment by mparvanov** [comment] 2019-09-05 07:25
I can confirm the issue is reproducible.

**Comment by Juveniel** [comment] 2019-09-16 05:13
There are currently two distinct Chrome functionalities which are subject to this issues - Autofill and Autocomplete. The [autofill spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-anchor-mantle) currently states that the off value for the autocomplete  attribute should correctly mark an input as a one that contains sensitive data, thus disabling the autocomplete and autofill. 

Taking the above into consideration, we will stick to setting the autocomplete attribute to "off" for the Kendo Autocomplete. After further testing in Chrome 76, Beta (77) and Canary(78) this seems to correctly handle the autocompletion popups which are not being displayed.

If there are any scenarios where the "off" value fails for the autocomplete attribute and the popup is shown, this should be reported to Chrome in [the following open bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=587466). We have also prepared [a Knowledge Base Article](https://docs.telerik.com/kendo-ui/controls/editors/autocomplete/troubleshoot/troubleshooting) that provides an alternative solutions for such edge-cases to disable the autocomplete of Chrome.

**Closed by Juveniel** 2019-09-16 05:13 UTC
Labels: C: AutoComplete, C: ComboBox, C: DropDownList, C: DropDownTree, C: MultiColumnComboBox, C: MultiSelect, Enhancement, FP: In Development, Kendo2, Priority 5

**Comment by fschlaef** [comment] 2019-09-18 09:37
Confirmed working with latest version, thank you very much ! 👍

**Comment by egorpavlikhin** [comment] 2020-02-18 04:53
The issue still exists and the KB link provided is broken.

**Comment by Juveniel** [comment] 2020-03-05 09:07
Hello @egorpavlikhin,

I was not able to reproduce the issue with the latest version of Chrome (80.0) and the latest release of Kendo UI(2020.1.219). Could you verify if you are able to reproduce the issue in [the official Demos ](https://demos.telerik.com/kendo-ui/combobox/serverfiltering)? If this is indeed the case, please provide a list of steps that would enable us to reproduce the issue and also add any specific details that you think might be important.

In terms of the KB link, indeed you are correct that it is currently not accessible. We are aware of the issue and will try to resolve it as soon as possible. In the mean time, here is the workaround that you could try:

1. Use a `name` attribute that is not contained in the predefined auto-fill fields of Chrome.
1. Toggle the `name` attribute on `focus` and `focusout`.

```js
<form>
  <input name="city" ID="City" required />
</form>

<script>
  var data = [
    "Toronto",
     "New York",
     "London",
     "Paris"
   ];

   var name;
   var CityAutoComplete = $("#City").kendoAutoComplete({
     dataSource: data,
     filter: "startswith",
     placeholder: "Select city...",
     separator: ", "
   }).getKendoAutoComplete();

   CityAutoComplete.element.on("focus", function () {
     name = this.name;
     this.name = kendo.guid().substr(0, 8);
   });

   CityAutoComplete.element.on("focusout", function () {
     this.name = name;
   });
</script>
```

**Comment by hsuanhan** [comment] 2021-07-21 16:56
Is this supposed to be fixed on the UI for ASP.NET MVC version 2021.2.616?

I see the browser autocomplete popup open when I click into a Kendo ComboBox on Chrome (v 92). When I inspect the input tag, autocomplete is set to 'off'.

![image](https://user-images.githubusercontent.com/4663949/126528027-861fa2ef-c82b-4b9f-bb4f-40617f34e162.png)
