### ISSUE TITLE
Spreadsheet.saveJSON() creates corrupt data when Workbook contains images

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6529] opened 2021-08-18 09:20 UTC
### Bug report

Spreadsheet.saveJSON() creates corrupt data when Workbook contains images

### Reproduction of the problem
* Run the following Dojo: https://dojo.telerik.com/iPeNEmOR/13
* Click the button to call .saveJSON() and save the file
* Try to open the file in Excel - it has an error

### Expected/desired behavior
Workbook with images should be properly exported

### Environment

* **Kendo UI version:** 2021.2.616

**Comment by veselints** [comment] 2021-08-19 10:41
Related to: https://github.com/telerik/kendo-ui-core/issues/6411

**Comment by mishoo** [comment] 2022-04-18 10:33
Closing as duplicate of #6411.

**Closed by mishoo** 2022-04-18 10:33 UTC
Labels: Bug, SEV: Medium, C: Spreadsheet, jQuery2
