### ISSUE TITLE
Spreadsheet custom editors

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1710] opened 2016-05-24 12:28 UTC
The most requested UV item for the widget - rightfully so. Spreadsheet is all about data entry

http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/10069785-spreadsheet-custom-editors

I think that there is plenty to explore here, but for we can start with date/time pickers -
https://github.com/telerik/kendo-ui-core/issues/1675 and predefined items from a list - https://github.com/telerik/kendo-ui-core/issues/1673

Note: the editors in question will be activated only when the cell enters an edit mode. We should also figure out the formula bar behavior when such cell is entered.

**Comment by mishoo** [comment] 2016-05-24 13:11
One question that comes to mind, should we allow free text editing as well?

**Comment by gyoshev** [comment] 2016-05-24 13:32
> Note: the editors in question will be activated only when the cell enters an edit mode. 

By the way, both Google Docs and MS Excel provide editing controls without entering edit mode:
![image](https://cloud.githubusercontent.com/assets/90405/15505624/ed0c2f1a-21cc-11e6-9719-f1e23057268f.png)
![image](https://cloud.githubusercontent.com/assets/90405/15505633/f18ad6b8-21cc-11e6-8d7a-43ac367a9a85.png)

Maybe we should consider allowing this?

**Comment by underlog** [comment] 2016-05-24 13:45
@mishoo, don't know, actually. I can definitely see a case for the opposite behavior (limiting choices to a predefined set). Free text editing + choices sounds like a combobox kind of editor to me. If we support both editors *and* free form text editing, then we should figure out how to handle formula entry. Or, perhaps this is not an issue at all? 

@gyoshev - these look more like custom editor indicators, could we treat them as such? The rendering can handle such things, biggest complication as usual is the frozen panes.

**Comment by mishoo** [comment] 2016-05-24 14:15
@underlog about the formula input, it should probably remain as is — allow free text there.

I couldn't find out in Google Docs how to enable custom editors, other than by data validation.  When done like this, it still allows free text input; the popup is just a helper.  And the formula bar remains a plain text field.  I vote we do the same.

**Comment by gyoshev** [comment] 2016-05-24 14:45
@mishoo AFAIK that's the way to enable them in Excel, too. +1 for the GDocs behavior, quite usable.

@underlog I believe these can be rendered like the filtering indicators, and allow the popups to be populated with the necessary UI (static / virtual list or exotics). This will also cater for the ASP.NET AJAX integration. I'm not sure if we want to reuse existing components outside the popup?

**Comment by underlog** [comment] 2016-05-25 06:52
I like the google docs approach (validation = editor helper), too. The main advantage here is that this will give us persistence out of the box. Don't you think, however, that this is a design decision suitable for a product targeting end users?

**Comment by tsvetomir** [comment] 2016-05-30 06:38
As usual we have to leave the option for the developers to come up with their own implementations. 

Perhaps an event or a set of events will be sufficient to allow implementing custom "custom editors". Templates don't seem like a good fit for the moment, due to the dynamic nature of the UI virtualization.

**Comment by mishoo** [comment] 2016-05-30 07:26
In this case I don't think we can rely on validation alone, we'd have to keep the cell editor in a different property.  How about an API like this:

```js
kendo.spreadsheet.registerEditor("foo", {
    edit: function(range, pos, callback) {
        // opens the editor for the given cell.  I'm thinking pos
        // will be useful to position it near the dropdown button
        // (if it's a popup editor) but it could be a dialog as
        // well.  We leave it to users.

        // the editor should invoke callback(value) when a value
        // has been selected
    },
    close: function() {
        // hide the editor
    },
    icon: "iconClass" // for the button
});
```

and we'll store the editor type in a new property bag, so one can say e.g.

```js
sheet.range("A5").editor("foo");
```

**Comment by mishoo** [comment] 2016-05-30 14:33
Started implementation on branch [spread-editors](https://github.com/telerik/kendo/tree/spread-editors).  Currently it has the date picker (can be seen in `playground/spreadsheet/sheet.html` on cells E5:E8).  It's enabled by the `showButton` option of the validator (checkbox yet to be added in the dialog).

So the date/list ones can be enabled via validation and will be built-in.  For user-defined editors, though, what do you guys think about my proposal above? (new `editor` property bag, and `spreadsheet.registerEditor`, which is already defined on the branch).

**Comment by tsvetomir** [comment] 2016-05-30 15:12
The `registerEditor` usage seems great to me. Its simple to use and extensible.

**Comment by mishoo** [comment] 2016-05-31 14:22
The editors for #1675 and #1673 are in place and can be activated in the validation dialog (and there's a sample in `playground/spreadsheet/sheet.html`),

Left to do on this issue (please add to the list if I'm missing something):

- [ ] the `editor` property bag, serialization
- [ ] document `kendo.spreadsheet.registerEditor`
- [ ] a demo with a custom editor would be nice

**Comment by tsvetomir** [comment] 2016-05-31 15:44
I'll also add end-user documentation to the list /cc @dmihaylo

**Comment by mishoo** [comment] 2016-06-06 09:24
[API documentation here](https://github.com/telerik/kendo/blob/654055922dc7a19e1c5957ac782b521f6a7918da/docs/controls/data-management/spreadsheet/custom-editors.md) — should I cherry-pick it into `kendo-ui-core`?  Also, I believe the branch is ready to merge, objections? ;-)

**Comment by underlog** [comment] 2016-06-06 09:26
Seems great to me! And a demo would complete the story :)

**Comment by mishoo** [comment] 2016-06-06 09:33
Merged.

**Comment by mishoo** [comment] 2016-06-06 15:10
@underlog I added a demo skeleton in `spreadsheet/custom-editors.cshtml`.  It shows the built-in editors, as well as the color picker sample from the doc.  Someone else should take it from here if it needs to be a more relevant/real-world scenario, as my imagination is lacking right now... :)  (giving good examples turns out to be a hard problem)

**Comment by tsvetomir** [comment] 2016-06-07 15:02
I get an error in the "regular" demos:
```
view.js:731 Uncaught TypeError: this._sheet.activeCellCustomEditor is not a function
kendo.Class.extend.isEditButton @ view.js:731
kendo.Class.extend.objectAt @ view.js:770
kendo.Class.extend.objectAt @ controller.js:745
kendo.Class.extend.onMouseMove @ controller.js:416
kendo.Class.extend.handleEvent @ eventlistener.js:148
kendo.Class.extend.mouse @ eventlistener.js:117
jQuery.event.dispatch @ jquery.js:5226
elemData.handle @ jquery.js:4878
```

**Comment by mishoo** [comment] 2016-06-07 15:06
Could it be because that method is defined in a [new file](https://github.com/telerik/kendo/blob/master/src/spreadsheet/customeditors.js)?  I did list it in [kendo.spreadsheet.js](https://github.com/telerik/kendo/blob/master/src/kendo.spreadsheet.js#L27) though.

**Comment by underlog** [comment] 2016-06-07 15:12
Well, that should work as expected. The error suggests that the new file is not picked by the build, though. Can you check that the referenced file is rebuilt correctly?

**Comment by tsvetomir** [comment] 2016-06-07 15:20
Seems to work fine [on staging](http://kendobuild/staging-kendo-ui/), so it's my setup. Sorry!

**Comment by tsvetomir** [comment] 2016-07-07 08:50
@yordanov do you have any ideas for a prettier demo?
See http://kendobuild/staging-kendo-ui/spreadsheet/custom-editors

**Comment by ipeshev** [comment] 2016-07-08 07:45
On IE11 colorpicker appears shrinked and positioned in top left corner.

**Comment by mishoo** [comment] 2016-07-08 09:20
There's an error actually that occurs in `kendo.binder.js`:

![binder-error-ie11](https://cloud.githubusercontent.com/assets/334725/16683025/4eb33f22-4506-11e6-950f-8bc586edc36b.png)

Perhaps I'm [not using it properly](https://github.com/telerik/kendo/blob/master/demos/mvc/Views/demos/spreadsheet/custom-editors.cshtml#L8-L26)?  In any case, it seems unrelated to the spreadsheet, but rather my implementation of the sample custom editor.

**Comment by mishoo** [comment] 2016-07-08 09:52
Seems like a really weird IE issue.  Just trying to `console.log(children.length)` for that particular element triggers the error.  There's nothing fancy about the element, it's just a `<div>` (the [toplevel one](https://github.com/telerik/kendo/blob/master/demos/mvc/Views/demos/spreadsheet/custom-editors.cshtml#L18)).  It's surprising that nobody has hit the issue so far.

Moving [initialization](https://github.com/telerik/kendo/blob/master/src/kendo.binder.js#L1655) of `children` to right before [this line](https://github.com/telerik/kendo/blob/master/src/kendo.binder.js#L1723) fixes it.  Thanks IE for yet another mind blowing weirdness.  :disappointed:

@underlog should I push this fix?

**Closed** 2016-07-08 10:03 UTC
Labels: C: Spreadsheet, Story

**Comment by underlog** [comment] 2016-07-08 10:25
Yeah another IE weirdness. not much I can say here.

**Comment by ipeshev** [comment] 2016-07-08 13:11
I can confirm that it is fixed, another IE bug down.

**Comment by niyas-ali** [comment] 2019-04-24 09:00
Hi,

Is there any way to pass some value to the edit variable ?
Sample code i have added below, here my logic is written in the edit function, there i have a dropdown and the value of this dropdown has to assign dynamically when i call sheet.range("A5").editor("foo");
Is there any hack  to pass the value through editor("foo",'some value') and get it from edit function?
//register editor
kendo.spreadsheet.registerEditor("foo", {
    edit: function(range, pos, callback) {
        // opens the editor for the given cell.  I'm thinking pos
        // will be useful to position it near the dropdown button
        // (if it's a popup editor) but it could be a dialog as
        // well.  We leave it to users.

        // the editor should invoke callback(value) when a value
        // has been selected
    },
    close: function() {
        // hide the editor
    },
    icon: "iconClass" // for the button
});
