### ISSUE TITLE
DropDown close animation is misplaced when the element is opened/closed fast (with jquery 3.1.1))

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2848] opened 2017-03-02 14:57 UTC
### Reproduction of the problem
Use the following dojo
http://dojo.telerik.com/IPoBIB/23

Star opening and closing the dropdown fast and observe its the close position.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment] 2017-12-14 15:14
Closed as duplicate of: https://github.com/telerik/kendo-ui-core/issues/3840

**Closed by Dimitar-Goshev** 2017-12-14 15:14 UTC
Labels: Bug, C: ComboBox, Kendo2, SEV: Low
