### ISSUE TITLE
Spreadsheet filter by condition crashes after filter by value. [fix included]

### ISSUE THREAD

**Issue by chriseaton** [telerik/kendo-ui-core#3441] opened 2017-07-24 18:42 UTC
### Bug report
If you attempt to choose a criteria filter after applying a "checkbox" filter, the filter will error out with:

> Uncaught TypeError: Cannot read property 'criteria' of undefined<br> at eval (eval at setter (https://kendo.cdn.telerik.com/2017.2.621/js/kendo.all.min.js:25:31060), <anonymous>:3:15)

This appears to be a bug in the spreadsheet as you can easily reproduce it within the online demo.

**Fix included below.**

### Reproduction of the problem
1) Go to the filtering demo: http://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering
2) Click the filter on the "Client" column.
3) Uncheck a few of the client values then hit apply.
4) Click the filter again, but this time expand the filter by criteria.
5) Select an item from the dropdown.
6) Notice a javascript error occurs, and the filter cannot be applied.

### Current behavior
Errors out, breaks filtering.

### Expected/desired behavior
The filter should toggle properly to filter by value from filtering by condition.

### Environment
* **Kendo UI version:** 2017.2.621
* **jQuery version:** 3.1.1
* **Browser:** all

### Fix
The fix is to check for the presence of the "customFilter" property before running the call to set a child property value. If the property is not found, it should be created (see below).

File: kendo.spreadsheet.js
AMD Module: spreadsheet/filtermenu
Method: operatorChange

Change this:
```
operatorChange: function (e) {
    var dataItem = e.sender.dataItem();
    this.set('operatorType', dataItem.type);
    this.set('customFilter.criteria[0].operator', dataItem.value);
},
```

To this:
```
operatorChange: function (e) {
    var dataItem = e.sender.dataItem();
    this.set('operatorType', dataItem.type);
    if (!this.get('customFilter')) {
        this.reset();
    }
    this.set('customFilter.criteria[0].operator', dataItem.value);
},
```

**Comment by veselints** [comment] 2017-07-26 11:01
Duplicate of #3317

**Closed** 2017-07-26 11:01 UTC
