### ISSUE TITLE
Paste keyboard command (Ctrl +C/V) in Spreadsheet places "null" in the target cell

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#1882] opened 2016-07-05 10:56 UTC
The problem can be replicated using the online demos:

demos.telerik.com/aspnet-mvc/spreadsheet/index

**Comment by mishoo** [comment] 2016-07-05 11:05
Duplicate of #1799 (fixed).

**Comment by ipeshev** [comment] 2016-07-05 12:08
Not sure if it is an issue, but on MS Edge CTRL+C ( from empty cell ) and CTRL+V into some cell (with content ) does nothing, on other browsers ( including IE11) it is clearing cell content.

**Comment by Alex-Bubblemaster** [comment] 2016-07-12 09:06
Copied blank Excel cell pastes "null" in Spreadsheet. Reported in ticket 1049532. 
(Tested in kendobuild)

**Closed** 2016-07-12 09:52 UTC
Labels: Bug, C: Spreadsheet, SEV: Medium

**Comment by ipeshev** [comment] 2016-09-08 09:21
On Chrome it CTRL+C/ is not working but CTRL+INS ( instead CTRL+C ) is working fine. 
It looks like it is something Chrome specific with keyboard shortcuts.
