### ISSUE TITLE
Spreadsheet takes the focus away from toolbar items when moving the mouse on the border between two columns on the column bar

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3695] opened 2017-10-18 11:04 UTC
### Bug report
Spreadsheet takes the focus away from toolbar items when moving the mouse on the border between two columns on the column bar. 

This issue stems from the 'mousemove' event that's being captured by the spreadsheet (the event handler is attached to the root html element). Once this event detects the mouse cursor is right on the border between two columns on the column bar, the spreadsheet renders to highlight the border and change the cursor to indicate column resize. This render function call switches focus back to the spreadsheet and causes the DropDownList menu to close.

### Reproduction of the problem
* Go to the [Index Spreadsheet Demo](https://demos.telerik.com/kendo-ui/spreadsheet/index);
* Click to open the Font drop-down;
* Move the mouse over the second option;
* Move the mouse horizontally. At the moment when it reaches the border between two columns, the drop-down will close and the column resize handle will be displayed;

[Screencas here](https://www.screencast.com/t/XKtuu3STR);

**Comment by mishoo** [comment] 2018-07-03 11:35
Closing as duplicate of #2922.

**Closed by mishoo** 2018-07-03 11:35 UTC
Labels: Bug, C: Spreadsheet, Kendo2, SEV: Low
