### ISSUE TITLE
Grid sticky column's left-border is set to 0px when the previous column is also sticky and hidden

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6288] opened 2021-02-12 15:55 UTC
### Bug report
The behavior has been introduced in R3 2020.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/osayIrIk) example.
1. Run the example

### Current behavior
The sticky column's left border is not displayed. For more details, see Ticket ID: 1506287

### Expected/desired behavior
The sticky column's left border is displayed.

### Environment

* **Kendo UI version:** 2020.1.119
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by sspasova** [comment] 2024-01-13 18:31
I am closing this issue because it is no longer reproducible using Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/EdoPapik

**Closed by sspasova** 2024-01-13 18:31 UTC
Labels: Bug, SEV: Low, C: Grid, jQuery, FP: Unplanned, Triaged
