### ISSUE TITLE
Endless scrolling of ListView does not correctly in AngularJS

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#5819] opened 2020-06-02 12:22 UTC
When loading the new batch of items a blank item is rendered. More information can be found in ticket - 1469304. 

Possible workaround can be found in [this ](https://dojo.telerik.com/EHozaKag/5)dojo.

**Comment by gyankov** [comment] 2020-09-09 13:58
Possible duplicate of https://github.com/telerik/kendo-ui-core/issues/5515.

**Comment by ag-petrov** [comment] 2020-09-30 08:35
Related issue - https://github.com/telerik/kendo-ui-core/issues/5999

**Comment by dmanova** [comment] 2020-10-02 14:07
> Possible duplicate of 5515.
5515 doesn't seem to be fixed with the current issue. While 5999 does.

**Comment by dmanova** [comment] 2020-10-02 14:13
Duplicate of #5999

**Closed by dmanova** 2020-10-02 14:13 UTC
Labels: Bug, C: ListView, F: AngularJS, Kendo1, SEV: Medium

**Comment by ag-petrov** [comment] 2020-10-05 06:34
#5515 is not related, it is a separate issue
