### ISSUE TITLE
Using arrows in virtualized ComboBox to navigate through items selects previous item when valueMapper function is called

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5991] opened 2020-08-28 11:29 UTC
### Bug report
When using jQuery v3.5.1 and using the arrows to navigate through items in virtualized ComboBox a previous item is selected when valueMapper function is called. The behavior is not observed when using jQuery v1.12.3

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/EveNEHEy)
1. Click on the arrow to open the list of items
1. Navigate through the items using the down arrow key

### Current behavior
When the valueMapper function is called the selection moves to the previous item in the list

### Expected/desired behavior
Selection should not change when the valueMapper function is called.
[Working example with jQuery v1.12.3](https://dojo.telerik.com/@AleksandarEvangelatov/uKApapeK)

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** 3.5.1
* **Browser:** [all]

**Comment by martintabakov** [comment] 2024-01-31 13:58
cannot reproduce the issue with the latest version - https://dojo.telerik.com/opoRuboh/2. Closing the issue until further information is provided.

**Closed by martintabakov** 2024-01-31 13:58 UTC
Labels: Bug, C: ComboBox, SEV: Medium, jQuery, Priority 1, FP: Unplanned, Triaged
