### ISSUE TITLE
Kendo.Mvc v.2016.2.607 has a dependency on pre-release RC2 assemblies

### ISSUE THREAD

**Issue by 1amirjalai** [telerik/kendo-ui-core#1783] opened 2016-06-12 11:02 UTC
Kendo mvc version  2016.2.607 released for the rc2 of asp.net core is still dependent on following  namesapces
Microsoft.Extensions.CompilationAbstractions  
Microsoft.Dnx.Compilation.CSharp.Abstractions  

which are not supported on rc2 anymore.

**Comment by dvdobrovolskiy** [comment] 2016-06-12 12:53
Correct. Have same problem.

**Comment by Asshiah** [comment] 2016-06-13 11:17
Same here.

**Comment by madrianr** [comment] 2016-06-13 15:46
Same

**Comment by alaatm** [comment] 2016-06-13 22:51
Also please change framework to netstandard1.x instead of netcoreapp1.0.

**Comment by Tiger333** [comment] 2016-06-14 11:28
Given the above then surely the latest version of telerik kendo ui rc2 should be pulled , until resolved.

No point rushing out the product if its not 100% ready -- happy to wait Telerik...

**Comment by Jekata** [comment] 2016-06-14 12:47
Hi guys,

We are aware of the reported namespace problem, which is logged with very high priority. We are working currently on it and once it's fixed, we will launch a new build.

**Comment by 1amirjalai** [comment] 2016-06-14 14:46
@Jekata  do u have any release date?

**Comment by Jekata** [comment] 2016-06-15 07:55
@1amirjalai and everyone who wants to help: Would it be possible to provide a sample working project, which demonstrates the issue with the Microsoft.Extensions.CompilationAbstractions and Microsoft.Dnx.Compilation.CSharp.Abstractions namesapces?

We need such a project to test the hotfix before providing it publicly. 

Thank you in advance!

@1amirjalai - Once the hotifix passes validation we will launch it asap.

**Comment by Asshiah** [comment] 2016-06-15 12:03
@Jekata 
Here is a sample solution demonstrating the problem:

[DemoSolution](http://s000.tinyupload.com/?file_id=08788484944091094743)

**Comment by tsvetomir** [comment] 2016-06-16 11:22
We've pushed a fix for this error and a 2016.2.616 version will be available soon on nuget.org

Two important notes:
* Use the 2016.2.607 version of the scripts on the CDN
* Add the following code to the Configure method in Startup.cs:

```cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    // ...

    // Configure Kendo UI
    app.UseKendo(env);
}
```

Apologies for the caused inconvenience!

**Comment by tsvetomir** [comment] 2016-06-16 15:39
It should be live now. Let us know if you still have issues.

**Closed by tsvetomir** 2016-06-16 15:39 UTC
Labels: Bug, S: Wrappers (ASP.NET MVC), SEV: High

**Comment by alaatm** [comment] 2016-06-16 18:48
@tsvetomir Why is the framework set to netcoreapp1.0 ? Shouldn't it be netstandard1.x ? I can't use this package from within libraries..

**Comment by tsvetomir** [comment] 2016-06-17 07:32
There's no particular reason to use netcoreapp other than our confusion around the [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) and [.NET Core Applications](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-core-applications.md) monikers.

In any case, we intend to switch to netstandard1.5 for the next release, as this is what [Microsoft.AspNetCore.Mvc.Core](https://github.com/aspnet/Mvc/blob/1.0.0-rc2/src/Microsoft.AspNetCore.Mvc.Core/project.json#L61) targets.

Tracking this issue in #1810. We'll be publishing updated releases regularly.
