### ISSUE TITLE
Deleting a row doesn't trigger the datasource destroy action

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#2030] opened 2016-08-04 10:12 UTC
Can be reproduced on the live demos:
http://demos.telerik.com/kendo-ui/spreadsheet/datasource

Select a row and delete it through the row context menu. Press the Save Changes button.

Expected - a call to the server destroy method is triggered and the row is removed from the database.

Actual - nothing happens, and refreshing the page reveals the row is still present in the database.

**Comment by rkonstantinov** [comment] 2016-08-04 14:19
I suspect that this is side-effect of this change https://github.com/telerik/kendo/issues/5675. Maybe @gyoshev could chime in with a possible fix.

**Comment by gyoshev** [comment] 2016-08-22 10:52
Some findings: the problem is caused by the batch handling of events, which discards the change event data. Once the `sheet.batch` method wraps the insert / delete operations, the sheet binder is never notified.

I've resolved this by bringing the `insertRow` / `deleteRow` sheet events, which are handled by the binder. However, any user code that deletes rows in a batch handler will need to handle this in the same way. An alternative is to accumulate the change events in batch mode, but I'm worried about performance issues.

**Comment by gyoshev** [comment] 2016-08-22 11:01
Closed via telerik/kendo@799fa03bcb

**Closed by gyoshev** 2016-08-22 11:01 UTC
Labels: Bug, C: Spreadsheet, SEV: Medium
